### ISSUE TITLE
[Feature Request] Make workspaceCategories.js easier to customize

### ISSUE THREAD

**Issue by chabad360** [material-shell/material-shell#102]
I'd like to suggest that [`superWorkspace/workspaceCategories.js`](https://github.com/PapyElGringo/material-shell/blob/master/superWorkspace/workspaceCategories.js) be made into a `.json` file that is saved in a location specific to each user (i.e. `~/.config/material-shell/workspaceCatagories.json`).
My reason for this, is that currently the `worksapeCatagories.js` file is owned by `root` (sensibly, if installed as a package), but this seriously inhibits customization, because it only allows an authorized user to customize the interface, and applies said customization to all users. Plus, even if it's installed locally, it's hard to customize, since it's not in a easy to find location.

If this can be done (and #90 is merged), this would make customization much easier (as would a dedicated make it easier to, but doing this would help such a tool a reality).

BTW `.json` is purely arbitrary in this case, but it makes it more of a "config" file, and less likely to screw up, cause then you could just have a default/fallback config to use if the customized one gets messed up.

**Comment by nununoisy** [comment]
Customizable categories are being discussed in #60. The proposal is to store your settings within GNOME and modify them through the settings GUI in Tweaks.

**Comment by chabad360** [comment]
The current settings GUI is not very good for configuring categories. A more proper configuration tool/config file might be better suited

**Comment by PapyElGringo** [comment]
Yes indeed. It's in the pipe

**Comment by chabad360** [comment]
Thanks! Any eta? (Literally no pressure)

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
