### ISSUE TITLE
Add uninstall instructions in readme.md

### ISSUE THREAD

**Issue by tahercool1** [material-shell/material-shell#104]
I just wanted to try out the extension and see if it's for me, however after installing I had to manually dig up folders and remove the files and undo some of the shell settings it did (even after disabling from tweaks). 
It would be nice to have a few commands that the user can simply copy and paste and have it removed cleanly.

**Comment by nununoisy** [comment]
The issue with this is that there isn't a way to store the previous gnome-shell gsettings.
What files did you end up having to remove besides the extension directory?

**Comment by PapyElGringo** [comment]
We could store in our cache file the initial value before overriding them and replaced them when we disable the extension

**Comment by rowbawts** [comment]
> I just wanted to try out the extension and see if it's for me, however after installing I had to manually dig up folders and remove the files and undo some of the shell settings it did (even after disabling from tweaks).
> It would be nice to have a few commands that the user can simply copy and paste and have it removed cleanly.

What settings does it change? because I'm looking at the [requiredSettings.js](https://github.com/PapyElGringo/material-shell/blob/master/module/requiredSettingsModule.js) and I see which ones but I'm not sure how to change the other ones back.

**Comment by PapyElGringo** [comment]
It's now revert automatically the settings and the hotkeys automatically on disable.
@nununoisy Could you just add in the readme the instruction to first disable and then delete the extension folder in order to uninstall properly MS?

Cheers !
