### ISSUE TITLE
Mouse cursor disappears in the dock/bar

### ISSUE THREAD

**Issue by notagoodidea** [material-shell/material-shell#118]
I currently having a issue with my mouse cursor which "disappears" when I have no program open and when I put it in the navbar¹/dockbar². Everything is click-able and working but the cursor is not visible on the screen (put everything react if I blindly put it on the right icon/space and click or overlay).

This comportment is not consistent, sometimes the cursor is visible in those areas sometines not. Usually when I have a program open, the cursor will be hidden in the navbar/doc and in other desktops too if I switch to one. If I close a program, the cursor will be visible in the empty desktop and in the navbar/dockbar but not in the desktop where it was not before.

The issue is reproducible at least for me. If you need more details or a video of the issue, tell me.

* Fedora 30
* Gnome Shell 3.32.2
* Theme : Shell : Flat-Remix-FullPanel
* Theme : Cursor : Adwaita (<- only choice)
* Theme : Applications : Adapta-Nokto-Eta
* Extensions enabled : 
** Material Shell (from dnf)
** Caffeine + Lock Keys + Panel OSD
** Remove Dropdown arrows
** User Theme

¹ navbar = the bar with the programs names
² dockbar = the bar with the icons with the various desktops/shutdown/sounds/wifi

**Comment by nununoisy** [comment]
Have you tried disabling other extensions, just temporarily?

Also, and I'm not sure if it will help, but are you running on Wayland or X?

**Comment by PapyElGringo** [comment]
Could you check the journalctl logs while hovering your cursor above the panels?

**Comment by notagoodidea** [comment]
I have disabled Material Shell and the problem is still there. (Last time, it has gone away with disabling/renabling from the extensions panel). I will recheck those as soon as I found time to test and come back with the logs.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
