### ISSUE TITLE
Move Dock/Bar to specific screen?

### ISSUE THREAD

**Issue by bradley-varol** [material-shell/material-shell#121]
I'm using three monitors and the dock/bar is on the primary (middle) monitor, but I'd like to move it to the left monitor so that I have more screenspace on my primary display.

Is this possible?

**Comment by PapyElGringo** [comment]
Yeah you have to set your left monitor as primary

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
