### ISSUE TITLE
Minor: Nicer new window animation

### ISSUE THREAD

**Issue by myleftshoe** [material-shell/material-shell#124]
When the view is maximised, i.e. one window per page, adding a new app/window opens normal size. It then slides in from the right being maximized only when it reaches its final position. Would probably get a better effect if the window started maximized then slid in.

**Comment by PapyElGringo** [comment]
Yep but we have trouble to manipulate initial state of a window.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
