### ISSUE TITLE
gnome-terminal is not rendering full or sometimes at all on app open

### ISSUE THREAD

**Issue by danigrithos** [material-shell/material-shell#128]
![Screenshot from 2019-10-12 13-37-41](https://user-images.githubusercontent.com/8318028/66705517-c2bfc080-ecf5-11e9-9c32-2b388163b4df.png)
As the title says and the picture illustrates, the gnome-terminal is not rendering fully, the right side is missing. This gets fixed when the window is forced to move or rerender thanks to a workspace change. This has occurred in every layout, and does not matter whether it is the first app or second. 
![Screenshot from 2019-10-12 13-45-01](https://user-images.githubusercontent.com/8318028/66705562-56918c80-ecf6-11e9-999f-fdc866668cf9.png) in this one the app didn't even render on the screen. So far gnome-terminal is the only one this has happened to. I have also disable all gaps and it still occurs.

Gnome = 3.34.1
OS: Manjaro Linux
Graphics: Intel UHD Graphics 620

If there is more information I can provide that would help, please let me know.

Thanks

**Comment by LiHRaM** [comment]
I experience the same problem in the grid layout on Gnome 3.32.2.

**Comment by PapyElGringo** [comment]
Well gnome-terminal is a Nazi of sizing and refuse to be resized at a size different of multiple of the line height and a certain width. It's impossible to tile it correctly. You could use a different terminal but I currently don't have solution for it..

**Comment by LiHRaM** [comment]
Well, in my experience this is an issue which occurs for all gtk apps. Gnome settings, fractal, gnome-terminal, etc. Some of these I run using snaps, others with apt. Seems to have the same effect.

**Comment by nununoisy** [comment]
Are you guys on XOrg perchance? I feel like I have less problems with these apps when using Wayland

**Comment by codycraven** [comment]
This happens to me all the time consistently in Xorg. I use my hotkey for moving the window left to make it appear.

**Comment by PapyElGringo** [comment]
It's only happen in the experimental tiling layouts right?

**Comment by nununoisy** [comment]
I experience it in every layout. The animation plays like the window was resized then it disappears. Upon moving to a different workspace and back, the window is visible in the correct position.

I don't have any of these issues on Wayland. I'm not sure if this bug is in Material Shell, GNOME Shell, or X.org.

**Comment by LiHRaM** [comment]
I experience this on Wayland as well, but only in tiling layouts.

**Comment by codycraven** [comment]
I don't know which layouts are experimental and which are not.... the tiling layouts (practically the only ones I use) all have this issue. The ones I use are: Split, Grid, and Simple (I assume the other tiling layouts do as well).

Float and Maximize do not have this issue.

I'm using Xorg.

**Comment by codycraven** [comment]
As a note, I'm not longer encountering this issue after updating to latest master. I think it has been resolved in commit 689c32e or a9d721f

**Comment by codycraven** [comment]
Update, I thought it was fixed but I started encountering issues. When I am in Grid and a browser (Brave) or Slack are the application already running opening my terminal continues to not appear. However this is not occurring when VSCode is the application.

Reproduction steps:
- Open three applications all in grid:
    - Slack (electron based chat application) in communication workspace
    - Brave (chromium based browser) in web browser workspace
    - VSCode (electron based code editor) in code workspace
- In communication workspace open terminal, terminal does not appear (can be moved with key binding) to make appear
- In web browser workspace open terminal, same result as communication workspace
- In code workspace open terminal, terminal appears as expected
- Move Brave web browser into code workspace (with VSCode running, no other windows present) open terminal terminal does not appear
- Move VSCode into browser worskspace (no other windows present) open terminal, terminal appears as expected

**Comment by Chrysostomus** [comment]
Proposed fix in #158 seems to have fixed also this issue thusfar.

**Comment by PapyElGringo** [comment]
Is fixed on the current version
