### ISSUE TITLE
Close apps/workspaces when pressing buttons on the sidebar/tabbar

### ISSUE THREAD

**Issue by YohananDiamond** [material-shell/material-shell#138]
After opening the workspaces or apps view from GNOME, if pressing a button from the sidebar or the tab bar, its corresponding action works but the view doesn't close.

For example, I opened the apps view, but I reminded I wanted to check something on another tab. If I press the tab's button, the current tab changes to it, but the apps view doesn't close and it's needed to press the hamburguer menu on the top-left edge of the screen or press the super key to do so.

![image](https://user-images.githubusercontent.com/23298480/67353482-0e117480-f529-11e9-97c6-fd59a0ea377c.png)

**Comment by nununoisy** [comment]
AFAIK this is intended behavior, at least for GNOME.

@PapyElGringo, I'll leave it to you as to whether or not we do anything about this.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **IS** deprecated
