### ISSUE TITLE
Windows dont place properly

### ISSUE THREAD

**Issue by CodeAndGin** [material-shell/material-shell#142]
Im having an issue where in grid/ratio mode windows place in weird locations half off the screen and subsequently anchored on the same spot in the top left. Cycling through the modes places them in the right spot but I'm not sure whats causing it, because it was working as intended a few days ago. Having this issue on both my desktop and laptop. What stuff should I provide for debugging?

**Comment by nununoisy** [comment]
Check out [CONTRIBUTING.md](https://github.com/PapyElGringo/material-shell/blob/master/CONTRIBUTING.md) in the future - it has all of the info you should submit.

Although since you are dealing with a graphical bug, I would make sure to include a screenshot.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
