### ISSUE TITLE
Doesn't work + oversize panel + panel indicators are cut

### ISSUE THREAD

**Issue by Amathadius** [material-shell/material-shell#148]
Does not work at all except that the width of the panel exceeds the screen and that the areas are too small (the date is cut for example)

Archlinux
aur/gnome-shell-extension-material-shell-git r277.ge789ded-5
gnome-shell 1:3.34.1+56+gbb24df2f9-1

**Comment by nununoisy** [comment]
Would you be able to post a screenshot?

**Comment by jamespotz** [comment]
Mine works but my lockscreen has the weird long panel and the icons are cut
![IMG_20191202_162624](https://user-images.githubusercontent.com/4239625/69943847-b73d7a00-149a-11ea-8c07-1238cbad0877.jpg)
I am on pop os 19.10

**Comment by Amathadius** [comment]
There is my screenshot
![Capture d’écran du 2019-12-02 07-34-00](https://user-images.githubusercontent.com/9408075/69960067-92ff8e80-14d6-11ea-9e13-6515a7e90075.png)

**Comment by nununoisy** [comment]
Looks like the style isn't correctly cleaned on disable. I'll see if I can work out a fix.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
