### ISSUE TITLE
Electron apps have box-shadow around frameless windows

### ISSUE THREAD

**Issue by oae** [material-shell/material-shell#155]
+ [x] **Output from `git show`.**
```bash
commit beb5c15940626ac6c41aa8579a51761438d2af10 (HEAD -> master, origin/master, origin/HEAD)
Merge: adb8101 e190db9
Author: PapyElGringo <adrien@pesler.be>
Date:   Thu Dec 5 10:57:19 2019 +0100

    Merge pull request #149 from bbil/layout-ripple
    
    Fix Ripple effect on tiling button
```

+ [x] **Are you using Wayland or X.org?**
I am on X.org
+ [x] **A detailed explanation of the bug.**
Electrons apps with frameless windows have weird box-shadow around them. This only happens when I enable material-shell.
It should be like this;
![image](https://user-images.githubusercontent.com/1043714/71561615-d293a900-2a89-11ea-8141-f5d4168cb911.png)
But when I enable material-shell, windows become like below;
![image](https://user-images.githubusercontent.com/1043714/71561502-4a60d400-2a88-11ea-9cee-bafcb96a707d.png)
You can reproduce it by running [LISTEN-moe](https://github.com/LISTEN-moe/desktop-app) or [Kitsu Launcher](https://github.com/oae/kitsu-launcher)

**Comment by PapyElGringo** [comment]
Okay thanks for your feedback ! Will look into it

**Comment by nununoisy** [comment]
I'm guessing this is a result of adding drop shadows to windows. Although I'm not sure how we can detect a frameless window, but if we could figure that out it would be easy to exclude them from the drop shadow.

**Comment by oae** [comment]
Is it possible to disable the shadow? I commented out all CSS rules but windows still have the shadow around them

**Comment by nununoisy** [comment]
Where did you comment out the CSS? Let me take a look and see where the shadows are coming from.

**Comment by oae** [comment]
from `stylesheet.css`, I commented out everything. Then reloaded the shell. It was a mess but still had the shadows
![image](https://user-images.githubusercontent.com/1043714/71634138-8a5fbc80-2c2a-11ea-913c-d273ad5ed512.png)

**Comment by nununoisy** [comment]
Interesting... for some reason I can't get either program running at the moment, so I can't test anything. Have you tried changing your GTK theme (and what are you using right now)?

**Comment by oae** [comment]
I use Plata-noir theme. I have changed it to Adwaita but still have the shadows. Only disabling the extension removes the shadow. 
Listen.MOE has [appimage](https://github.com/aklein13/listen-moe-electron/releases/download/v0.6.17/ListenMoe-0.6.17.AppImage). It may be easier to launch it that way

**Comment by oae** [comment]
I found out that `xprop` command call causes this issue. https://github.com/PapyElGringo/material-shell/blob/a9d721f31a50286f0ae551efa8f8d15c5d04da33/utils/windows.js#L19-L29

**Comment by nununoisy** [comment]
That `xprop` command is to change the visibility of the titlebar (to make them go away or come back in float mode).

Quick question - what happens when you enter float mode on a workspace with the frameless windows? If that fixes the issue it would be worth figuring out what is going on with Electron.

**Comment by oae** [comment]
In float mode, it adds decorators
![image](https://user-images.githubusercontent.com/1043714/71833202-8534be80-30bd-11ea-863f-2ae044baf73f.png)

**Comment by nununoisy** [comment]
Weirdly enough, Listen.MOE doesn't exhibit this behavior on my machine. One more thing to try: change line 28 of `utils/windows.js` from
```js
`2, 0, ${visible ? '1' : '2'} 0, 0` 
```
to
```js
`2, 0, ${visible ? '1' : '0'} 0, 0` 
```
Then restart your session with `Alt+F2` and `r`.

**Comment by oae** [comment]
After changing it, shadows are gone. It looks ok now.

**Comment by nununoisy** [comment]
Awesome! I think it needs more testing but we should have this fixed.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.

**Comment by LogicWrite** [comment]
in wich relased version of electron i can make use of this fix?
