### ISSUE TITLE
FEATURE REQUEST: Option to get rid of "dock" in the center of the desktop

### ISSUE THREAD

**Issue by pyro57** [material-shell/material-shell#157]
This isn't an issue more of a feature request, and if this is already a thing please let me know but I would like to be able to remove that "dock" in the center of the desktop that holds the apps for that category.

Not that they have to be removed by default or anything, but the option would be nice.

Thank you.

**Comment by xsgb** [comment]
There's this issue talking about hiding the application box here: https://github.com/PapyElGringo/material-shell/issues/56

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.

**Comment by xsgb** [comment]
Thanks for your investment on the project. I'm still using it since I've tried once 6 months ago.
