### ISSUE TITLE
Some windows are invisible

### ISSUE THREAD

**Issue by logix2** [material-shell/material-shell#158]
Some windows are invisible with material-shell (latest Git). This happens for the GNOME Terminal window for example (Ubuntu 19.10, GNOME Terminal 3.34.2, GNOME Shell 3.34.1+git20191024-1ubuntu1~19.10.1 as is in this Ubuntu version), and the ULauncher preferences window, with Material Shell layouts like Ratio. 

It doesn't happen with layouts like the one in which 2 windows are side by side, or in maximize all windows.

This [https://github.com/PapyElGringo/material-shell/pull/92](https://github.com/PapyElGringo/material-shell/pull/92) pull request mentions a workaround that fixes this issue:

> @paradoxxxzero The source of the bug of the window ghosting is this line in `baseTiling.js`:
> 
> Around line 175:
> 
> ```js
> if (frame.width !== width || frame.height !== height) {
>     log(
>         'Force resize of',
>         metaWindow.get_title(),
>         `${newWidth}x${newHeight} -> ${width}x${height}`
>     );
>     // Some windows have invisible padding
>     // actor is larger in this case and we need to clip
>     // only visible area
>     actor.set_clip(frame.x - newX, frame.y - newY, width, height); // <-- this is the issue
> ```
> 
> If I comment out `actor.set_clip`, the ghosting is fixed. I don't really understand this code though so there's prolly a better fix than removing the line.
> 
> EDIT: this seems to have fixed it maybe by changing the equality checks on the IF statement:
> 
> ```js
> if (frame.width < width || frame.height < height) {
> ```

I'm not sure what this affects though.

**Comment by Chrysostomus** [comment]
This fix seems to improve the situation a lot. The ghosting is pretty much gnome and the experience is much more usable.

**Comment by Chrysostomus** [comment]
Further testing shows that the fix work on wayland, but does not affect the behavior on X11

**Comment by PapyElGringo** [comment]
Im currently rewriting completely the tiling engine so it's will be obsolete in the next release. Let's check this then.

**Comment by Chrysostomus** [comment]
Good luck and thank you for your efforts!

**Comment by Chrysostomus** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/12002226/81168477-bbb51400-8f9f-11ea-9cef-a396e10c1ec6.gif)

I'm really hoping this gets fixed. Besides this issue, the extension feels ready to package and ship. The art and code for it is already added gnome layout switcher, it just needs to be enabled. I'm probably replacing the mate layout with material shell. We could probably ship it already if we enforced wayland with it, but that would get messy and we ship xorg by default.

![Screenshot from 2020-05-06 13-51-42](https://user-images.githubusercontent.com/12002226/81169001-bd330c00-8fa0-11ea-992a-358cdbdd9438.png)

Is there anything that would help this issue?

**Comment by hosler** [comment]
I am also experiencing what @Chrysostomus has detailed in his gif. Seems to be mostly terminal applications that do this.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
