### ISSUE TITLE
Drop Down Terminal

### ISSUE THREAD

**Issue by ishan9299** [material-shell/material-shell#160]
I have a drop down terminal setup (Tilix) with "tilix --quake" option but when the terminal comes up it tiles. If I use the floating layout it will work fine it would we amazing it I am able to keep that terminal floating in any layout I want
![Screenshot from 2020-01-30 19-31-43](https://user-images.githubusercontent.com/47824004/73456182-7331fd00-4397-11ea-920a-a5f677314972.png)
![Screenshot from 2020-01-30 19-33-06](https://user-images.githubusercontent.com/47824004/73456194-7927de00-4397-11ea-9ca2-ace1b173f185.png)

**Comment by severino32** [comment]
same here, it would be great!

**Comment by nununoisy** [comment]
This probably wouldn't be hard to implement. However, the focus right now is on customizable categories. From what Papy has said that should be done soon.

**Comment by ishan9299** [comment]
Something similar to scratchpads would be a nice addition and better alternative to the dropdown mode in some terminals

**Comment by JohnnyUrosevic** [comment]
this is the number one thing preventing me from using this extension full time, can anyone point me to a relevant part of the code so I could maybe work on a pull request?

**Comment by nununoisy** [comment]
@JohnnyUrosevic check the /tilingManager/tilingLayouts/baseTiling.js class - it should have what you need. You would need to import WindowUtils and add an exception based system per window to forcefully re-add the title bar. It would require some refactoring but it should be possible.

**Comment by PapyElGringo** [comment]
@JohnnyUrosevic @nununoisy 
I think the easiest way to achieve that is to create a new input in the extension settings to define either excluded applications or window class and to check them in the handleByMaterialShell function to ignore them.
Easy peasy

**Comment by PapyElGringo** [comment]
I pushed this in my last commit https://github.com/material-shell/material-shell/commit/15183774f2b393a32bdbbc69fc244f6e62d87bd9. Could you give it a try? There is a new entry in the settings to exclude some window classes.

**Comment by ishan9299** [comment]
It works fine sorry for the late response I will close the issue.
