### ISSUE TITLE
Focus frame/border

### ISSUE THREAD

**Issue by renestalder** [material-shell/material-shell#162]
Went through all the settings and assume there is no built-in feature.

In WMs like i3, there is a way to set the border width and colour for the focused window. 

In Material Shell, the only indicator currently is the active tab in the top bar and additionally, in some programs, the colour of the window controls.

With an additional way to set border width and colour, keyboard usage would be improved as one doesn't have to check the top bar for the active application. Eyes can remain where they naturally would be: On the program you wanted to focus.

**Comment by nununoisy** [comment]
I really like this idea - its a great UX improvement. I'm just struggling to think how this would fit in with Material Design - I'm sure there is a way but I need to do some research first. Maybe it could be implemented with drop shadows, where distance from the background changes with focus (i.e. the focused window would be "further away from the background"). This would be a subtle but useful indicator.

**Comment by nununoisy** [comment]
Also, I'm not sure if adding borders or shadows can be done reliably with this extension seeing as that is usually handled by GTK CSS - perhaps we would need to override it.

**Comment by PapyElGringo** [comment]
There is now  focus effect and you can configure it as border on the settings
