### ISSUE TITLE
Sidebar located in the middle of the screen

### ISSUE THREAD

**Issue by yannisgu** [material-shell/material-shell#163]
Afte the material shell worked seamlessly for couple of weeks, after this weekend the sidebar is located in the middle of the screen. 
I have no idea how to debug this, so any hint would be appreciate. 

![Screenshot from 2020-02-17 08-26-47](https://user-images.githubusercontent.com/1180984/74632415-9a424a00-515f-11ea-86bc-def938670488.png)

**Comment by PapyElGringo** [comment]
Search for incompatible extension either a new extension you installed or an extension that updated

**Comment by nununoisy** [comment]
Are you on XOrg or Wayland? Does restarting GNOME fix the issue? And try disabling other extensions like @PapyElGringo said.

**Comment by PapyElGringo** [comment]
Any update? Should I close this?
