### ISSUE TITLE
Tile into 3 colums?

### ISSUE THREAD

**Issue by murbanowicz** [material-shell/material-shell#164]
Hi,
It looks great however on the UltraWide it is almost necessary to have option to split screen into 3 colums instead of classical 2 colums and quaters. 
Do you think it is possible with Material Shell?

**Comment by nununoisy** [comment]
Currently this is not possible on the master branch. You can however try out my experimental fork #141 that will allow you to do this.

**Comment by velovix** [comment]
I believe this is achievable using the "Simple" layout. It looks like this on my ultrawide:

![Screenshot](https://i.imgur.com/EZuz24Z.png)

**Comment by PapyElGringo** [comment]
What about this?

**Comment by velovix** [comment]
I still use this layout every day, now on v2 beta, and it works just fine. I didn't file the issue but I think it can be closed.

**Comment by lfom** [comment]
Is it OK to update PR #141 to close this?

By the way, is there any special reason why gaps isn't shown in the split view? I did some work to show gaps in split view and hide them if only AppLauncher is shown, should I make a PR for this?

**Comment by PapyElGringo** [comment]
Well im not really fan of this PR. Your idea was to use the hotkeys to
increase / reduce the number of split in the split view ?

**Comment by lfom** [comment]
@PapyElGringo Yep, like the original PR: split view from 2 to 5, and increase/decrease ration in 0.05 steps.

And what about the gaps in split layout?

**Comment by PapyElGringo** [comment]
It's was initially meant to be use with the native split which was incompatible with gap since is maximized half left and maximized half right but if there is gap I accept to make it gapped !

**Comment by lfom** [comment]
> Well im not really fan of this PR. Your idea was to use the hotkeys to increase / reduce the number of split in the split view ?

Actually it works quite well with the Ratio layout, at least you can adjust the width of the main window, what is quite nice IMHO. And the greater split values may work great for anyone with ultra-wide monitors.

**Comment by dwrolvink** [comment]
Seems fixed now yeah?
![image](https://user-images.githubusercontent.com/30291690/97780455-157c4c80-1b85-11eb-9960-b36a5a9a7caa.png)

Layout simple allows this behavior.

**Comment by PapyElGringo** [comment]
With the resize implemented and the customization of column in split layout this should be good
