### ISSUE TITLE
Keyboard shortcut for specific layout

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [material-shell/material-shell#169]
I would love to have a keyboard shortcut for a specific window layout, so e.g. `Super+X` for floating, `Super+Y` for split or `Super+Z` for maximized. This may be important if you use more than 3 different layouts because then cycling between all those layout takes lots of time and may become confusing.

**Comment by PapyElGringo** [comment]
Okay, I can understand the need to switch to a specific layout with a shortcut but why do you want to activate more than 3 layouts if you want to switch only between three of them?

**Comment by JasMich** [comment]
I would like to switch *to* a specific layout. I don't want to activate more layouts then I want to cycle threw. `3` was just an example as well as the stated keybindings were.

**Comment by dwrolvink** [comment]
It's now possible to quickly select a layout with two clicks:
![image](https://user-images.githubusercontent.com/30291690/97780685-62acee00-1b86-11eb-9ed1-0be2cd2b0717.png)

Still, a lot of keyboard-centric people would enjoy being able to set keyboard shortcuts I reckon.

**Comment by dwrolvink** [comment]
For the last point, there is an open issue for that: https://github.com/material-shell/material-shell/issues/261
