### ISSUE TITLE
Add support for Peek

### ISSUE THREAD

**Issue by busybox11** [material-shell/material-shell#172]
Peek is very buggy on the current release of Material Sheel, it is unusable.
Is it possible to make it usable properly anywhere ?

**Comment by busybox11** [comment]
Also, I've just discovered that windowed DevTools are not usable too

**Comment by skluthe** [comment]
Have you tried peek with a float layout? Also just so the devs are aware, peek is screen recording software that creates gifs.

**Comment by PapyElGringo** [comment]
Since it's work in float mode and you can add it to window exception in the settings I consider this close
