### ISSUE TITLE
Add support for/fix Waylands per-display scaling

### ISSUE THREAD

**Issue by l1k3ab0t** [material-shell/material-shell#174]
Gnome on Wayland supports per-display scaling which is not used/supported in material-shell.

At the current state material-shell uses the scaling of the "main" display for all Monitors.
This leads to issues in setups with multiple monitors of different resolutions/scaling.
As you can sees in the following screenshot:
![Screenshot from 2020-04-09 16-11-41](https://user-images.githubusercontent.com/22274293/78932006-12b1f100-7aa7-11ea-9c87-101a839f007f.png)
Both monitors are about the same size but have different resolutions (3840x2160 @ 200% scaling and 1920x1080 @ 100% scaling). 

### Occurring Issues:

- Scaling of fonts/icons is wrong.
- Closing Apps on through the Taskbar on the second display can cause crashes of material shell and logout.
- (On the above Setup) Dragging certain apps to the wrongly scaled monitor causes them to be automatically moved to the next monitor.

**Comment by PapyElGringo** [comment]
This could be fixed with the last release
