### ISSUE TITLE
Transparent Header when switching to previously full screen workspace

### ISSUE THREAD

**Issue by Parkar99** [material-shell/material-shell#176]
![Screenshot from 2020-04-29 23-21-45](https://user-images.githubusercontent.com/50555895/80629659-ca1ba100-8a70-11ea-8ba7-34ee1fc047a4.png)

The above screenshot shows how the header is transparent showing the desktop background.

### Steps to reproduce
- Toggle simulate full screen for the workspace to go full screen
- Switch to another workspace while still full screen
- Toggle off full screen
- Switch back to original workspace to find transparent header

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
