### ISSUE TITLE
material-shell does not restore original settings when disabled.

### ISSUE THREAD

**Issue by trusktr** [material-shell/material-shell#178]
This is a neat project! I am looking forward to the edges getting smoother. One thing that I found annoying was when I disabled the extension, various settings were messed up (I had to go change them manually in Tweak Tool, Gnome Settings, or dconf).

It would be great if material-shell would not mess up the settings (somehow), or perhaps record them and restore them after disabling the extension.

**Comment by PapyElGringo** [comment]
Yeah I know sorry ! I've planned to record changes and restore on disable but didn't found any time to do it yet ! But I'll try to prioritize it
