### ISSUE TITLE
Make bloat optional

### ISSUE THREAD

**Issue by danielsouzat** [material-shell/material-shell#179]
There's nothing wrong in innovating. The extension brings new features like categorized workspaces in a unity-like dock and while that may be awesome for some people I couldn't sticky it with my workflow. I suggest that you make it optional so those who dislike it could still use the extension and  sticky with the tilling window management features.

**Comment by nathanmiddleton** [comment]
I'm not the author, but I don't see how this wouldn't just become another dash-to-panel + some kind of window formatting tool if you just make it's point optional.

**Comment by danielsouzat** [comment]
I don't see how it would become another dash-to-panel. Right now there are now tilling window management features in GNOME. The closer we have besides this extension is PaperWM but it lacks features and maturity. Apparently you don't know what a tilling/dynamic window management is. Also I don't get why giving users the option to better adjust the extensions to their need and wishes would in any way be prejudicial to the users that do wish to use the before mentioned features.

**Comment by PapyElGringo** [comment]
Hey daniel thanks for your feedback.
First I want to say that in the next version the categories are removed for a new system that will allow everyone to customize their workspace themselves.
Secondly Material-shell is primary a Workflow not a tiling manager. That's mean that every line of code has been made to optimise this workflow and not to propose a standalone tiling manager.
If you are only searching a tiling engine with gnome interface you should seek over the Pop shell.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
