### ISSUE TITLE
Windows only show for current workspace in Gnome application menu

### ISSUE THREAD

**Issue by velovix** [material-shell/material-shell#183]
In this case, I have windows open in all my workspaces. However, in the workspace preview on the right, I see windows only on my current workspace:

![](https://i.imgur.com/WuKj0uN.png)

If I switch to another workspace, I see the same behavior for that workspace:

![](https://i.imgur.com/4QDWvMB.png)

Apologies if this issue description is confusing. I don't know the official term for these Gnome UI elements.

Material Shell version: 125a0dc (installed through the AUR package)
Gnome version: 3.36.3 (running with X)

**Comment by PapyElGringo** [comment]
This is caused by the way we minimize hidden windows. I'll need to think of different condition

**Comment by velovix** [comment]
Looks good on my end. Thanks!
