### ISSUE TITLE
UI Scaling is not consistently applied

### ISSUE THREAD

**Issue by matthewwardrop** [material-shell/material-shell#185]
I run this on a 4k monitor with 200% scaling; but the material shell doesn't properly scale icons in open new app mode (icons appear to be 400% scaled, but clipped to the 200% size).

![Screenshot from 2020-06-16 20-29-19](https://user-images.githubusercontent.com/124910/84851962-7b21cf00-b010-11ea-9c7e-61f672d6330f.png)

I have installed material shell using git (current hash `01cca4f956797d506735a2f04e973ff1ba01553d`), and am using Wayland.

**Comment by matthewwardrop** [comment]
Thank you!

**Comment by PapyElGringo** [comment]
Don't hesitate to reopen if you find more scaling issues!
