### ISSUE TITLE
RFE: Allow dragging of windows to new workspace / app groups

### ISSUE THREAD

**Issue by matthewwardrop** [material-shell/material-shell#186]
Currently you can drag windows to rearrange them within an app group. I'd love to be able to drag a window into another app group (or onto the + to create a new one).

**Comment by chris314b** [comment]
+1

**Comment by PapyElGringo** [comment]
If you pick up a window with super+click and then switch workspace with Super+S or Super+W the window should follow you in the different workspaces

**Comment by lfom** [comment]
Or press Super/click the looking glass and then move the window/app to an existing or new workspace (app group).

PS: great extension, works really well. Great job!
