### ISSUE TITLE
"fully persistant" mode doesn't work on debian testing after reboot or close/open the session

### ISSUE THREAD

**Issue by chris314b** [material-shell/material-shell#187]
On debian testing (bullseye, gnome 3.36.2, with Intel HD Graphic 500 APL 2), the "fully persistent" option doesn't work after reboot or close/open the session: MS forgets the applications marked as "fully persistent" and displays only one workspace, with one fully persistent app (picture: before / after reboot). 100% reproducible on my computer, both on Xorg and Wayland.

![Screenshot-1a-before](https://user-images.githubusercontent.com/67124994/85197470-6cbe0680-b2e1-11ea-9424-16f997b322ce.png)
![Screenshot-1b-after](https://user-images.githubusercontent.com/67124994/85197472-6d569d00-b2e1-11ea-98b5-a312849e468d.png)

**Comment by PapyElGringo** [comment]
Can you try disable all exensions except Material-shell?

**Comment by PapyElGringo** [comment]
Probably related to an incompatible extension.

**Comment by chris314b** [comment]
> Probably related to an incompatible extension.

Indeed: it was the "auto move windows" extension. Thanks.
