### ISSUE TITLE
The "fully persistent" doesn't always lauch an new app on debian testing

### ISSUE THREAD

**Issue by chris314b** [material-shell/material-shell#189]
On debian testing (bullseye, gnome 3.36.2) with Intel HD Graphic 500 APL 2):

The "fully persistent" option doesn't always work when I close the last windows of the tab marked as "fully persistent": either MS displays an empty windows (I see my wallpaper: cf. picture) and I can not launch an app, or MS display the screen to launch the application (picture) but that does not work (I click and nothing happens). 
Workaround: the problem disappears when I select "unmark fully persistent", then "close" the tab: MS close the app and I can reopen it and mark it at fully persistent. 
Both on Xorg and Wayland. I can't reproduce it 100%.

![Screenshot-3a-wallpaper](https://user-images.githubusercontent.com/67124994/85197903-739a4880-b2e4-11ea-9b25-843589220d9c.png)
![Screenshot-3b-nothing-happens](https://user-images.githubusercontent.com/67124994/85197905-772dcf80-b2e4-11ea-9f83-3ef51f0a3c5c.png)

**Comment by PapyElGringo** [comment]
Wayland or Xorg? Only last window?

**Comment by chris314b** [comment]
> Wayland or Xorg?

Both
> Only last window?

Not sure to understand your question. 
- the issue appears only when I close the last windows of an tab marked as fully persistant
- the issue may appears on every workspaces (see picture 2 above)
- the issue may appears on every tab in a workspace (see pictures below: neither terminal nor file can be opened on these pictures).

As a side note: this issue appears not only on debian testing, but also on GNU Guix.

![Capture d’écran de 2020-06-24 14-22-01](https://user-images.githubusercontent.com/67124994/85556708-a27f2a00-b616-11ea-95dd-770c1aea6b7b.png)
![Capture d’écran de 2020-06-24 14-22-08](https://user-images.githubusercontent.com/67124994/85556709-a317c080-b616-11ea-9e8e-e3f97df3cecf.png)
![Capture d’écran de 2020-06-24 14-23-02](https://user-images.githubusercontent.com/67124994/85556715-a3b05700-b616-11ea-96f6-0aa01472d6a1.png)

**Comment by chris314b** [comment]
I did an update of MS today and since the update, the problem is solved \o/
