### ISSUE TITLE
Material Shell seems to restart automatically after lock/unlock on debian testing

### ISSUE THREAD

**Issue by chris314b** [material-shell/material-shell#190]
MS seems to be disable after lock/unlock or after screensaver is enable: when I unlock the session, I can see the "Activity" button and all the windows opened but I can't do anything (no screenshot possible); then MS seems to restart automatically (black screen then MS Logo) and then MS displays the windows again normally. 
Note: if there are several applications in workspaces, these applications are all grouped together in the first workspace. 
100% reproducible on my computer (debian testing: bullseye, gnome 3.36.2 with Intel HD Graphic 500 APL 2).

**Comment by PapyElGringo** [comment]
There seem to have an issue with restoring the workspaces could you try with only one workspace used?

**Comment by chris314b** [comment]
Exactly: this issue only appears when there are several workspaces used. With one workspace used, there are no problems.

**Comment by PapyElGringo** [comment]
Probably related to an incompatible extension.

**Comment by chris314b** [comment]
I did an update of MS today and since the update, with the same extensions as before, the problem is solved.
