### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by StructByLightning** [material-shell/material-shell#193]
I'm on Ubuntu 18.04. I followed the install from source instructions, and in my tweaks it has an alert icon with a hover popup saying "Error loading extension". 

I'm not sure how to get a better error message but if you can tell me what to do I'd be happy to do it.

**Comment by PapyElGringo** [comment]
What is your gnome-shell version?

**Comment by PapyElGringo** [comment]
The current Master is requiring gnome-shell >= 3.34 and and in the Readme it's was wrongly said 3.32 I just updated it

**Comment by PapyElGringo** [comment]
I'll assume that the version was the cause
