### ISSUE TITLE
Allow selecting a default layout for new workspaces

### ISSUE THREAD

**Issue by gforcedev** [material-shell/material-shell#206]
**Is your feature request related to a problem? Please describe.**
Mostly I use material-shell in the "ratio" tiling mode, but sometimes I want to use an app full-screen for whatever reason. Currently then the best way to do this is by switching to the full-screen tiling mode, but this is a problem because if I have the full-screen mode enabled as an option, it is used as the default for new workspaces.

**Describe the solution you'd like**
The best and most flexible solution would be to have a keybinding which full-screens the current app in use, as this means I can keep using ratio mode normally. In addition it is a good solution because it saves on more keypresses because normally when I want an app full screen I also have to enable zen mode to achieve this.

**Describe alternatives you've considered**
A temporary workaround / alternative could be to be able to set which tiling mode is used by default or on new workspaces so that ratio mode can be used by default rather than having to change to it every time a new workspace is opened.

**Comment by gforcedev** [comment]
Just worked out this can be achieved natively with Gnome's "toggle full-screen mode" keyboard shortcut, so only the part about a default layout is actually relevant.

**Comment by PapyElGringo** [comment]
@gforcedev I was going to tell you that :)

**Comment by PapyElGringo** [comment]
Fixed
