### ISSUE TITLE
Revert Workspaces if Turned Off

### ISSUE THREAD

**Issue by YoungElPaso** [material-shell/material-shell#21]
Hi, very cool extension. However, I noticed that it creates many workspaces and alters the gnome-tweaks workspaces settings.  That's fine I guess, but if I turn off your extension, the numerous workspaces are all retained.  I dunno if this is what you intend but I'm guess not.

**Comment by PapyElGringo** [comment]
It's a side effect behavior indeed. But pretty harmless? Ideally we should revert all our modifications but It's request us to stash this informations.

**Comment by Schroedi** [comment]
My problem with the leftover currently is that I do not find where the Super+Q shortcut is configured. It shadows a custom command and is not set in the gnome keyboard settings.

How can I unbind it?

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
