### ISSUE TITLE
Some windows are lost after screen lock

### ISSUE THREAD

**Issue by flashka07** [material-shell/material-shell#211]
**Describe the bug**
Some windows are lost after screen lock in particular. I'm not sure if screen lock is the only case for this bug. 'Lost' here means that in the beginning a window is presented on any workspace and is tracked nicely by any layout, but after screen lock (Super+L) and unlock you won't be able to find and switch to this window anymore. There will be no mention of the window on any workspace. Although the window is still in Super-Tab or Alt-Tab menu.
However if you use shell reload command (Alt-F2 r Enter) the window comes back in a second after the extension loading is finished.
It happens always with *wine* windows and windows opened through *ssh -Y*.
During my short debugging session I found out that this is probably due to incomplete handling of windows with app.is_window_backed(). Such windows are filtered out in MsWorkspace.getState() and none of the code (probably) brings them back even if they are still opened.

**Expected behavior**
After unlocking your system it would be nice to have all the windows open and accessible you had before actual locking.

**Screenshots**
Run all the apps I want. So I can access them all
![before_lock](https://user-images.githubusercontent.com/1944683/87074635-d0c05480-c227-11ea-9f5e-5d9eca799bd6.png)
Lock the screen and unlock it.
![after_lock](https://user-images.githubusercontent.com/1944683/87074630-cf8f2780-c227-11ea-9b3f-b63d010d0407.png)
So you can see that at least two wine windows (Blizzard and its tray) on 3rd workspace and one window on the 2nd workspace are missing.
Reload shell using 'Alt-F2 r Enter'.
![after_lock_and_reload](https://user-images.githubusercontent.com/1944683/87074633-d027be00-c227-11ea-9191-8313b2b6e83b.png)
All the windows are back. Also you can see that their order is changed since the missing ones were added in a second after the shell is reloaded.

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Open an app like wine GUI app (may be even any app from terminal that doesn't have special *.desktop entry)
2. Lock your computer
3. Unlock
4. This app's window is missing

**Current commit**
Output from `git rev-parse --short HEAD`: `2f399a2`

**Log data**
There are no any special logs even with DEBUG enabled.

**Comment by PapyElGringo** [comment]
Thanks for the feedback and thanks for having diging it all this way down ! I'm on it

**Comment by PapyElGringo** [comment]
The windows should appear now. But they will still be reorder at the end. The issue with the window with app `app.is_window_backed()` is that we have no idea which application they are related to therefore we have a special dirty check for them to at least support them a little and at least display them.

**Comment by flashka07** [comment]
Thank you! It works now, all the windows appear back again!
And speaking of handling such windows, I think that keeping their order throught a real reboot or relog is not a necessary thing (I mean 'click here to restore' or other similar functionality), but it would be better to treat them as any other regular windows across a screen lock keeping track of them (like gnome-shell itself keeps their positions, etc) :)
Anyway it's great to have them reachable now without the need of shell reloading.

**Comment by PapyElGringo** [comment]
Gnome shell has the advantage of not being destroyed when the screen is locked ^^ for us it's like you disable / reenable the extension. But yeah if I knew how to do it easly i'll do like you said. You can create a new issue for it if you want to track that
