### ISSUE TITLE
[crash] MS does not load any more 

### ISSUE THREAD

**Issue by varsop** [material-shell/material-shell#218]
**Describe the bug**
I had the lid of my laptop closed and an exterior screen has been connected by HDMI. I opened the lid and MS went freeze. I had to restart the laptop. Now MS does not load properly. I can only see the default GNOME shell, when all other extensions are disabled and MS is enabled. It does not react to any of my shortcuts.

**Expected behavior**
MS should load when enabled via extensions but it does not. 

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36.2
- Distro: Ubuntu 20.04
- Step 1: Attach exterior screen to laptop by HDMI
- Step 2: close lid
- Step 3: login into MS
- Step 4: open lid

**Current commit**
Output from `git rev-parse --short HEAD`: `e86bce0f`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindowContent (0x55b7eeee88a0), has been already deallocated — impossible to get any property from it. This might be caused by the object having>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to get any property from it. This might be caused by the object having been d>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Could not create transient scope for PID 13449: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 13449 does not exist.
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Could not create transient scope for PID 13450: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 13450 does not exist.
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Could not create transient scope for PID 13451: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 13451 does not exist.
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Could not create transient scope for PID 13452: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 13452 does not exist.
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Could not create transient scope for PID 13453: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 13453 does not exist.
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: Object .MsWindow (0x55b7ede7cde0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C>
Jul 16 09:59:53 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #0   7fffe469c210 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/maximize.js:116 (>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #1   7fffe469c270 I   self-hosted:266 (39ea4ee4c0 @ 259)
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #2   7fffe469c2d0 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/maximize.js:114 (>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #3   7fffe469c340 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/maximize.js:68 (2>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #4   7fffe469c3a0 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:71 >
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #5   7fffe469c440 I   resource:///org/gnome/gjs/modules/core/_signals.js:133 (2c0ee119268 @ 427)
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #6   7fffe469c4b0 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:224 (2c0ee1d3a60>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #7   7fffe469c5b0 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:108 (2c0ee1d35b0>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #8   7fffe469c620 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:532 (2c0ee1d0f10 @ 1>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #9   7fffe469c690 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:512 (2c0ee1d0e98 @ 1>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #10   7fffe469c760 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:115 (2c0ee1cc8f8 @ >
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #11   7fffe469dfc0 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js:515 (2c0ee1a19e8 @>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #12   7fffe469e080 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js:485 (2c0ee1a1880 @>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #13   7fffe469e0e0 I   self-hosted:266 (39ea4ee4c0 @ 259)
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #14   7fffe469e150 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js:482 (2c0ee1a1790 @>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #15   7fffe469e210 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:100 (2c0ee1d35b>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #16   7fffe469e280 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:532 (2c0ee1d0f10 @ >
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #17   7fffe469e2f0 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:496 (2c0ee1d0e20 @ >
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #18   7fffe469e340 I   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:298 (2c0ee1d0268 @ >
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #19   7fffe469fba0 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js:334 (2c0ee1a1178 @>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #20   7fffe469fc50 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:12>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #21   7fffe469fcb0 I   self-hosted:266 (39ea4ee4c0 @ 259)
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #22   7fffe469fd70 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:11>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #23   7fffe469fe60 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:18>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #24   7fffe469ff30 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:59>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #25   7fffe469ffd0 I   resource:///org/gnome/gjs/modules/core/_signals.js:133 (2c0ee119268 @ 427)
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: #26   7fffe46a00b0 b   /home/philipp/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:147 (2c0ee1d379>
Jul 16 10:00:11 philipp-ThinkPad-T490 gnome-shell[2336]: clutter_actor_set_width: assertion 'CLUTTER_IS_ACTOR (self)' failed

**Comment by PapyElGringo** [comment]
Your state file `~/.cache/material-shell@papyelgringo-state.json` is probably corrupted. You can remove it and reload the shell and the extension should get back to work.

We need to investigate the cause

**Comment by varsop** [comment]
> Your state file `~/.cache/material-shell@papyelgringo-state.json` is probably corrupted. You can remove it and reload the shell and the extension should get back to work.

Indeed, you are right. I have removed the mentioned file and reloaded the shell and was able to use MS again.

> We need to investigate the cause

The problem when opening or closing the lid of my laptop, while I have an exterior screen connected remains. Either MS freezes or drops me out to the login screen. 

The current workaround for me is to log out from MS, close or open the lid, then log in to MS.

**Comment by PapyElGringo** [comment]
Should be good now
