### ISSUE TITLE
Toggle tiling layout from a submenu on the tiling button

### ISSUE THREAD

**Issue by niksingh710** [material-shell/material-shell#224]
Small icon in the left panel to quickly enable and disable some of the tiling options. It will be very Handy.

**Comment by dwrolvink** [comment]
Perhaps adding a right-click option to the tiling button on the top right, or have a setting to enable putting another next to it (for tablet users).

**Comment by dwrolvink** [comment]
This has been added. Click topright, click `Tweak available layout`. Click `confirm layouts` when done toggling.
