### ISSUE TITLE
Show entire title when hovering an application tab with a truncated title

### ISSUE THREAD

**Issue by maxerbox** [material-shell/material-shell#227]
**Is your feature request related to a problem? Please describe.**
I can't see the entire window name
![image](https://user-images.githubusercontent.com/12765875/88181299-f3426c80-cc2e-11ea-8e40-cda0b31efd35.png)

**Describe the solution you'd like**
Hovering an application's tab 1 sec  would display a contextual menu with entire window title
Could be compared to the "title" attribute in html.

**Describe alternatives you've considered**
Pressing the super key to open the gnome launcher, and then hovering the window.

**Comment by maxerbox** [comment]
Dash to dock already implement this behavior when hovering an icon : 
![image](https://user-images.githubusercontent.com/12765875/88183139-5d5c1100-cc31-11ea-92ca-ff919f4b8d4f.png)

**Comment by maxerbox** [comment]
Good point from @GoshaEgorian :
> Alternative, it can be implemented by drag-drop action on dock and lock option by right mouse button (window's like style).

**Comment by maxerbox** [comment]
Fixed by 20e2bc1eb58c986fae1cbad6e0388e51553e0421

**Comment by PapyElGringo** [comment]
So you noticed 😉

Le dim. 25 oct. 2020 à 11:11, Simon Sassi <notifications@github.com> a
écrit :
