### ISSUE TITLE
[Feature Request] Hotkey for launching a new program

### ISSUE THREAD

**Issue by MithicSpirit** [material-shell/material-shell#234]
There should be a hotkey that can open the window for launching a new program, which should do the exact same thing as clicking on the `+` button on the top panel. Currently the same can be achieved (sort of) by either using GNOME's default menu that pops up when the `Super` key is pressed or by navigating to the right (by default `Super`+`D`) until reaching the `+` icon, the first of which is inadequate because I prefer the Material Shell menu the GNOME menu and the second requires that I switch to many different windows if I am not currently on the last window in the workspace.

**Comment by quaintdev** [comment]
This is really needed!

**Comment by RidgeA** [comment]
Super+X works for me, not sure why, I've just installed the Material Shell ))

**Comment by MithicSpirit** [comment]
Yes, this feature appears to have been added somewhat recently (unsure about which version/commit in specific though).
