### ISSUE TITLE
Incorrect gap size at the top and bottom edges of screen

### ISSUE THREAD

**Issue by MithicSpirit** [material-shell/material-shell#235]
### Describe the bug
The gap at the top and bottom edges have a gap that is equivalent to 1/2 of the `Gap size` value (regardless of what `Use a different gap size for screen` and `Screen edge gap size` are set to). I believe this has to do with https://github.com/material-shell/material-shell/blob/f58ec05c2830c6f5c9ad0d5184e619820f570e7b/src/layout/msWorkspace/tilingLayouts/baseTiling.js#L1-L369

More specifically, I believe the issue is that the `applyGaps` function is incorrectly detecting whether the window is at the top/bottom edge of the screen, and therefore using `halfGap` rather than `edgeGap`.

### Expected behavior
The gap at the top and bottom of the screen should be the same as the gap on the sides of the screen.

### Screenshots
![Screenshot from 2020-07-28 23-06-40](https://user-images.githubusercontent.com/24192522/88823092-b0364b00-d192-11ea-85fe-7198b7c1843c.png)
The gap on left and right is 100 px wide, the one in between windows is 50 px wide, and the one at the top and bottom is only 25 px wide.

### To Reproduce
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36.3
- Distro: Ubuntu 20.04 LTS
- Steps to reproduce, if applicable:
  1. Open the extension settings
  2. Set `Gap size` to a nonzero number
  3. Optionally enable `Use different gap size for screen` and set `Screen edge gap size` to a number that isn't exactly half of `Gap size`
  4. "Refresh" the window positions (restart GNOME, move to a different workspace, or move around a window).
  5. Observe the gaps at the top and bottom in contrast with the sides (depending on values, it might be helpful to check the gap sizes with GIMP or similar)

### Current commit
Output from `git rev-parse --short HEAD`: `f58ec05`

### Log data
Output from `journalctl /usr/bin/gnome-shell`:

My logs are pretty long and I don't think they're that important for this issue. That said, I could provide them if they're actually necessary.

**Comment by MithicSpirit** [comment]
This now appears to be fixed. I believe it is due to commit a527302785611f387239cb989133197cf14afaa7.

**Comment by PapyElGringo** [comment]
Indeed :+1:
