### ISSUE TITLE
Pycharm floating window with list of projects is not being displayed

### ISSUE THREAD

**Issue by talhajunaidd** [material-shell/material-shell#236]
**Describe the bug**
Thanks for such a  nice shell. I really liked it on the first try.
I'm using PyCharm for development. This is a floating window. When I launch it with Material Shell it disappears.

**Expected behavior**
Material Shell should show that floating window

**Screenshots**

![image](https://user-images.githubusercontent.com/6547611/89053866-4a53ea00-d371-11ea-901f-2898b37432c6.png)

**Comment by talhajunaidd** [comment]
I just upgraded pycharm version to 2020.2 and now it is displaying the window.

**Comment by log-linear** [comment]
I also have this issue. As a workaround, you can run it from the terminal on a directory and it will open it as a project, e.g. 

```sh
charm $HOME
```

From there click on `File > Close Project` to open the startup window.

**Comment by PapyElGringo** [comment]
Should be okay now
