### ISSUE TITLE
Unable to use windows moved to second or third monitor on recent update

### ISSUE THREAD

**Issue by HaisojYellams** [material-shell/material-shell#237]
**Describe the bug**
After updating Material Shell this morning (to `d56953f`), all of my windows were placed on my primary monitor. I was unable to move the windows to my left/right monitor with my normal shortcut (`SHIFT-SUPER-ARROW`), and dragging the window to the desired monitor via mouse displayed the tab but did not render the window. Using the Material Shell shortcuts to scroll through windows didn't seem to notice the existence of that window on that monitor. (The window tab also appeared to the right of the '+'/Add window button). Sorry I did not take screenshots of the error.

After reverting the extension back to `f58ec05` (From Jul 23rd), everything still works as expected.

Please let me know if you need more details. Thanks for your work on this - I love Material Shell!

**Expected behavior**
I expected to be able to place windows on my second and third monitors on the most recent update, but was not able to view the windows once dragged there.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.34.5
- Distro: Fedora 31 (Linux 5.7.9-100.fc31.x86_64)

**Current commit**
Commit `f58ec05` works correctly. Commits `7903f91` and `d56953f` did not.

**Log data**
No relevant logs.

**Comment by PapyElGringo** [comment]
I rollbacked some of the code should be good now

**Comment by HaisojYellams** [comment]
Just updated to the newest commit. Everything looks to be in working order. Thanks for the quick update!
