### ISSUE TITLE
Error loading extension on Void Linux

### ISSUE THREAD

**Issue by smolck** [material-shell/material-shell#241]
**Describe the bug**
After installing the extension via the "source" method and following the steps, I can't enable the extension. In tweaks it just says "error loading extension" and won't let me enable it.

**Expected behavior**
I'd like to be able to enable the extension ;)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.34.1
- Distro: Void Linux
- Steps to reproduce, if applicable:
1. Follow instructions in README to install extension from source.
2. Open tweaks and try to enable extension
3. Can't enable extension due to "error loading extension"

**Current commit**
Output from `git rev-parse --short HEAD`: `1a1f25e`

**Log data**
Void Linux doesn't use systemd, so I have no `journalctl` command.

**Comment by PapyElGringo** [comment]
Try to update to Gnome SHELL 3.34.4

**Comment by smolck** [comment]
I'm gonna close this; I've switched back to Arch Linux, and even before I did there didn't appear to be an easy way to update the version (without doing xbps-src and template modifying and such). But I think Void will be updating the GNOME version soon to 3.38 (see https://github.com/void-linux/void-packages/pull/24260), so this shouldn't be a problem much longer if it is related to the version.
