### ISSUE TITLE
Option to show System Panel on the right

### ISSUE THREAD

**Issue by lfom** [material-shell/material-shell#245]
**Is your feature request related to a problem? Please describe.**
I know Ubuntu and Gnome keep the dash on the left, but actually it is much better/faster to have the icons you access/use most on the right side of the screen (macOS is a good example of this).

**Describe the solution you'd like**
Option in settings to move the system panel to the right, while keeping the top bar intact (keep the search and layout switcher where they are).

**Describe alternatives you've considered**
None.

Thanks for the great work! Regards.

**Comment by dwrolvink** [comment]
I think it might be a good idea to be able to set **both** the system bar and the application bar in the extension settings. Pretty big change and might effect other bugs though (like this one https://github.com/material-shell/material-shell/issues/283).
