### ISSUE TITLE
Shell does not start after background blurring has been activated

### ISSUE THREAD

**Issue by AlexHo1982** [material-shell/material-shell#247]
**Describe the bug**
Material Shell UI is not being initialized after background blurring has been activated.

**Expected behavior**
The shell starts after background blurring has been activated or the option is removed.

**Screenshots**
![ksnip_20200822-155206](https://user-images.githubusercontent.com/70063365/90957683-8e796c80-e48f-11ea-8b97-dd4900888b0f.png)

**To Reproduce**
- Occurs on:
  - [x ] X.Org
- GNOME Shell version: 3.34.4
- Distro: OpenSuse Leap 15.2
- Steps to reproduce, if applicable:
1. Install the extension
2. Activate the extension
3. Start Gnome Tweak tool and open settings for Material Shell
4. Activate option: Blur background 
5. Use "Alt+F2 and r", or reboot
6. Look at the issue
7. Deacitvate the option
8. Use "Alt+F2 and r", or reboot
9. Compare the results

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Comment by PapyElGringo** [comment]
This option may require GNOME Shell 3.36+

**Comment by AlexHo1982** [comment]
Maybe you could add this in parenthesis behind the text of the option: Blur background (requires 3.36+)
It is quite confusing, when nothing works after a restart and it took me a while to figure out the root cause, since reinstalling did not work and the options where added back.

Other than that this extension is awesome, thank you very much for all the hard work. :)

**Comment by PapyElGringo** [comment]
The option should be hidden for user with gnome-shell < 3.36
