### ISSUE TITLE
It doesn't totally goes after uninstall

### ISSUE THREAD

**Issue by arhamfar22** [material-shell/material-shell#255]
**After uninstall, the minimize and the maximize buttons are not restored i.e they are absent even after the uninstall and even after reboot the shell or the system**

**I thought that the decorator will become like the gnome-default one but it not.**

**
![Screenshot from 2020-09-01 09-46-33](https://user-images.githubusercontent.com/56512504/91794218-24ec2180-ec38-11ea-8c29-e52001f4184f.png)
**

- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04

**Comment by PapyElGringo** [comment]
Well we do have a system supposed to restore the previous configuration but it's seem in your case that it's "forget" your inital configuration.

You can restore the buttons with 
```gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"```

We need to investigate on why we lost the datas

**Comment by brzegorz** [comment]
In my case, the Super+N shortcuts stopped working after installation and uninstallation didn't help. I had to restore them through dconf-editor.

**Comment by arhamfar22** [comment]
> Well we do have a system supposed to restore the previous configuration but it's seem in your case that it's "forget" your inital configuration.
> 
> You can restore the buttons with
> `gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"`
> 
> We need to investigate on why we lost the datas

Thanks

**Comment by Araly** [comment]
@brzegorz 
Hey, can I ask you how you restored the Super + N shortcuts ?
