### ISSUE TITLE
How to change application launcher page background?

### ISSUE THREAD

**Issue by smolck** [material-shell/material-shell#256]
**Is your feature request related to a problem? Please describe.**
Currently, there doesn't appear (although I may be wrong) to be a way to change the black background when no tabs are open in a workspace; there's just a black background with the application launcher on top of it.

**Describe the solution you'd like**
It would be nice to be able to change that black background to the current desktop background.

**Describe alternatives you've considered**
Don't allow for this.

**Comment by PapyElGringo** [comment]
You can tweak the surface opacity in the settings if it's what you are looking for

**Comment by smolck** [comment]
@PapyElGringo Huh, I guess this is a question not a feature request, because I think this is possible to change, but for me when I have no application open I get this:

![material-shell](https://user-images.githubusercontent.com/46855713/91881190-bb274400-ec46-11ea-8bc8-2c4ae38b57a3.png)

See the black background. I have my desktop background set, but it doesn't show up behind the application menu. How do I make that work? I'm on Arch Linux using the AUR package.

**Comment by PapyElGringo** [comment]
You can access to the settings from gnome extension app or gnome tweaks then there should be an option called `surface opacity`

**Comment by smolck** [comment]
Awesome, that's exactly what I was looking for, thanks!
