### ISSUE TITLE
Ability to unset a keyboard shortcut

### ISSUE THREAD

**Issue by brzegorz** [material-shell/material-shell#260]
**Is your feature request related to a problem? Please describe.**
There is no way to delete a keyboard shortcut. In case of ones conflicting with ones set in Gnome settings, there's no way to unify them. Because of that it's difficult to have one shortcut for one action, and by default the super+n launching ceases to work.

**Describe the solution you'd like**
Ability to set shortcuts to an "unset" state when they have no associated key combination. This way shortcuts like "Go to a workspace" can stay with Gnome settings if one wishes so.

**Comment by FOLLGAD** [comment]
Pressing backspace when choosing a hotkey disables that keyboard hotkey

**Comment by sebastian-xyz** [comment]
The issue seems to be solved
