### ISSUE TITLE
Keyboard shortcut for layout management

### ISSUE THREAD

**Issue by brzegorz** [material-shell/material-shell#261]
**Is your feature request related to a problem? Please describe.**
The only way to manage layouts is to cycle through them in the screen corner, which is inconvenient.

**Describe the solution you'd like**
Configurable keyboard shortcuts to:
- cycle layout
- set layout X

**Comment by vidosuba** [comment]
This feature would really help!

**Comment by PapyElGringo** [comment]
There is a layout menu now
