### ISSUE TITLE
Installation instructions could be simpler: just go to extensions.gnome.org

### ISSUE THREAD

**Issue by rrthomas** [material-shell/material-shell#262]
Rather than have instructions for different distros, just have standard instructions to go to extensions.gnome.org, as this is the simplest thing for most users. You could also mention that distros may package it.

**Comment by PapyElGringo** [comment]
Was already planned but since the update are less frequent I want to be sure that the version on the extension website was good enough before communicate about it. But I think it's time

**Comment by rrthomas** [comment]
Good stuff! It certainly worked for me: easy install like any other extension, and the extension then seemed to work fine.

**Comment by dwrolvink** [comment]
![image](https://user-images.githubusercontent.com/30291690/93800666-3924ac80-fc41-11ea-8b8f-23a16156a7a4.png)

Solved.
