### ISSUE TITLE
Only two layouts available?

### ISSUE THREAD

**Issue by rrthomas** [material-shell/material-shell#264]
**Describe the bug**
When I switch layouts I can only switch between two columns and full screen; `README.md` says there are other options.

**To Reproduce**
- Occurs on:
  - [x] X.Org
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04

**Current commit**
Version 3 from extensions.gnome.org.

**Comment by PapyElGringo** [comment]
It's has changed in the Master but in the v3 of gnome-shell extension website there is only 2 layouts enabled by default. But you can activate the other ones from the settings.

**Comment by rrthomas** [comment]
Thanks! I hadn't looked for settings.
