### ISSUE TITLE
Minimizing windows reclaim space

### ISSUE THREAD

**Issue by kelunik** [material-shell/material-shell#27]
If windows are minimized, their space should be available to other windows, otherwise minimizing is pointless apart from seeing the desktop behind.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
There is no minimizing anymore

**Comment by icheered** [comment]
Sorry for reopening this issue. Why was minimizing removed? I often run into situations where I have to start an application through a terminal and want to minimize the terminal while keeping the application running (I don't want it to start detached) but this seems impossible...

**Comment by PapyElGringo** [comment]
@icheered if you set your layout to maximized you will have only one application visible at the same time. Therefore if you open an application from your terminal your terminal will be replaced by the application without closing it
