### ISSUE TITLE
Chrome window jumps between screens after dialog popup

### ISSUE THREAD

**Issue by xbenjii** [material-shell/material-shell#275]
**Describe the bug**
I have 3 screens, when triggering a chrome dialog popup (save/open file) on the left or right screen the Chrome window jumps to the middle screen

**Expected behavior**
For the window to not jump between screens

**Screenshots**

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Open a Chrome window on a multi-screen desktop
2. Trigger a save popup with ctrl+s
3. Escape the window or save file
4. Bug

**Current commit**
Installed from extensions.gnome.org

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
https://gist.github.com/xbenjii/42e2e169d51f4d88853c55a487210ec4

**Comment by jacob-swanson** [comment]
This is affecting IntelliJ too. I have two monitors. With IntelliJ open on my secondary monitor, whenever a popup opens, IntelliJ jumps over to the primary monitor.

**Comment by PapyElGringo** [comment]
This should be fixed how did you guys installed the extension?

**Comment by xbenjii** [comment]
I installed it through https://extensions.gnome.org/extension/3357/material-shell/ about 4 hours ago

**Comment by amenophis** [comment]
Same issue here, also with Enpass, when Enpass assistant opens, all the app moves to the first screen.
Extension installed this morning

**Comment by PapyElGringo** [comment]
Can someone try with the master branch installed ?

**Comment by amenophis** [comment]
Seems ok with master !

**Comment by jacob-swanson** [comment]
Can confirm that using master instead of installing from extensions.gnome.org fixed the issue for me.

**Comment by QCU87Z** [comment]
anyone know how long this update will take to make it into the package provided by Fedora32?

**Comment by xbenjii** [comment]
Also confirming it's fixed installing from master.
