### ISSUE TITLE
[Feature request] Move top panel to bottom

### ISSUE THREAD

**Issue by Sanqui** [material-shell/material-shell#277]
It would be very nice if we could move the top panel (with workspace windows) to the bottom of the screen.  That way, it looks more like a task bar, and I consider space at the top of the screen to be more important for visibility.

**Comment by sandangel** [comment]
In general, I think it would be nice to be able to customize the position of the sidebar, topbar

**Comment by hyperreal64** [comment]
I also would like this feature

**Comment by k-s-dean** [comment]
Me too !
