### ISSUE TITLE
[Feature request] Pin workspaces

### ISSUE THREAD

**Issue by jopicornell** [material-shell/material-shell#279]
**Is your feature request related to a problem? Please describe.**
I like having shortcuts that I can rely on without having to watch how my workspaces are arranged at that moment. This means that `Super+0..9` should be organized in a certain way every time I start my computer. When I'm working, I'd like to have 1 workspace with my IDEs, another with terminals, another with GIMP...

**Describe the solution you'd like**
Pinning workspaces so they are not deleted when no applications remain on that workspace. This way I can configure up to 10 workspaces that have predefined categories, so I can rely on shortcuts to travel faster and without even thinking in which order I opened them or watching the order they have.

**Describe alternatives you've considered**
I've also considered the possibility to specify rules to that workspaces. This way, every time a browser is opened, it goes to the workspace where I've browsers, when I open another IDE it goes to the workspace I've my IDEs, and so on. This is something that some tilling wm have and I find it extremely useful.

**Comment by PapyElGringo** [comment]
You can already pin applications to workspace and by doing it you basically already pin workspace too.

**Comment by AlexZolotarenko** [comment]
@PapyElGringo, do you refer to the feature of extension to remember which application was running where? With this approach, one should manually keep arrangement between apps and workspaces, each time an application is launched/on logout/OS is switched off and, unfortunately, this approach does not guarantee that, for example, workspace 3 will be where terminal emulators are living, workspace 5 - for IDEs or text editors and so on,  and that workspace 3 or 5 will even exist when you log in to gnome with material shell.

**Comment by PapyElGringo** [comment]
I was referencing to the feature when you right click a task item (tab in the top panel) you can pin a window to a workspace. Then if you close it the app will remain here
