### ISSUE TITLE
Maximize window should toggle layout

### ISSUE THREAD

**Issue by kelunik** [material-shell/material-shell#28]
Maximizing a window currently animates to full screen for a very short period of time, then the window is reset to its original size. Instead, maximizing should have the same effect as having the window focused and toggling the layout to one window mode.

**Comment by maxerbox** [comment]
Such an option would be good indeed

**Comment by PapyElGringo** [comment]
Maximize and minimize action doesn't mean anything on MS If I could i would have remove them ^^
