### ISSUE TITLE
[feature request] clock in zen mode

### ISSUE THREAD

**Issue by sbeckeriv** [material-shell/material-shell#282]
**Is your feature request related to a problem? Please describe.**
I can not tell time when i am in zen mode

**Describe the solution you'd like**
I would like to tell time in zen mode. Can it hover somewhere? Or show when i hit super.

**Describe alternatives you've considered**

https://github.com/beloglazov/bottom-hover-clock  doesnt seem to work any more..

**Comment by sebastian-xyz** [comment]
There's an open issue to add a clock above the search bar (#294). Would this solve the issue for you?

**Comment by sbeckeriv** [comment]
It might. it would provide a place to view it. Can not think of a place on the screen in zen mode it would work without the mouse in a hot spot. closing for #294
