### ISSUE TITLE
Top bar invisibly covers fullscreen apps

### ISSUE THREAD

**Issue by cmulk** [material-shell/material-shell#283]
**Describe the bug**
When using a full screen app such as Remmina remote desktop or Citrix Workspace remote desktop, it is not possible to click on the full screen controls which are in the region of the top bar. Even though the top bar is covered by the full screen app as expected, it seems the material-shell top bar is still taking over the mouse when it is at the top of the screen. This prevents you from being able to close or change remote desktop settings from the floating control bar of Remmina or citrix.

**Expected behavior**
Full screen apps covering the material top bar should own the mouse even when it is in the region of the material top bar.

**To Reproduce**
- Occurs on:
  - [ X] X.Org
  - [ ] Wayland -(unknown)
- GNOME Shell version: 3.38
- Distro: Manjaro testing

 Steps to reproduce, if applicable:
1. Open a full screen app such as Remmina remote desktop
2. Try to access the floating control bar at the top of the remmina screen

**Current commit**
gnome-shell-extension-material-shell-git r277.ge789ded-5

**Comment by goose0058** [comment]
I have encountered this too, it's a serious limitation for my workflows.

**Comment by dwrolvink** [comment]
Reproducible in vscode:

- Press F11 to enter full screen mode
- Area where topbar is is inactive

Interestingly, this doesn't affect Firefox for me.

**Comment by dom3k** [comment]
My temporary workaround: If Material shell is in full screen mode (default esc+super) then every things works.
