### ISSUE TITLE
Respect the font scale in the texts panel

### ISSUE THREAD

**Issue by tinchoz49** [material-shell/material-shell#284]
**Describe the bug**
I'm using a different font scale and the texts in the top panel didn't change, it remains the same size. 

This is more as an accessibility feature than a bug, I guess.

**Expected behavior**
It should respect the font scale of the system.

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36.6
- Distro: Fedora 32

**Comment by benley** [comment]
This is both an accessibility bug and a general interface bug imho.  Many people with displays in the 120-180dpi range set `GDK_DPI_SCALE` to a fraction between 1 and 2 as a "hidpi" stopgap, because setting `GDK_SCALE` to 2 would make most UI elements too big.

**Comment by tinchoz49** [comment]
thank you @PapyElGringo !
