### ISSUE TITLE
ALT key

### ISSUE THREAD

**Issue by caasi-dev** [material-shell/material-shell#285]
I normally prefer to use ALT key instead of SUPER key. Although you can already change it, It would be fantastic to have a switch in shortcuts pane to replace SUPER key to ALT as default meta key.

**Comment by michaelmob** [comment]
An alternative could be to swap `Left Alt` and `Left Super` from the  GNOME Tweak Tools.
This gives the added bonus of minimizing keyboard conflicts from applications that use `Alt` for shortcuts. (Cura, most CAD software, Kakoune, etc., all optionally use `Alt` for a specific piece of functionality)

Here are the settings I use:

![image](https://user-images.githubusercontent.com/4530010/93626093-eaf97a00-f9b0-11ea-86b1-243c02688c22.png)

![image](https://user-images.githubusercontent.com/4530010/93625978-c1405300-f9b0-11ea-9825-8b2392e85484.png)

**Comment by caasi-dev** [comment]
Hey, thanks for a quick response. TBH I did not explore those settings, and they are a perfect solution, so this can be closed.
