### ISSUE TITLE
Picture-in-Picture fonctionnality from firefox is not working with material-shell

### ISSUE THREAD

**Issue by alaenix** [material-shell/material-shell#286]
**Describe the bug**
[Picture-in-Picture fonctionnality](https://support.mozilla.org/en-US/kb/about-picture-picture-firefox) from firefox is not working with material-shell.

When you switch to another application or workspace, the video you're watching is not displayed at the screen. You can't also move around and place the video container like you could normally do it.

**Expected behavior**
Normal usage of the Picture-in-Picture fonctionnality with firefox.

**Comment by hashworks** [comment]
In the extension settings under "Tiling settings" you can set a list of excluded window classes. If you can find out the class of the PIP window you can add it there.

**Comment by michaelmob** [comment]
Some more details...

The class for Firefox's floating preview window is `firefox`. This unfortunately means we can't change it using its class. We would have to either use it's `instance` or it's `title`. Please correct me if I am misinformed.

When trying to drag the PIP window, it will focus and apply the drag motion to the main Firefox window. Always-on-top is the bigger issue IMO.

There is a partial workaround: right-click the titlebar and click `Move` and then you can move the window around with the arrow keys or with the cursor.

**Comment by dwrolvink** [comment]
The fact that the PIP moves away with the workspace is intended behavior I reckon.

The moving around is a proper bug indeed.

**Comment by michaelmob** [comment]
@dwrolvink 
Unfortunately, the "Always on Visible Workspace" window option does not apply to the PIP window.

**Comment by PapyElGringo** [comment]
Should work properly on 5bdb93a9f0c06b162cc005f2317941fdea6dd6e7
