### ISSUE TITLE
Unable to select applications in the workspace panel with touch

### ISSUE THREAD

**Issue by hashworks** [material-shell/material-shell#287]
**Describe the bug**
When I try to switch to a window by clicking on it's tab in the workspace panel with a touchscreen I get the ripple effect, but it won't switch. There is some error message in the logs when I do that.

**Expected behavior**
Clicking a window tab in the workspace panel with a touchscreen should cause it to switch to the window.

**To Reproduce**
- Occurs on:
  - [ ] X.Org (not tested)
  - [X] Wayland
- GNOME Shell version: 3.36.6
- Distro: ArchLinux
- Steps to reproduce, if applicable:
1. Use a touchscreen device (I only tested it on a Surface Go 2)
2. Try to select a window in the workspace panel
3. See the ripple, but the window isn't opened

**Current commit**
688ce24

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
Sep 17 15:49:01 surface gnome-shell[32755]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
Sep 17 15:49:01 surface gnome-shell[32755]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
```

**Comment by hashworks** [comment]
I added a `global.log(eventType);` [here](https://github.com/material-shell/material-shell/blob/50d6fae3fbc14056909e32beeab1651c82ce6a25/src/widget/taskBar.js#L378), which gives me:
```
5
4
13
14
14
14
14
clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
15
Sep 17 16:07:28 surface gnome-shell[36829]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
5
```

Which [translates](https://gitlab.gnome.org/GNOME/clutter/-/blob/master/clutter/clutter-enums.h#L771) to:
* 4 = `CLUTTER_ENTER`
* 5 = `CLUTTER_LEAVE`
* 13 = `CLUTTER_TOUCH_BEGIN`
* 14 = `CLUTTER_TOUCH_UPDATE`
* 15 = `CLUTTER_TOUCH_END`
```

However those seem to be covered by the [`taskBar.js` code](https://github.com/material-shell/material-shell/blob/50d6fae3fbc14056909e32beeab1651c82ce6a25/src/widget/taskBar.js#L387).

**Comment by PapyElGringo** [comment]
Could you isolate the line that cause the exception? If the ripple is working we detect the event but somehow there is an exception.

**Comment by hashworks** [comment]
I think the exception is unrelated, I don't know where that assertion is made – touch stuff isn't even in there.

The problem is in [taskBar.js#L413](https://github.com/material-shell/material-shell/blob/50d6fae3fbc14056909e32beeab1651c82ce6a25/src/widget/taskBar.js#L413) – `event.get_button()` always returns 0, no matter how many fingers I'm using to touch the tabs. I'll add a MR to recognize that as "left click".

**Comment by PapyElGringo** [comment]
What is the difference with the workspace buttons?

**Comment by hashworks** [comment]
There is no `get_button` switch case handling for them. This is [only done in the taskBar](https://github.com/material-shell/material-shell/search?q=get_button&unscoped_q=get_button).
