### ISSUE TITLE
.DEB package

### ISSUE THREAD

**Issue by mhalano** [material-shell/material-shell#289]
Would be nice to have DEB packages available for download and also via official repository.

**Comment by dwrolvink** [comment]
Would installing the extension via extensions.gnome.org be a good solution for now?

**Comment by mhalano** [comment]
Works, but I can't automate that. With a DEB package available in a repository I would be able to add the repository and install the package without manual intervention.

**Comment by PapyElGringo** [comment]
We will only support official gnome extension installation process or Git installation because a lot of packages made by the community is unmaintained and become obsolete
