### ISSUE TITLE
Window focus issue with multi monitors

### ISSUE THREAD

**Issue by pierre-lehnen-rc** [material-shell/material-shell#292]
**Describe the bug**
Whenever I switch windows, a window in a different monitor is focused instead. I need to click on the window area to focus it before I can type on it. It happens both by clicking on the material-shell UI and by using Super+S/Super+D, but doesn't happen with Alt+Tab.

The window that receives the focus is always the last window you used on a different monitor. If you switch between two windows on the same monitor, the focus still goes to a different monitor.

I use three monitors and the monitor that receives the focus is always the one I used more recently other than the one I switched to.

**Expected behavior**
When switching windows, the window that I switched to should receive focus.

**Screenshots**
N/A

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Have multiple windows opened on multiple monitors
2. Switch between open windows
3. Type something
4. What you typed will go to a window on a different monitor than the one you expected.

**Current commit**
Output from `git rev-parse --short HEAD`: `688ce24`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
set 17 19:35:55 orange gnome-shell[2624]: JS WARNING: [/home/pierre/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js 75]: reference to undefined property "categoryList"
set 17 19:35:55 orange gnome-shell[2624]: JS WARNING: [/home/pierre/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js 136]: reference to undefined property "msWorkspaceActor"
set 17 19:35:55 orange gnome-shell[2624]: JS WARNING: [/home/pierre/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js 35]: reference to undefined property "forcedCategory"
set 17 19:35:55 orange gnome-shell[2624]: JS WARNING: [/home/pierre/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js 118]: reference to undefined property "msWindowDragged"```

**Comment by greek** [comment]
I can reproduce. although this doesn't happen with a single monitor.

**Comment by alexandru-calinoiu** [comment]
I have the same issue.

Why is this closed? What it solved?

**Comment by PapyElGringo** [comment]
It was supposed to be resolved with https://github.com/material-shell/material-shell/commit/392b82aa7f6a77e87ce2eb2ce1bdfc1c99b31df4 what is your Material Shell version?
