### ISSUE TITLE
Google Chrome resizing issue in maximized layout

### ISSUE THREAD

**Issue by Degerada** [material-shell/material-shell#293]
**Describe the bug**
First issue: Chrome is always resizable.
Even when you use maximized layout, Chrome will occupy all space as it should, but the edges will always stay resizable.

Second issue: When you do accidently try to resize Chrome, the UI will freeze/be broken, but content is still clickable.
Note, I am using 2 monitors if that has anything to do with it.
The solution is to drag the Chrome bar from one monitor to another, then Chrome will start working fine again.

**Expected behavior**
Chrome should be in proper full screen mode when using maximized layout.

**Screenshots**
Not applicable.

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Manjaro 20.1
- Steps to reproduce, if applicable:
1. Open Chrome
2. Resize Chrome at one of its edges
3. See Chrome's UI break

**Current commit**
Latest version from extensions.gnome.org as of today (v4?)

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
The resizing issue does not leave any log message behind.
The drag/dropping of chrome between 2 monitor panels also doesn't log anything to fix the issue.
```

**Comment by mithrandi** [comment]
Maximizing the Chrome window fixes the issue temporarily, but each time you switch to another window Chrome will be restored (unmaximized) when you switch back.

**Comment by dwrolvink** [comment]
I have a single monitor, same issue pops up. Fixed by moving the app to another workspace.

**Comment by dwrolvink** [comment]
For general issues with screens freezing, see this new issue: https://github.com/material-shell/material-shell/issues/316

For the fact that Chrome stays resizable even in maximized mode, we can continue here.
