### ISSUE TITLE
Return to the last focused window after current window closes

### ISSUE THREAD

**Issue by xbenjii** [material-shell/material-shell#295]
**Is your feature request related to a problem? Please describe.**
When an application opens a new window (in this instance Thunderbird) and the new window closes, it focuses to the last window in the taskbar
![](https://cdn.discordapp.com/attachments/595852612990140436/756440657996021810/unknown.png)
After application opens a new window:
![](https://cdn.discordapp.com/attachments/595852612990140436/756440722101501992/unknown.png)
After closing the new window:
![](https://cdn.discordapp.com/attachments/595852612990140436/756440802846310410/unknown.png)

**Describe the solution you'd like**
* To focus back to the last window you had open (Thunderbird)
* Open the new window next to the application that opened it in the taskbar

**Describe alternatives you've considered**

**Comment by PapyElGringo** [comment]
We have updated this behavior. If a window is opened while a window is focused it's will be inserted next to it. If you kill the window just inserted it's will go back to the previous window instead of the next one. It's should fix this
