### ISSUE TITLE
File dialogs on external monitor move parent application automatically to main monitor when closed

### ISSUE THREAD

**Issue by jrohland** [material-shell/material-shell#296]
**Describe the bug**
When I'm using an application on an external monitor that utilizes a file dialog, the application is automatically moved to the main monitor when the file dialog is closed. This happens when a file is selected as well as when the dialog is canceled out. I've experienced this behavior in multiple applications such as SublimeText, VSCode, and Firefox.

**Expected behavior**
After a file dialog is closed, either by selecting a file or canceling, the main application should remain on the external monitor.

**Screenshots**
I've recorded a screencast of this happening with various applications: https://streamable.com/gu6dm8

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.3
- Distro: Pop!_OS 20.04
- Steps to reproduce, if applicable:
1. Move application to external monitor
2. Attempt to open a file either via menu or ctrl-o
3. Close the open file dialog by selecting a file or clicking cancel
4. The application window shifts to the main monitor automatically

**Current commit**
Using the current version available on the gnome extension site

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
Sep 18 11:09:08 stealth gnome-shell[2725]: Could not create transient scope for PID 298752: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 298752 does not exist.
Sep 18 11:09:11 stealth gnome-shell[2725]: Trying to activate unmanaged window '0x3601637'
Sep 18 11:09:11 stealth gnome-shell[2725]: clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
Sep 18 11:09:11 stealth gnome-shell[2725]: clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
Sep 18 11:09:11 stealth gnome-shell[2725]: clutter_actor_remove_child: assertion 'child->priv->parent == self' failed
Sep 18 11:09:11 stealth gnome-shell[2725]: Could not create transient scope for PID 299126: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 299126 does not exist.
```
I'm not sure if that log applies but I ran `journalctl -f /usr/bin/gnome-shell` while I reproduced the issue and that was all that was logged.

**Comment by PapyElGringo** [comment]
check #275

**Comment by jrohland** [comment]
Confirmed fixed when running latest version from master.
