### ISSUE TITLE
Fonts are blurry and clipped on the application selection grid

### ISSUE THREAD

**Issue by jsbmg** [material-shell/material-shell#297]
**Describe the bug**
When opening a new program from the application selection grid, the fonts appear blurry like a few pixels are shaved off of the bottom of the letters. I believe this is affecting the icons as well. Elsewhere in gnome and the extension, the fonts are perfectly crisp.

**Expected behavior**
Clear font rendering like in the rest of gnome and material shell.

**Screenshots**
![blurry-fonts](https://user-images.githubusercontent.com/63313743/93619203-c2c94580-f9c7-11ea-8c77-df6d74f642ae.png)

**To Reproduce**
- Occurs on:
  - [x] Wayland
- GNOME Shell version: 3.36
- Distro: Fedora 32
- Steps to reproduce, if applicable:
1. Install Fedora 
2. Install material shell from git using the instructions
3. ???
4. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `688ce24`

**Comment by sebastian-xyz** [comment]
Can you provide some more information about your system like your screen resolution?

I was only able to reproduce this in a VM when I wasn't in full screen mode. Otherwise the font looked crisp.

**Comment by dwrolvink** [comment]
@jsbmg  did you install ttf-roboto?

**Comment by jsbmg** [comment]
After a reinstall of Fedora this issue resolved itself.

**Comment by bignimbus** [comment]
Is it possible to re-open this?  I have seen the same thing with Roboto on my machine. Ubuntu 20.04 stock

**Comment by PapyElGringo** [comment]
I have no idea what cause this :(

**Comment by matguidi** [comment]
I have a probably related problem, occurring both with X and Wayland. Rendering is somehow broken.

![immagine](https://user-images.githubusercontent.com/59918868/97988463-51115380-1ddd-11eb-85f5-26aa526d0002.png)

**Comment by matguidi** [comment]
Is there any way to debug this?

**Comment by matguidi** [comment]
I can add that it doesn't depend on Roboto particularly. I have changed the font used in the theme's *.css file, and the behaviour is the same.
