### ISSUE TITLE
[Feature Request] be able to switch active window via hover

### ISSUE THREAD

**Issue by codic12** [material-shell/material-shell#300]
I'm used to this behavior from i3 and qtile, and a way to toggle it would be great; currently we have to click on the other window.

**Comment by boardfish** [comment]
This can be achieved using `gnome-tweak-tool` and probably shouldn't be a feature of Material Shell in its own right. See [this StackOverflow answer.](https://superuser.com/a/1249399/573335)

**Comment by codic12** [comment]
i see, thanks
