### ISSUE TITLE
[Feature Request] Stock Gnome search for new window

### ISSUE THREAD

**Issue by nchlsryncrg** [material-shell/material-shell#301]
When using search for new application I often have to just use the super key and use stock Gnome search.
Rather than the search that is unique to Material Shell, just use the stock Gnome search.
I love Material Shell and find little things like this counter to the productivity I've gained.

**Comment by Chrysostomus** [comment]
Both search options have their advantages. Material-shell search gives better spatial awareness and is more mouse/touch friendly if your desired app is one of the suggested ones. But gnome shell search is much more powerful. Could their advantages be combined? Like, have the current app suggestion view, but if search field is click, switch to the full screen gnome shell search? Or something like that.

**Comment by PapyElGringo** [comment]
We have our own search now
