### ISSUE TITLE
[Feature request] Move taskbar applications

### ISSUE THREAD

**Issue by Wael2727** [material-shell/material-shell#303]
The only reason i've switched to material shell is for the design, automatic tiling, it was so nice but something bothered me too much.

the clock in the bottom corner for example should be able to be moved or, alternatively

the taskbar itself since i don't like it being on the left imo;
or anything inside the taskbar should be customizable!

**Comment by dwrolvink** [comment]
There is an open issue to move the clock to/above the search button. Would this be sufficient for your use case?

Regarding moving the entire taskbar to a different location, there is an open issue for putting it on the right: https://github.com/material-shell/material-shell/issues/245

I think a general feature of being able to control the location of the application/system bar would be in order.

**Comment by Wael2727** [comment]
yes i would gladly appreciate it!

**Comment by dwrolvink** [comment]
Alright, since there are issues for those use cases already, I'll close this one.
