### ISSUE TITLE
Improve straight/rounded corner consistency

### ISSUE THREAD

**Issue by eldelacajita** [material-shell/material-shell#305]
**Is your feature request related to a problem? Please describe.**
Tiled windows sometimes show straight corners while others (typically the ones using CSD) keep their rounded corners. This looks messy and inconsistent. Even default gnome shell applies straight corners to side-by-side tiled windows. 

![top-corners](https://user-images.githubusercontent.com/2880679/93670674-73eddf80-fa9d-11ea-89e9-fc73db08df1b.png)

**Describe the solution you'd like**
A common styling could be applied to all window corners. My preferred solution would be: using straight corners for all the windows when "gap size" is set to 0, and rounded corners for all the windows (ideally, also applying to bottom corners) when "gap size" is set to > 0.

**Describe alternatives you've considered**
Using straight corners for all the windows in all layouts, if that's simpler. 

Now, I don't know how difficult this is to implement, so I'll take your word for it. Can Material Shell force of override the corners of the windows in some way?

**Comment by PapyElGringo** [comment]
There is no way for us to enforce corner radius as it's client side decoration.
Sorry for the answer delay...
