### ISSUE TITLE
Dark theme font contrast in textboxes not working

### ISSUE THREAD

**Issue by truckerboy** [material-shell/material-shell#306]
In the dark theme on Ubuntu 20.04, the font contrast is not working in text boxes as can be seen in the screenshot (dark font on a dark background). The font contrast in light theme works fine. Any ideas on how to fix for dark theme?
The material-shell theme is installed from gnome extensions website.
![Screenshot from 2020-09-19 22-29-37](https://user-images.githubusercontent.com/23089829/93693196-7d417100-faca-11ea-9898-36758a562ee2.png)

**Comment by greek** [comment]
thanks for reporting this, i can reproduce with the default Ubuntu 20.04 theme.
next time please be sure to use the format so we can follow the proper steps to reproduce :)

**Comment by PapyElGringo** [comment]
What is this window?

**Comment by greek** [comment]
I have an idea of what's going on. Based on the theme selected, Material Shell would override the current colors selected. Elements like the input dialog will change colors based on the user's theme. To reproduce this, set your Material Shell theme to primary and change the primary color. The same thing happens with the Light theme, where the white color will be used in the search box. 

> What is this window?

@PapyElGringo, this is the clipboard extension window. The bug specifically is reproducible almost everywhere in the shell, like in GNOME search.
![image](https://user-images.githubusercontent.com/17275723/93934292-f0c4c780-fcf0-11ea-9485-51428238ccd9.png)
![image](https://user-images.githubusercontent.com/17275723/93934623-6c267900-fcf1-11ea-9da7-b2c2c8a4530b.png)
