### ISSUE TITLE
Super+Space is common keyboard layout switch combination

### ISSUE THREAD

**Issue by r7sa** [material-shell/material-shell#309]
**Describe the bug**
The Super+Space combination is interfered with keyboard switch layout.

**Expected behaviour**
The combination need to be changed for comfortable use this extension in case of multiple keyboard layouts.

**Comment by dwrolvink** [comment]
Duplicate of https://github.com/material-shell/material-shell/issues/274

**Comment by dwrolvink** [comment]
I've added your suggestion there as an action point. You can continue the discussion over there. @r7sa
