### ISSUE TITLE
Option to change the switcher tab's title

### ISSUE THREAD

**Issue by kellya** [material-shell/material-shell#313]
The switcher tabs currently change to whatever the application windows' title is displaying.  I think it reduces predictability if the tabs constantly change to match the window's title.  The window is already telling me what the title is, and in my opinion it is extraneous detail that jumbles up the display.

![switcher](https://user-images.githubusercontent.com/168120/93809271-17183380-fc1b-11ea-9dd5-17bb6060c8a2.png)

In that screenshot, Brave and Firefox both are setting the title, which shows up in the switcher tabs.  I would like the option to have it only display "Brave" and "FireFox" instead of the window title.

**Describe the solution you'd like**
I would like an option to choose the switcher tab content between:

1. The app's window title (current behavior)
2. App Name only
3. None (would only display the app icon)

**Comment by aaronjanse** [comment]
It would be super cool if there were also an option to just show the app title but not the icon :-)

**Comment by lfom** [comment]
Latest version has an option in settings to display:
- Full (app title + icon)
- App name only
- App icon only

So maybe this issue can be closed?

**Comment by aaronjanse** [comment]
The latest git clone seems to include the icon, but I like it now. Yes, I think this issue can be closed

**Comment by kellya** [comment]
I didn't see this issue referenced in the log, but this functionality is in the current git version and works exactly as I had imagined.  Thank you!
