### ISSUE TITLE
Appimage applications not persisting

### ISSUE THREAD

**Issue by Nishan-Vivek** [material-shell/material-shell#314]
**Describe the bug**
Appimage applications not persisting.

**Expected behavior**
I have two AppImage apps and noticed that neither persist either when the system is restarted or when pinned. 

- Occurs on:
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04

**Current version**
latest from extensions.gnome.org

**Comment by PapyElGringo** [comment]
That is because the application desktop lack a `StartupWMClass` entry matching the application class. Therefore Gnome is unable to detect from which app is has started.

For exemple by default the `appimagekit-hyper.desktop` look like 
```
[Desktop Entry]
Name=Hyper
Comment=A terminal built on web technologies
Exec="/home/papyelgringo/Downloads/hyper-2.1.2-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-hyper
X-AppImage-Version=2.1.2.3322
X-AppImage-BuildId=48ccfad0-2901-11a9-009e-51f93bb07a19
Categories=TerminalEmulator;
X-Desktop-File-Install-Version=0.24
X-AppImage-Comment=Generated by /tmp/.mount_hyper-W5BRbW/AppRun
TryExec=/home/papyelgringo/Downloads/hyper-2.1.2-x86_64.AppImage
```
and is not recognised by gnome and therefore we are unable to create persistence for it.
But if you change to
```
[Desktop Entry]
Name=Hyper
Comment=A terminal built on web technologies
Exec="/home/papyelgringo/Downloads/hyper-2.1.2-x86_64.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-hyper
X-AppImage-Version=2.1.2.3322
X-AppImage-BuildId=48ccfad0-2901-11a9-009e-51f93bb07a19
Categories=TerminalEmulator;
X-Desktop-File-Install-Version=0.24
X-AppImage-Comment=Generated by /tmp/.mount_hyper-W5BRbW/AppRun
TryExec=/home/papyelgringo/Downloads/hyper-2.1.2-x86_64.AppImage
StartupWMClass=Hyper
```
It's will work

**Comment by Nishan-Vivek** [comment]
Thanks got it working. 

I used appimagelauncher to integrate the appimages to my desktop and the .desktop file it created already included the `StartupWMClass` line. However it did not match the applications WM_CLASS as seen with `xprop`. After changing the .desktop to match the WM_CLASS string exactly persistence started working.
