### ISSUE TITLE
JetBrain application screen-moves on a dual screen setup

### ISSUE THREAD

**Issue by frague59** [material-shell/material-shell#315]
**Describe the bug**
PyCharm windows move from plain fullscreen on screen 1 to tiled on screen 2 when an action opens PyCharm a popup on a dual screen setup. Sometimes the popup is not visible. 

**Expected behavior**
I expect that the popup are always displayed and the window does not change of screen.

**To Reproduce**
- Occurs on:
  - [x ] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Debian testing
- Steps to reproduce, if applicable:
1. Start PyCharm (JetBrain application) with two projects (A and B) opened in distinct screens (A→1 and →2)
2. Copy a file in project A, paste it in project B. 
3. The A application *lonely* moves to screen 2
3. Pycharm should open a "Add file to repository" dialog - **The dialog does not appears**

**Current commit**
Version from http://www.gnome-extensions.org

**Comment by PapyElGringo** [comment]
Should be fixed

**Comment by frague59** [comment]
Hi, 
Pushed in http://www.gnome-extensions.org ?

**Comment by PapyElGringo** [comment]
in extensions.gnome.org normally yes.
It's not working?

**Comment by frague59** [comment]
... not tested yet, 'll do it tomorrow morning :)  Good night !

**Comment by frague59** [comment]
Hi, 

I've still weird behavior on Pycharm (JetBrain). Note I have 2 screens.

When I have 1 project opened and the application opens a popup, most of time, the main window (on my main screen) moves to the secondary screen, and the popup with it. 

When I've more than one 1 opened (projects P1 and P2), by example one on each screen (S1 and S2), when I perform an action on the P1 project which requires a popup (from P1 on S1), the P1 main application window moves to the S2, and most of the time, it attaches itself on the P2.

I cannot "directly" perform the action on the opened popup, because it comes from P1 and P2 window has focus. I've to re-move the P1 window to the S1, then I can perform action on P1 popup, which if still over the P2 window on S2.

I do hope my explanation is clear... 

Thanks for your great extension !
