### ISSUE TITLE
PhpStorm closes itself

### ISSUE THREAD

**Issue by vatavazz** [material-shell/material-shell#317]
**Describe the bug**
When opening a new instance of PhpStorm (snap installation, v 2020.2), the splash logo pops up briefly. If PhpStorm is set to open the last-opened project, nothing happens past this point. If PhpStorm is set to open a project select window, a confirmation window to exit the application appears. The window confirms itself and the application closes. When managing to quickly click "cancel" on the window, PhpStorm stays open. Issue does not occur with material shell disabled.

**Expected behavior**
PhpStorm opens normally with MaterialShell enabled, whether opening the project select window or last-opened project.

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Open PhpStorm

**Current commit**
Output from `git rev-parse --short HEAD`: `688ce24`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
sep 22 18:10:24 free-coffee gnome-shell[3154]: Window manager warning: Window 0x5c00007 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
sep 22 18:10:24 free-coffee gnome-shell[3154]: Window manager warning: Window 0x5c00007 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
sep 22 18:10:28 free-coffee gnome-shell[3154]: Window manager warning: Tried to ping a window with a bad serial! Not allowed.

```

**Comment by velovix** [comment]
I used to see this behavior with PyCharm but I haven't seen it lately. I would recommend pulling the latest commit on master and see if you still have the bug.

**Comment by PapyElGringo** [comment]
Same as #330 can you check the last master commit? should fix that

**Comment by vatavazz** [comment]
@PapyElGringo, I can get PhpStorm to open reliably now, thanks!

**Comment by greek** [comment]
closing issue per [comment above.](https://github.com/material-shell/material-shell/issues/317#issuecomment-698855612)
