### ISSUE TITLE
Add keyboad shortcut to Maximize Tile/Full-screen

### ISSUE THREAD

**Issue by adriano-moreira** [material-shell/material-shell#318]
Some apps have a different shortcut to full-screen, others don't have

I knew gnome have this config, on Ubuntu the default is disabled, I configure to F11

I guess useful  have a global full-screen shortcut on extension

**Comment by greek** [comment]
>I guess useful have a global full-screen shortcut on extension

the `Super+Esc` shortcut hides the shell's layout, only leaving applications to be visible on the screen. maybe this is what you might be looking for?
