### ISSUE TITLE
Error during the upgrade

### ISSUE THREAD

**Issue by Surfoo** [material-shell/material-shell#320]
**Describe the bug**
A new update of Material Shell appeared this morning, I clicked on the green button to update it and the Error button appeared.

**Log data**
```
JS ERROR: Extension material-shell@papyelgringo: Error: A different version was loaded previously. You need to log out for changes to take effect.
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:340:52
                                            callback@resource:///org/gnome/shell/ui/extensionDownloader.js:222:39
                                            gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

**Expected behavior**
The upgrade should works without a user log out.

**Screenshots**
![material](https://user-images.githubusercontent.com/553659/93978419-472b1800-fd7c-11ea-9ab4-c97278b03c7d.png)

**To Reproduce**
Manjaro with Gnome-shell 3.38

**Comment by PapyElGringo** [comment]
Is that because you previously installed it in a different way? (Like not from the gnome website)

**Comment by undu** [comment]
I hit the same error, I previously installed it using the gnome website. Logging out and in again fixed it though. I'm using Fedora 32

**Comment by Surfoo** [comment]
Same as @undu, installed from gnome website. Logout then login to upgrade the extension is not user friendly (and I know it only by reading logs, which isn't user friendly too)

**Comment by iho** [comment]
Same but on Ubuntu 20.04. New version of the package is broken
