### ISSUE TITLE
Material Shell won't start after update

### ISSUE THREAD

**Issue by GrosTon1** [material-shell/material-shell#321]
**Describe the bug**
Material Shell won't start after updating

**Expected behavior**
Material Shell should start.

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.34.3
- Distro: Ubuntu 19.10
- Steps to reproduce, if applicable:
1. Updated Material Shell
2. Relogged
3. Material Shell won't start

**Current commit**
Output from `git rev-parse --short HEAD`: `9d72be9`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
https://nextcloud.clauzier.dev/s/GiMgZHp7tWx4q3K

**Comment by PapyElGringo** [comment]
Could you try the last commit on Master?

**Comment by GrosTon1** [comment]
https://nextcloud.clauzier.dev/s/eZD9qqS2J7ywHxn

**Comment by bedlamss** [comment]
Affected me, but after reboot work well

**Comment by PapyElGringo** [comment]
@GrosTon1 Is that on the last commit ? I doubt

**Comment by GrosTon1** [comment]
I haven't rebooted which may explain that. Will let you know asap

**Comment by PapyElGringo** [comment]
Can I have the logs now?

**Comment by GrosTon1** [comment]
Sorry, here : https://nextcloud.clauzier.dev/s/HKCxYcmimJkF8Ft

**Comment by PapyElGringo** [comment]
Ok so now you have to disable blur background since it's not compatible with 3.34 https://github.com/material-shell/material-shell/issues/247

**Comment by GrosTon1** [comment]
Now works like a charm indeed, thank you !

I can then confirm blur background option isn't hidden for Gnome 3.34 ^^

**Comment by HaisojYellams** [comment]
I'm having a similar issue on Fedora 31 (Gnome 3.34.8). I can confirm I've disabled blur background, but the Gnome Extensions page shows an error. The logs show the error below. Disabling the notifications does not help.
```
JS ERROR: Extension material-shell@papyelgringo: TypeError: GObject.registerClass() used with invalid base class (is Source)
@/home/jsmalley/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msNotificationManager.js:72:30
@/home/jsmalley/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:20:7
```

If this needs to be its own ticket, let me know and I'll create one - didn't want to unnecessarily duplicate an issue.

**Comment by PapyElGringo** [comment]
@HaisojYellams Yeah sorry I delivered a no-retro compatible code... 
Since there is delay before I can delivre new version your best luck would be to install the master branch using GIT to solve that...
My bad

**Comment by HaisojYellams** [comment]
Ok. I'll try that - is there a specific commit I should point to that should be stable? I was going to try to point to the last release (`688ce24`) unless you have a better option. :smile:

**Comment by PapyElGringo** [comment]
You should target master. It's have the last bug fixes. I usually try to not push bugs but if I do I tend to fix them asap when reported
