### ISSUE TITLE
Being able to change the hotkeys

### ISSUE THREAD

**Issue by vlefevre86** [material-shell/material-shell#326]
**Is your feature request related to a problem? Please describe.**
I'm using a French keyboard, so the meta+WASD is not really natural... Being able to change it to meta+ZQSD would be nice.

**Describe the solution you'd like**
Being able to change the hotkeys :smiley: 

**Describe alternatives you've considered**
None that I can think of...

**Comment by PapyElGringo** [comment]
Salut!
It's already doable in the settings so I supposed you didn't find them. So my questions will be related to that, are you new gnome user? new Linux users? Or just new extensions users?
I've planned to make settings more integrated but for now you have to go through the  extension settings page available through the gnome tweak app or the gnome extension app

**Comment by vlefevre86** [comment]
New extension user 😊 And I couldn't find any setting... Looking at gnome tweak apps, I've just found it, thanks. 
Never occurred to me it could be here... 
Issue closed then !
