### ISSUE TITLE
System tray is partially missing after system lock/unlock

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#329]
**Describe the bug**
System information (battery, connection, brightness etc) are missing after system unlock.
Also this icons have click action to open sys menu like reboot or log off, change wi-fi connection etc. As an example, the only (UI) way to reboot is to short press hardware button and then choose reboot action. Also there is no way to switch user. 

**Expected behavior**
Every sys tray parts should be shown after unlock.

**Screenshots**
As it should be and as it is before locking:
![As it should be](https://user-images.githubusercontent.com/8870929/94130234-11159300-fe65-11ea-967a-ec302755330c.png)
As it is after unlocking:
![As it is after unlocking:](https://user-images.githubusercontent.com/8870929/94130342-31455200-fe65-11ea-87b8-2edcd7fd167e.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org (Nvidia control)
  - [?] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04
- Steps to reproduce:
1. Load system
2. Check sys tray for icons
3. Press Win+L to lock
4. Lig in again
4. Check sys tray for icons (some are missing now)

**Current commit**
I installed extension from gnome shell extensions site. The version is 5.

**Log data**
I cut logs for last boot approximately.
Output from `journalctl /usr/bin/gnome-shell -S "2020-09-24 12:00:00"` in file.
[material-shell.log](https://github.com/material-shell/material-shell/files/5275177/material-shell.log)

**Comment by GoshaEgorian** [comment]
I checked out it's OpenWeather extension incompatibility. If it's turned on together icons will disappear on locking and will not appear after unlocking.

**Comment by GoshaEgorian** [comment]
Updated steps to reproduce:
1. Install both OpenWeather and Material-shell extensions
2. Turn them on
3. Check sys tray for icons
4. Press Win+L to lock
5. Log in again
6. Check sys tray for icons (some are missing now)

After step 2 you can turn off and on OpenWeather as many times as you want - bug will appear anyway until reboot (or mb logout / xorg/wayland/gnome restart - I didn't check this).

**Comment by PapyElGringo** [comment]
It's normally already fixed on master

**Comment by GoshaEgorian** [comment]
I checked this is solved in master already. Thank you!
