### ISSUE TITLE
IntelliJ Idea cannot be opened if no project is selected

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#330]
**Describe the bug**
If you have fresh install on idea or close every project (file -> close project) then project selecting window should be prompted. But instead Idea closes (maybe it's crash but silent).

It stop Idea from working at all because you cannot even open it. The only way to use it is to turn off this extension, open Idea, choose any project and then turn on extension back. And never close every project again, just keep at least one opened.  

**Expected behavior**
Project selecting window should be shown.

**To Reproduce**
- Occurs on:
  - [x] X.Org (Nvidia control)
  - [?] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04
1. Fresh install Idea
or
1. Open Idea
2. Close every project in it (File -> Close Project) 
3. Bug here (Idea closes instead of window prompt)
4. Open Idea back
5. Bug again (it closes)

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Current commit**
I installed extension from gnome shell extensions site. The version is 5.

**Log data**
I cut logs for last boot approximately.
Output from `journalctl /usr/bin/gnome-shell -S "2020-09-24 12:00:00"` in file.
[material-shell.log](https://github.com/material-shell/material-shell/files/5275177/material-shell.log)

**Comment by HaisojYellams** [comment]
I'll add my two cents here: I've noticed this same issue with JetBrains' Rider as well. If you try to launch the software without a specific program selected, it will (very briefly) show the "are you sure you want to close <program name>" dialog and quickly quit the program. I've managed to hit "cancel" on that dialog a few times, but not often. Using the App Toolbox, I can get things going by selecting an existing project to launch instead of launching the app by itself.

I have _not_ seen this issue with DataGrip, PhpStorm, WebStorm, PyCharm (Professional), or RubyMine though.

**Comment by PapyElGringo** [comment]
Can you guys try the last commit ? I think I found a way to improve the splashscreen detection and prevent this bug

**Comment by HaisojYellams** [comment]
The above issue doesn't occur using IntellJ IDEA Ultimate 2020.1.4.
It still occurs on Rider 2020.2.3. (The dialog message that pops up before closing actually says something along the lines of "you have background tasks running. are you sure you want to close Rider?")

**Comment by PapyElGringo** [comment]
@HaisojYellams You tryed with the lastest change on Master?

**Comment by GoshaEgorian** [comment]
@PapyElGringo It works now if you close already opened project. But it doesn't work if Idea starts when no project is selected (silent closing).

**Comment by HaisojYellams** [comment]
> @HaisojYellams You tryed with the lastest change on Master?

Yes. I tested on `a618405` (the commit from 36 minutes ago).

**Comment by GoshaEgorian** [comment]
I cannot repeat it on `ec73be7` - everything works well. I consider it was fixed. Could we close this?

**Comment by metaa** [comment]
I just installed material shell yesterday and I also experience the same with issue with Jetbrains products closing automatically as well as the Steam login window closing right after opening.

I'm on Debian `bullseye/sid` (alpha 2) running `gnome-shell` in version `3.38.0` and `gnome-extensions list -d` shows version 7.

**Comment by karottenreibe** [comment]
I just tried with the current master (d7478d7e09f6618d075549568f07a7ba11c649c5) and IntelliJ and Android Studio both work for me

**Comment by metaa** [comment]
> I just tried with the current master (d7478d7e09f6618d075549568f07a7ba11c649c5) and IntelliJ and Android Studio both work for me

I'll update my install to master then and give y'all feedback.

**Comment by metaa** [comment]
Oh hey, I forgot to report back.
I can confirm too that it works on commit d7478d7.
