### ISSUE TITLE
Zoom will not persist

### ISSUE THREAD

**Issue by HaisojYellams** [material-shell/material-shell#332]
**Describe the bug**
The Zoom application refuses to persist - I always have to re-launch the application when restarting my computer. I understand this may be an issue with Zoom and _not_ Material Shell, but thought you may like to know about it.

**Expected behavior**
A Zoom placeholder window should save the place of the application after restarting the computer.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.34.8
- Distro: Fedora 31

**Current commit**
`701b6ad` (But Zoom has not persisted since the persistence feature was released)

**Comment by Chrysostomus** [comment]
Could zoom be one of the apps that rewrites it's window name after launch like libreoffice and steam?

**Comment by lfom** [comment]
Some Flatpack apps also behave this way (change its WM class after each launch).

**Comment by HaisojYellams** [comment]
I believe this issue may be solved with the newest version of Zoom I installed this week: 5.4.3 (54779.1115).
