### ISSUE TITLE
Unable to login to Steam

### ISSUE THREAD

**Issue by chabad360** [material-shell/material-shell#337]
**Describe the bug**
Attempting to login to Steam results in the login window opening for just a sec, and then it exits.

**Expected behavior**
Steam should show the login page, and allow me to login.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Install Steam
2. Launch Steam
3. Press `Login`
4. Boom! It's gone!

**Current commit**
Output from `git rev-parse --short HEAD`: `688ce24`

**Comment by PapyElGringo** [comment]
Could you pull last changes and try again?

**Comment by chabad360** [comment]
Seems to be working now, however, steam refuses to stay in the background, after closing the windows, it just quits.

**Comment by chabad360** [comment]
Also, it should be noted that all windows even little dialog boxes are now full size. I think that would be considered a regression?

**Comment by PapyElGringo** [comment]
Possibly yes

**Comment by PapyElGringo** [comment]
Should be fixed on ddc48257b4103e3ec7516efe80362fe4b329e56e
