### ISSUE TITLE
Firefox picture-in-picture video: always on visible workspace doesn't work properly

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#341]
**Describe the bug**
If you want to keep video on screen you can enable picture-in-picture mode with always on visible workspace option. Normally, if you switch between workspaces video will be shown up on target workspace and you can always see it.
But with material shell enabled picture-in-picture will be displayed on Firefox's workspace only and will not be shown on any other.

**Expected behavior**
Picture-in-picture with always on visible workspace enabled should be always visible.

**Screenshots**
Always on visible workspace is on:
![Screenshot from 2020-09-26 15-23-07](https://user-images.githubusercontent.com/8870929/94340797-2a594380-000d-11eb-9b8b-48dc16b2b1b5.png)

But it's not shown on another workspace:
![Screenshot from 2020-09-26 15-23-50](https://user-images.githubusercontent.com/8870929/94340712-7bb50300-000c-11eb-9d7f-e9a1355f1c26.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Open [any video](https://youtu.be/dQw4w9WgXcQ) in Firefox
2. Click on picture-in-picture button (blue icon on the right side of a video when you hover it)
3. Right click on picture-in-picture frame -> Always on visible workspace
4. Move to any workspace
5. Bug: the frame is not shown

**Current commit**
`5e75527`

**Comment by dmaahs2017** [comment]
Yeah it'd be nice to be able to do this with any window, such that when you select "Always on visible in workspace" the window is freely movable, manually resizeable, and always on top. My specific use-case would be for the discord pop-out player during video calls.

**Comment by NicholasMamo** [comment]
Same for Chrome... Picture in picture is considered to be a different window instead of drawing on top of all windows

**Comment by PapyElGringo** [comment]
Should be fixed in 5bdb93a9f0c06b162cc005f2317941fdea6dd6e7 and always on visible workspace is now selected by default

**Comment by GoshaEgorian** [comment]
@PapyElGringo It's working well. Thank you!
