### ISSUE TITLE
Firefox picture-in-picture video prevents Win+D to work properly

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#342]
**Describe the bug**
Consider Firefox is opened as last application in current tab. If you press Win+D to move right then menu will be shown (search string and applications list).
But if picture-in-picture is enabled Win+D will lead to this menu then immediately switch you back. But screen will be empty as no application opened in current tab.

**Expected behavior**
Apps search menu should be shown.

**Screenshots**
Picture-in-picture is enabled:
![Screenshot from 2020-09-26 15-38-30](https://user-images.githubusercontent.com/8870929/94340933-6b9e2300-000e-11eb-9e24-e30478daeafe.png)

State after Win-D:
![Screenshot from 2020-09-26 15-38-34](https://user-images.githubusercontent.com/8870929/94340948-7b1d6c00-000e-11eb-970f-feed33cc4c64.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce:
1. Open Firefox and move it to the last position of current tab
2. Open [any video](https://youtu.be/dQw4w9WgXcQ)
3. Enable picture-in-picture mode by clicking on blue icon on a right side of video when you hover it
4. Press Win+D
5. Look at an animation and empty screen

**Current commit**
`5e75527`

**Comment by PapyElGringo** [comment]
Should be fixed in 5bdb93a9f0c06b162cc005f2317941fdea6dd6e7
