### ISSUE TITLE
When restarting computer, Firefox and Thunderbird are reloaded using their default user profile

### ISSUE THREAD

**Issue by pieqq** [material-shell/material-shell#356]
Hello! I've been using Material Shell for a few days on my desktop and so far, loving it! I found the following issue, though.

# Describe the bug
Firefox and Thunderbird can be started with a different user profile. This profile is not remembered by Material Shell, so after reboot, the default profile is loaded instead of the one originally chosen.

# To Reproduce
- Occurs on:
  - [X] X.Org
  - [X] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:

1. Make sure you have at least two profiles with Firefox or Thunderbird. With Firefox for instance, go to `about:profiles` and make a note of the existing profiles (or create one if you don't have enough). For our example, let's assume we have two profiles: `profile1` and `profile2`.
2. Start Firefox with `profile1` by pressing `Alt+F2`, then entering `firefox -p profile1`, and place the window on the first workspace. Visit a given website to make sure you can differentiate the two profiles later on.
3. Move to a second workspace, and start Firefox with `profile2`: `Alt+F2`, then entering `firefox -p profile2`. Visit another website.
4. Restart your computer.
5. Click to re-launch Firefox.

# Expected behavior

- On the first workspace, Firefox with `profile1` should load (so you should see the website you visited in step 2)
- On the second workspace, Firefox with `profile2` should load (so you should see the website you visited in step 3)

# Actual behavior

- In both workspaces, Firefox is loaded with the default profile, whatever it is.

**Comment by lfom** [comment]
As of now, there is no way this can be fixed without a custom implementation of the launch process for each app that could load profiles. But create a different .desktop file for each profile, and I _think_ this would work (I haven't tested it so far) with no changes required to the current code.

**Comment by pieqq** [comment]
Thanks for the workaround. I understand it's not possible to handle right now, so I'll close this issue.
