### ISSUE TITLE
Resize windows in tiling mode

### ISSUE THREAD

**Issue by philibertc** [material-shell/material-shell#362]
**Is your feature request related to a problem? Please describe.**
It is impossible to resize the windows when they are tiled. We cannot choose one window to be larger than another when two are placed side by side.

**Describe the solution you'd like**
With the mouse or like Pop Shell does :
https://youtu.be/-fltwBKsMY0?t=41

**Comment by garethhubball** [comment]
This looks to me to be a duplicate or at least linked to #48

**Comment by philibertc** [comment]
I have combined the material-shell with the Pop_Shell extension and it works great !
The procedure is very simple, just install the Pop Shell extension, set the default material-shell mode to "float" and enable Pop Shell tiling (which works better than the one integrated in material-shell for me).

If you can no longer lock your session with Super+L, set the shortcut to Ctrl+Alt+L. The Pop Shell extension monopolizes part of the keyboard shortcuts with the Super key.

**Comment by Luctins** [comment]
That works, but breaks some features, like having three things and "sliding" between pairs in split view (e.g. text editor, console, doc pdf).

**Comment by philibertc** [comment]
Yes, I noticed that some features are no longer usable when Pop Shell shell tiling is enabled. In fact it's all the material-shell features like maximize, split, half, ratio, grid, and simple that conflict with Pop Shell (the window won't stop vibrating).
When I want to use these features, I disable Pop Shell tiling with the default shortcut Super+Y of the extension.
For the gaps, it is possible to define them in the Pop Shell extension parameters or directly by clicking on the icon in the tray icon bar. (Picture)
![image](https://user-images.githubusercontent.com/57588282/95177787-e90c2500-07be-11eb-949a-4c598fe20897.png)

**Comment by Magean0** [comment]
I second this request: while I'm very fond of the extension, not being able to resize windows other than by changing the ratio value in Material Shell's settings isn't convenient. Changing the ratio value is cumbersome and forces an identical ratio upon all workspaces.

**Comment by Luctins** [comment]
> Yes, I noticed that some features are no longer usable when Pop Shell shell tiling is enabled. In fact it's all the material-shell features like maximize, split, half, ratio, grid, and simple that conflict with Pop Shell (the window won't stop vibrating).
> When I want to use these features, I disable Pop Shell tiling with the default shortcut Super+Y of the extension.
> For the gaps, it is possible to define them in the Pop Shell extension parameters or directly by clicking on the icon in the tray icon bar. (Picture)
> ![image](https://user-images.githubusercontent.com/57588282/95177787-e90c2500-07be-11eb-949a-4c598fe20897.png)

Yes, mine is set to 0.
![image](https://user-images.githubusercontent.com/4743486/95331081-db6aa400-087f-11eb-9d51-9505f5d88350.png)
Now I can't seem to reproduce the gaps that had shown up before, both shells dit it perfectly:
Material Shell:
![image](https://user-images.githubusercontent.com/4743486/95331209-094fe880-0880-11eb-9047-6404f00d7548.png)
PopShell:
![image](https://user-images.githubusercontent.com/4743486/95332032-3ea90600-0881-11eb-980b-96bc93ccf156.png)
But pop shell adds back in the window titlebars, wich is a bit redundant (and wastes space).

**Comment by philibertc** [comment]
@Luctins 
> But pop shell adds back in the window titlebars, wich is a bit redundant (and wastes space).

I found this solution because I wanted to have the title bar, which doesn't necessarily please everyone.
In case you don't want to have the title bar, it's true that the only feature Pop Shell adds is the ability to resize the windows when they are tiled.

**Comment by ackstorm23** [comment]
> @Luctins
> 
> > But pop shell adds back in the window titlebars, wich is a bit redundant (and wastes space).
> 
> I found this solution because I wanted to have the title bar, which doesn't necessarily please everyone.
> In case you don't want to have the title bar, it's true that the only feature Pop Shell adds is the ability to resize the windows when they are tiled.

I 100% agree.   I was just editing the windows.js to bring titlebars back but there are things I liked about Pop Shell as well so I may just go your route of combining the two.  Brilliant idea!

[FYI - The changes to windows.js I've been making to enable titlebars](https://gist.github.com/ackstorm23/9906621e64ffdbd2069a7a09ba00a932)

**Comment by PapyElGringo** [comment]
Hey guys the D days has landed ! The feature is available on the https://github.com/material-shell/material-shell/tree/resize branch.
I would need some testers before merging it to master if you guys can try it ! :+1:

**Comment by Luctins** [comment]
I will.

**Comment by Luctins** [comment]
seems to work very well OK with a single monitor, but "crushes" the rightmost window if using 2 monitors.
Single monitor:
![single05](https://user-images.githubusercontent.com/4743486/99918419-7bc43d00-2cf5-11eb-9be7-a43d3eff13ae.gif)
dual:
![dual05](https://user-images.githubusercontent.com/4743486/99918427-81218780-2cf5-11eb-999c-ff369014b639.gif)

**Comment by PapyElGringo** [comment]
@Luctins Should be fixed on last commit

**Comment by Luctins** [comment]
That did the trick, thanks!
I think this can be closed now.

**Comment by Luctins** [comment]
@PapyElGringo this seems to have reverted back when updating to gnome 40. I'm using current master branch on gnome 40.5

**Comment by dnth** [comment]
With Gnome 41.1 this seems to have reverted back too

**Comment by Luctins** [comment]
Same here. 

Also it seems like if the application is 'smaller than the given space' like console applications, which can only have sizes multiple of the size of a character, you can resize by dragging the back bar that separates the applications. On 2 'normal' applications this bar is almost impossible to click as it is about 1 px wide
