### ISSUE TITLE
Can't pin the windows on the top

### ISSUE THREAD

**Issue by chenboshuo** [material-shell/material-shell#366]
**Describe the bug**
When I used flame shot to pin  a shot, the windows can't on the top of my workplace.

**Expected behavior**
the shot should on the top of my workplace

**Screenshots**
When I focus on flame shot
![image](https://user-images.githubusercontent.com/43953268/94991542-72044000-05b6-11eb-8977-dfa5e5007e67.png)

After click my current window
![image](https://user-images.githubusercontent.com/43953268/94991544-77618a80-05b6-11eb-90a4-4e73846f4c7b.png)

the windows was changed, and the shot is not float on the top.

**To Reproduce**

- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1.intall [flame shot](https://flameshot.js.org/#/getting-start)
2. take a shot and pin it on the desktop
3. click your current windows
4. the shot is not on the top

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by PapyElGringo** [comment]
You need to add flameshot to the excluded windows
