### ISSUE TITLE
is not starting

### ISSUE THREAD

**Issue by 8mccm8** [material-shell/material-shell#371]
Hi all sorry for the poor report 

debian 10 

`TypeError: settingKey.get_range(...).get_child_value(...).recursiveUnpack is not a function

Stack trace:
  addSetting@/home/mc/.local/share/gnome-shell/extensions/material-shell@papyelgringo/prefs.js:314:30
  buildPrefsWidget@/home/mc/.local/share/gnome-shell/extensions/material-shell@papyelgringo/prefs.js:38:5
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43`

**Comment by PapyElGringo** [comment]
Hey what is your gnome-shell version?

**Comment by 8mccm8** [comment]
gnome-shell => 3.30.2-11~ded10u2

**Comment by PapyElGringo** [comment]
We are only compatible with gnome 3.34 +

**Comment by 8mccm8** [comment]
ok 

sad.....
