### ISSUE TITLE
Drop-down menus in some apps are anchored somewhere off-screen

### ISSUE THREAD

**Issue by kellya** [material-shell/material-shell#373]
**Describe the bug**
In certain apps (the first one I remember is Scribus) drop-down selection menus appear to be anchored somewhere off-screen and you are unable to view the contents of the drop-down.  I just noticed this in Scribus, which is what I used as the example to document the issue, but I have seen it in other apps too.  I will update when I catch another app though.

**Expected behavior**
Drop-down list should render underneath the selector

**Screenshots**
[Video of the issue](https://gateway.ipfs.io/ipfs/QmVS3CCKKuHfe5SUtcXq22h1npAWiYxGPMWW2z9yF55H1G)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [X] Wayland
- GNOME Shell version: 3.36
- Distro: Fedora 32
- Steps to reproduce, if applicable:
1. Start Scribus
2. navigate to insert->barcode
3. Attempt to pick a barcode family
4. Bug

**Current commit**
21b48f8

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
-- Logs begin at Mon 2020-10-05 12:24:20 EDT, end at Tue 2020-10-06 08:57:53 EDT. --
Oct 06 08:30:20 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [/home/kellya/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js 80]: reference to undefined property "_proxyChangedProperties"
Oct 06 08:30:20 salticus.franklin.edu gnome-shell[233232]: JS ERROR: TypeError: proxy._proxyChangedProperties is undefined
                                                           refreshPropertyOnProxy/<@/home/kellya/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:80:17
Oct 06 08:30:21 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:22 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:24 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:24 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:25 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:26 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:27 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:28 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:30:42 salticus.franklin.edu appindicatorsupport@rgcjonas.gmail.com[233232]: Microsoft Teams - Preview1, Impossible to lookup icon for 'Microsoft Teams - Preview1_2-panel' in path /tmp/.org.chromium.Chromium.XFw9iX
Oct 06 08:30:42 salticus.franklin.edu appindicatorsupport@rgcjonas.gmail.com[233232]: unable to update icon for Microsoft Teams - Preview1
Oct 06 08:30:54 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 299ms, your system is too slow
Oct 06 08:31:01 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 68ms, your system is too slow
Oct 06 08:31:02 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 394ms, your system is too slow
Oct 06 08:31:02 salticus.franklin.edu gnome-shell[233232]: libinput error: client bug: timer event6 middlebutton: scheduled expiry is in the past (-104ms), your system is too slow
Oct 06 08:31:03 salticus.franklin.edu gnome-shell[233232]: libinput error: client bug: timer event6 middlebutton: scheduled expiry is in the past (-312ms), your system is too slow
Oct 06 08:31:13 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 23ms, your system is too slow
Oct 06 08:31:49 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 90ms, your system is too slow
Oct 06 08:34:54 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 20ms, your system is too slow
Oct 06 08:37:55 salticus.franklin.edu gnome-shell[233232]: libinput error: client bug: timer event6 tap: scheduled expiry is in the past (-140ms), your system is too slow
Oct 06 08:37:55 salticus.franklin.edu gnome-shell[233232]: libinput error: client bug: timer event6 tap: scheduled expiry is in the past (-44ms), your system is too slow
Oct 06 08:38:15 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 12ms, your system is too slow
Oct 06 08:38:33 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 79ms, your system is too slow
Oct 06 08:39:23 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 11ms, your system is too slow
Oct 06 08:39:49 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 11ms, your system is too slow
Oct 06 08:41:43 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 14ms, your system is too slow
Oct 06 08:45:39 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 15ms, your system is too slow
Oct 06 08:47:00 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 11ms, your system is too slow
Oct 06 08:47:20 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [/home/kellya/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/utils/index.js 52]: reference to undefined property "leading"
Oct 06 08:47:21 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:22 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:23 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:24 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:25 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:26 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:27 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:28 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:29 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:30 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:31 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:32 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:33 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:34 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:35 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:36 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:37 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:38 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:39 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:40 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:41 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:42 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:43 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:44 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:45 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:46 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:47 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:48 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:49 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:50 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:51 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:52 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:53 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:54 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:55 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:56 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:57 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:58 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:47:59 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:00 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:01 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:02 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:03 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:04 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:05 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:06 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:07 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:48:08 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:49:26 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 11ms, your system is too slow
Oct 06 08:50:03 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 57ms, your system is too slow
Oct 06 08:50:53 salticus.franklin.edu gnome-shell[233232]: libinput error: event3  - AT Translated Set 2 keyboard: client bug: event processing lagging behind by 14ms, your system is too slow
Oct 06 08:54:26 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:27 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:28 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 13ms, your system is too slow
Oct 06 08:54:28 salticus.franklin.edu gnome-shell[233232]: libinput error: event6  - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 31ms, your system is too slow
Oct 06 08:54:28 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:29 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:30 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:31 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:32 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:33 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:34 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:38 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:39 salticus.franklin.edu gnome-shell[233232]: libinput error: client bug: timer event6 tap: scheduled expiry is in the past (-2ms), your system is too slow
Oct 06 08:54:52 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"
Oct 06 08:54:55 salticus.franklin.edu gnome-shell[233232]: JS WARNING: [resource:///org/gnome/shell/ui/shellDBus.js line 62 > eval 1]: reference to undefined property "-1"

```
example log data
```

**Comment by kellya** [comment]
Confirmed this is only happening in Wayland, xorg seems to do it correctly.  Consequently, it looks like I may not be a further good test case for wayland because things overall seem to be better in xorg :)

**Comment by PapyElGringo** [comment]
Should be fixed anyway
