### ISSUE TITLE
Scrolling lists of windows and workspaces in the panels

### ISSUE THREAD

**Issue by Magean0** [material-shell/material-shell#375]
Hey,

Thank you very much for developing this extension. It's very neat and works very well.

There's however one addition I'd like to suggest: would it be possible for the panels to be scrollable so as to move across windows and workspaces? This kind of scrolling has been an old-time staple of window lists and workspace indicators in the realm of Linux desktops. Not having it feels a bit odd, and makes navigation somewhat not as smooth as it could be.

Thanks in advance, keep up the good work!

Cheers

**Comment by PapyElGringo** [comment]
What do you mean exactly? Using the mouse wheel while hovering the top panel should switch windows and on the left panel switch among workspaces ?

**Comment by Magean0** [comment]
Yes, exactly. Thanks for replying.

**Comment by PapyElGringo** [comment]
Done
