### ISSUE TITLE
Cycled workspace do not work restrain moving windows

### ISSUE THREAD

**Issue by NastuzziSamy** [material-shell/material-shell#379]
**Describe the bug**
When workspaces are cycled, moving a window from the first workspace to the last by going up is not working.
It is creating a new first workspace and all workspaces increment themselves.

**Expected behavior**
Moving up a window from the first workspace should move the window to the last workspace.

**Screenshots**
None

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Enable cycled workspaces
2. Open a window into the first workspace
3. Have multiple opened workspaces
4. Move up the first window 
5. A new workspace will pop up and the window still in the first workspace

**Current commit**
master: 21b48f8

**Log data**
None

**Comment by sebastian-xyz** [comment]
Seems to be fixed by #380
