### ISSUE TITLE
Bug in Overview and possible memory leak

### ISSUE THREAD

**Issue by lfom** [material-shell/material-shell#381]
**Describe the bug**
After starting MS, the first time Overview is activated the widows are stacked (sizes and positions are broken), all workspace previews on the right are empty as well. After this, it seems to work properly, so I guess something needs to be fixed when the extension starts and state is restored.

Also, after a while, `gnome-shell` memory usage in `top`/System Monitor increases a lot. From my observation, memory usage increases mainly after suspending with many windows opened.

**Expected behavior**
Windows displayed correctly since start and memory usage should not increase dramatically after some time MS is running.

**Screenshots**
N/A

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36.3
- Distro: Pop!_OS 20.04
- Steps to reproduce, if applicable:
1. Start using MS
2. (suspend a few times with windows in different wokspaces)
3. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: 6a9cd52c26b34116769a98922e8ab82ab793e8f0

**Log data**
N/A

**Comment by lfom** [comment]
Maybe it is related: when placeholder or applauncher is selected in a workspace, then the workspace thumbnail is empty:

![Screenshot from 2020-10-07 15-41-06](https://user-images.githubusercontent.com/15659999/95373773-d6bfe300-08b3-11eb-9b73-129434b8ccef.png)

**Comment by thecodejedi** [comment]
Hey there! 

I don't have the overview bug, but my gnome-shell reaches 2GB Memory footprint easily with material shell enabled...

Maybe we should split this issue?
