### ISSUE TITLE
Need to be able to navigate to my second monitor

### ISSUE THREAD

**Issue by sigboe** [material-shell/material-shell#4]
Need to be able to navigate to my second monitor

**Comment by PapyElGringo** [comment]
With the keyboard you mean?

**Comment by sigboe** [comment]
yes please

**Comment by BitPhinix** [comment]
I have a triple monitor setup and would love to have an I3-ish way of assigning workspaces to specific monitors and navigate between them. Keep up the good work :)

**Comment by vitorhugods** [comment]
I don't know exactly if this issue includes the `Workspace span displays`.

I'm using two monitors, and I would really like that when I press `Super+W` or `Super+S`, the second monitor would change as well.

When trying to change the `Display Handling` in the `Workspaces` section of the Gnome Tweaks, I get a message informing that `material-shell` does not care.

**Comment by indyfree** [comment]
Is there any update on this? Would be really handy to add shortcuts/hotkeys to focus workspaces on the second/third monitor without having to use the mouse.

**Comment by gcstr** [comment]
I second that.
And I would add that not only navigating between workspaces but also when switching window focus with Super + A and Super + D.

Currently the focus Prev and next only works inside the workspace/monitor.

**Comment by MattByName** [comment]
Yes, this feature would be great.

**Comment by PapyElGringo** [comment]
Which shortcut would you like?

It's seem usefull only for a both hand on keyboard workflow, so maybe something like `Super + ArrowKeys` but it's often already used

**Comment by DiaanEngelbrecht** [comment]
Maybe a screen toggle command in one direction would be fine? Just something like `Super + Tab`. It's already bound, but I doubt I need Ubuntu's switch applications when I'm running material shell.

**Comment by AlexZolotarenko** [comment]
`Super + Left` and `Super + Right` in Gnome  set to tile window to the left / right. 
Since that does not make sense with Material Shell extension, it may be quite useful to use them to switch between monitors. 
Other option I may think of is `Super + Ctrl + a` or `Super + Ctrl + d` and so on for '+w', '+d' if necessary

**Comment by davidlind** [comment]
+1. I would love this feature.

**Comment by thomjs** [comment]
This would be great, it could even just be left optional, and let the user choose their own keybinding that fits their workflow. I use Super+{H,J,K,L} for workspaces and windows, and would be in favour of Super+Shift+{H,J,K,L} for displays/monitors.

**Comment by Ben8** [comment]
I don't know if this is related, but I really hope it will be possible to have workspaces on multiple monitors. Either adding the sidebar to all monitors and having workspaces different between monitors or having each workspace span all monitors would be useful.

**Comment by paultop6** [comment]
Until this is implemented, there are two "workarounds":
1: Switch to a program running in the second window, then the super WASD nav will work for that window.
2: If you distro allows it, use an extended manitor layout.  That way its treated as one big monitor so you can easily utilise all screen space.

I was going to go with option two, but I see it isnt supported in Ubuntu 20.04 (even though older versions had it :S)

**Comment by jjgumucio** [comment]
> Until this is implemented, there are two "workarounds":
> 1: Switch to a program running in the second window, then the super WASD nav will work for that window.
> 2: If you distro allows it, use an extended manitor layout. That way its treated as one big monitor so you can easily utilise all screen space.
> 
> I was going to go with option two, but I see it isnt supported in Ubuntu 20.04 (even though older versions had it :S)

Yep... I was going for the second option on Pop OS! too but, Pop being based on Ubuntu well, sad that this makes dual monitor usage useless or materual-shell useless.

Hoping for this feature to be implemented soon.

**Comment by PapyElGringo** [comment]
This should be fixed in Master

**Comment by paultop6** [comment]
Awesome, can't wait to give this another try with multi monitor navigation sorted

**Comment by ErickHoward** [comment]
> This should be fixed in Master

It seems to have broken since it was fixed - with two monitors the second monitor does not respect workspace changes
