### ISSUE TITLE
Quake mode of Tilix doesn't work

### ISSUE THREAD

**Issue by Merlin04** [material-shell/material-shell#40]
I use the "Quake" feature of Tilix heavily. When I press F12, a Tilix window (but without window controls) appears in the upper half of my screen and stays on top of everything. When I press F12 again, it effectively minimizes the window. This doesn't seem to work with Material Shell. When I press F12, it switches to the "others" tab and opens Tilix full screen. If I close it out again, it leaves me in the "others" tab, and I have to switch back to whatever I was doing.

**Comment by JordyScript** [comment]
I will add my voice to this. It would be nice if dropdown terminals (Tilix, Yakuake, etc.) can still behave the way they do in a non tiling window manager. If they can just slide down the screen, covering the other windows, and then slide back up, that would be perfect, but this is probably hard to implement.

**Comment by skluthe** [comment]
Maybe adding blacklisting for applications would be beneficial?

**Comment by PapyElGringo** [comment]
I pushed this in my last commit 1518377. Could you give it a try? There is a new entry in the settings to exclude some window classes.
