### ISSUE TITLE
Firefox doesn't loose the title bar

### ISSUE THREAD

**Issue by giorgiga** [material-shell/material-shell#400]
Sorry for the undetailed report: I already uninstalled material shell but then I thought I should let you know about this.

I was trying out this extension in manjaro under wayland (I think) and the firefox titlebar wouldn't go away when I told firefox not to show it.
Firefox did change the tab bar integrating the close button, but the titlebar with a second close button was still visible above it.
The strangest thing is that I also had firefox-developer-edition installed and the titlebar disappeard as expected in it.

**Comment by PapyElGringo** [comment]
It's probably depend on the titlebar setting in firefox it's must be set to use the `System titlebar`

**Comment by giorgiga** [comment]
Err... I guess you must get a lot of bug reports from script kiddies who don't know their left from their right nowadays :-)

Firefox settings were fine: in fact, the titlebar disappeared on its own after I disabled the material shell extension.

Anyway, feel free to close this if you can't replicate: I didn't really investigate since I was going to remove material shell anyway and it might very well be due to some astral conjunction happening in my system.

**Comment by Chrysostomus** [comment]
Often toggling that setting twice helps even if the setting is already right.

**Comment by giorgiga** [comment]
Closing, as devs think PIBKAC and I don't want to be a bother any further

**Comment by PapyElGringo** [comment]
We are not presuming that the issue is PIBKAC we just need to check and eliminate the main issue sources since many people using Firefox without raising this error. So the issue is not obvious either way.
I would also be interested to know how Material Shell was disappointing for your use cases.
Thanks for the feedback anyway !

**Comment by giorgiga** [comment]
@PapyElGringo I guess my wording wasn't the most appropriate – sorry if it sounded harsh in any way :)

I did try the obvious tricks (reset and re-set the settings, restart ff, restart the gnome shell), but since you obviously can't replicate and neither can I (since I uninstalled) there is no point in wasting dev time on this issue. When I noticed this I was trying out gnome and fiddling with extensions, so it must have been some idiosyncrasy of my system.
