### ISSUE TITLE
Can't move windows from main monitor to additional ones through keyboard

### ISSUE THREAD

**Issue by HaisojYellams** [material-shell/material-shell#402]
**Describe the bug**
I am unable to move windows from my main screen (center) to additional screens (left/right) using the keyboard (shortcuts `SUPER-SHIFT-LEFT`/`SUPER-SHIFT-RIGHT`). I *am* able to move windows from the additional screens _to_ the main one in this manner, however.

**Expected behavior**
I expect to be able to move windows from the main screen to the additional screens through the keyboard

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.34.8
- Distro: Fedora 31

**Current commit**
`5cef1be`

**Log data**
No relevant logs

**Comment by wolterlw** [comment]
same issue, but I can't move windows in both directions

**Comment by karottenreibe** [comment]
This also doesn't work on Wayland/Ubuntu 20.04.1/Gnome 3.36.3 for me

**Comment by tsopanid** [comment]
Same on Manjaro 20.1.2 with Gnome 3.36.6

**Comment by TheRafaelFarias** [comment]
That was occurring with me too, I just updated and worked again
