### ISSUE TITLE
Document gschema override

### ISSUE THREAD

**Issue by Chrysostomus** [material-shell/material-shell#404]
**Is your feature request related to a problem? Please describe.**
I would like to set distro default for material-shell settings
**Describe the solution you'd like**
Documentation on how to apply gschema override file to the extension.
**Describe alternatives you've considered**
Currently we have most of our gnome-settings in file /usr/share/glib-2.0/schemas/99_manjaro-settings.gschema.override. If I try to apply the defaults for other gnome-extensions and apps like this:

```
[org/gnome/shell/extensions/materialshell/layouts]
float=false
split=false
half=true
default-layout='half'
windows-excluded='Enpass,Gnome-layout-switcher'
ratio-value=0.54999999999999993

[org/gnome/shell/extensions/materialshell/theme]
clock-horizontal=true
primary-color='#2eb398'
taskbar-item-style='name'


```
The settings are not getting applied to new user accounts. Some extensions like arc-menu require compiling the gschema-file for them, but material-shell already provides the compiled gschema files.

I could also just patch the gschema files provided by the extension, but I would prefer not to do that for an extension that gets updated this frequently. Another option would be to apply the dconf settings with a one-shot script on login, but that is extremely hacky. 

So, what wuold be the recommended option to apply distro defaults to material-shell settings?

**Comment by PapyElGringo** [comment]
I have no idea... I'll ask around !

**Comment by Chrysostomus** [comment]
We are also looking into on our end. I'll post here when we find something.

**Comment by PapyElGringo** [comment]
Well it's seem that using the gschema override is the proper way to do it. So you are saying it's not working with Material Shell?

**Comment by Chrysostomus** [comment]
Unfortunately not. We ended hacking it with an autostart script:

https://gitlab.manjaro.org/profiles-and-settings/manjaro-gnome-settings/-/blob/19.0/scripts/apply-tiling-settings

**Comment by Chrysostomus** [comment]
It also doesn't work for pop-shell and some other extensions. I'm not sure what would need to be implemented in the extension for it to work. For some extentions it does work.

**Comment by PapyElGringo** [comment]
But your script still use gschema override but loaded manually?
