### ISSUE TITLE
"Applications" button in left panel

### ISSUE THREAD

**Issue by matguidi** [material-shell/material-shell#405]
I'm using Material Shell on Manjaro, and I've noticed that, at the bottom of the vertical panel, there's an "Applications" button that opens the menu of all applications. I have no problems with this menu, but it's not really necessary, and the fact that it's button consists in a word that doesn't fit the panel width makes it... not pretty:
![Schermata del 2020-10-18 00-42-43](https://user-images.githubusercontent.com/59918868/96354792-e4a70c80-10da-11eb-91ad-673fdf60893b.png)
I haven't seen this button in screenshots and videos, so it might be something related to Manjaro, but is there a way to edit the panel configuration so that it doesn't show up? I have searched in the documentation and I haven't find anything on this.

**Comment by matguidi** [comment]
Sort it out by myself: it was due to the "Applications menu" extension (https://extensions.gnome.org/extension/6/applications-menu/). Deactivated, problem solved.

**Comment by PapyElGringo** [comment]
Indeed :)
