### ISSUE TITLE
App launcher has the wrong app grid size on startup.

### ISSUE THREAD

**Issue by expeehaa** [material-shell/material-shell#423]
**Describe the bug**
If app launcher is shown directly after logging in to gnome, it has a "wrong" application grid size on my Surface Go. Moving the cursor over the grid triggers a resize of the app launcher grid making the grid smaller (see screenshots).
This is especially annoying when I want to use the touch screen to start an application, since the resize happens after touching, but before starting the application, which may lead to the wrong application being started.

**Expected behavior**
The app launcher has the correct grid size on startup.

**Screenshots**
![App launcher directly after startup.](https://user-images.githubusercontent.com/12911474/97063343-76ad8a00-159f-11eb-9e22-b34966d8ce35.png)
![App launcher with the "correct" grid size.](https://user-images.githubusercontent.com/12911474/97063344-7a411100-159f-11eb-9214-0fcde6eb35b8.png)
With a higher panel size:
![App launcher directly after startup.](https://user-images.githubusercontent.com/12911474/97063806-2e439b80-15a2-11eb-9c95-ac88f30919e6.png)
![App launcher with the "correct" grid size.](https://user-images.githubusercontent.com/12911474/97063836-503d1e00-15a2-11eb-96c4-b4fd0f64bdda.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.36
- Distro: openSUSE Tumbleweed
- Screen size: 1600x1200
- Steps to reproduce, if applicable:
1. Set the panel size to a value such that the difference between the maximized window size and the actual screen size results in different app launcher grid sizes.
2. Close all applications to directly view the app launcher when logging into gnome.
2. Log out and back into gnome.
3. Observe the app launcher grid when moving the cursor over the grid.

**Current commit**
Output from `git rev-parse --short HEAD`: `c5c4313`

**Log data**
Output from `journalctl /usr/bin/gnome-shell` (not sure if this is the excerpt from the login until after the resize, but looks right to me):
```
Okt 24 02:12:52 xsurf gnome-shell[18049]: JS WARNING: [/home/xph/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js>
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Restoring previous state
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Step 1 Remove empty workspace if any
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Checking among 1 workspaces
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Removing 1 empty workspaces
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Step 2 Restoring 0 previous MS workspace
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Start by restoring external monitors: 0 external monitors found and 0 external MS workspaces found
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Then continue by restoring all other 0 MS workspaces into 1 existing gnome-shell workspace
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Then continue by creating a new Ms Workspace for every Gnome Workspace still not assigned 1
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Setup a new Workspace
Okt 24 02:12:52 xsurf gnome-shell[18049]: [DEBUG], Create new MS Workspace: Restoring previous state? NO
Okt 24 02:12:53 xsurf gnome-shell[18049]: [DEBUG], stateChanged from createNewMsWorkspace
Okt 24 02:12:53 xsurf gnome-shell[18049]: [DEBUG], Then add the last empty Ms Workspace at the end
Okt 24 02:12:53 xsurf gnome-shell[18049]: [DEBUG], Setup a new Workspace
Okt 24 02:12:53 xsurf gnome-shell[18049]: [DEBUG], Create new MS Workspace: Restoring previous state? NO
Okt 24 02:12:53 xsurf gnome-shell[18049]: [DEBUG], stateChanged from createNewMsWorkspace
Okt 24 02:12:54 xsurf gnome-shell[18049]: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of th>
                                          (Note that array.toString() may have been called implicitly.)
                                          0 toString() ["self-hosted":629:4]
                                          1 parseStat() ["/home/xph/.local/share/gnome-shell/extensions/simplenetspeed@biji.extension/extension.js":117:19]
Okt 24 02:12:55 xsurf gnome-shell[18049]: [DEBUG], Remove workspace because it's empty
Okt 24 02:12:55 xsurf gnome-shell[18049]: [DEBUG], Workspace 1 was removed
Okt 24 02:12:55 xsurf gnome-shell[18049]: [DEBUG], stateChanged from removeMsWorkspaceAtIndex
Okt 24 02:12:55 xsurf gnome-shell[18049]: [DEBUG], Inside stateChanged
Okt 24 02:12:56 xsurf gnome-shell[18049]: GNOME Shell started at Sat Oct 24 2020 02:12:50 GMT+0200 (CEST)
Okt 24 02:12:56 xsurf gnome-shell[18049]: Registering session with GDM
Okt 24 02:12:56 xsurf gnome-shell[18049]: ----------------
Okt 24 02:12:56 xsurf gnome-shell[18049]: EXTENSION LOADED
Okt 24 02:12:56 xsurf gnome-shell[18049]: ----------------
Okt 24 02:12:56 xsurf gnome-shell[18049]: --------------------
Okt 24 02:12:56 xsurf gnome-shell[18049]: END EXTENSION LOADED
Okt 24 02:12:56 xsurf gnome-shell[18049]: --------------------
Okt 24 02:12:56 xsurf gnome-shell[18049]: [DEBUG], registry successfully saved
Okt 24 02:12:56 xsurf gnome-shell[18049]: Window manager warning: Overwriting existing binding of keysym 73 with keysym 73 (keycode 27).
Okt 24 02:12:56 xsurf gnome-shell[18049]: Window manager warning: Overwriting existing binding of keysym 20 with keysym 20 (keycode 41).
```

**Comment by lfom** [comment]
The log shows no errors. Does it happen only when you change panel size and logout?

**Comment by expeehaa** [comment]
No, the issue only appears on login, but it does not matter whether the panel size gets changed or not.
I guess that the problem might be something like the app launcher grid being created on login using the screen size without the panels, and the panels being created afterwards (though I haven't looked at the code yet, this is purely speculative). That would obviously lead to no errors, I just wanted to add the log as it is a part of the bug template.
The only problem with my theory is that the issue exists only with the width, not the height.

**Comment by lfom** [comment]
Are you using GDM or something else? Maybe the screen resolution changes when you login?

**Comment by im6h** [comment]
![image](https://user-images.githubusercontent.com/35485655/97254271-96171200-1840-11eb-8a44-8faa52903a0d.png)


Icon notification is wrong display when I change clock from left bottom to right top.

**Comment by lfom** [comment]
@im6h I was fixed already in the master branch, you can either update manually or wait until the next release.

**Comment by expeehaa** [comment]
It seems like the bug is fixed in release 9, I can’t reproduce it anymore.
