### ISSUE TITLE
Clear new tab search box after closing tab

### ISSUE THREAD

**Issue by artouiros** [material-shell/material-shell#424]
**Is your feature request related to a problem? Please describe.**
When you open new tab and search for an app and then you change your mind and move back to previous windows, then next time you open new tab, the previous search is there and you cannot fast search beecause you need to manually backspace previous text.

**Describe the solution you'd like**
Just clear searchbox when closing tab withotu selecting anything. Can be set on timeout, maybe you did switch to other windwos for a few seconds then you will continue typing your search.

**Describe alternatives you've considered**
As I said it can be set on timeout.

**How to reproduce**
1. Open new tab, start searching for an app
2. Dont select anything, pretend you changed your mind. Return to your previous work in other tab.
3. Open new tab, you will expect to start typing yoru search query, but you can't because you will need to backspace previous one.

**Comment by lfom** [comment]
Pressing ESC when there is text in the search entry should clear it, doesn't it work for you? If not, could you please provide a log?

**Comment by artouiros** [comment]
This actually works,
