### ISSUE TITLE
By default, Super+space cycles through the tiling layout even if disabled

### ISSUE THREAD

**Issue by NicholasMamo** [material-shell/material-shell#427]
**Describe the bug**
Super+space cycles through the tiling layout even though the hotkey disabled. This seems to happen only on a newly-installed material shell.

**Expected behavior**
Super+space should change the input source, or language, not the tiling layout.

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [ x ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Disable the 'cycle around the tiling layout on the current workspace'
2. Press Super+space
3. The tiling layout changes (instead of changing the input source, or language)

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Workaround**
Assign a different hotkey to it, then disable the new hotkey again.

**Comment by lfom** [comment]
The MS setting you are referring to is meant to do something else: it is meant to navigation through the horizontal bar in a cyclic way (go to the beginning when moving forward in the end). To do what you want, you must change the default keybinding in the settings instead (make sure Gnome still uses it too).

**Comment by NicholasMamo** [comment]
> The MS setting you are referring to is meant to do something else: it is meant to navigation through the horizontal bar in a cyclic way (go to the beginning when moving forward in the end). To do what you want, you must change the default keybinding in the settings instead (make sure Gnome still uses it too).

Oh go
