### ISSUE TITLE
Alt-Tab -> Go to previous window (across all workspaces)

### ISSUE THREAD

**Issue by VanCoding** [material-shell/material-shell#430]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to configure Alt-Tab so that it always goes to the previous window, no matter if it's on the current namespace, or on a different namespace. But this is something I am very used to. For example, I usually have multiple development workspaces, that all have a terminal and a code editor. And one workspace with the browser. And normally, I want to alt-tab between the terminal and the code editor. But sometimes, when I need to google something, I want to go back and forth with my browser and the editor on Alt-Tab. Without Material Shell, I didn't use workspaces and so I didn't have this problem. But with Material Shell, this is really a pain, even if I like the concept really much. A quick keyboard shortcut to jump to the last window, no matter on what workspace I currently am, is a must for me.

**Describe the solution you'd like**
Add some sort of setting to the exenstions setting menu to toggle the expected behavior.

**Describe alternatives you've considered**
I've tried using the extension "alternativeTab" but it sadly didn't work.

**Comment by lfom** [comment]
Maybe I missed something here, but Alt + Tab never moved to the previous window (or last window): it is used to switch between open apps. And it is not a MS shortcut, it is actually used by Gnome Shell itself. There are tons of shortcuts for window/app navigation in Setting (Gnome Control Center) >>> Keyboard, and they also can be customized. As far know, MS also honors these shortcuts (unless the user manually replaced one of MS shortcuts with a Gnome Shell one, of course), so you can easily use one of the Gnome Shell options to do what you want.

**Comment by VanCoding** [comment]
Yes, Material Shell does not alter the Alt + Tab Shortcut directly. But the order of the window-list that appears when Alt-Tabbing behaves different in Material Shell than in stock gnome. In stock gnome, windows in the alt-tab list are ordered by last used time. In Material Shell, that's no longer the case.

**Comment by lfom** [comment]
Ah, I see what you mean now: MS minimizes the window in the same workspace when changing focus to another app in Maximize layout (you can see this if you go to App Launcher using Maximize layout and then open Overview: workspace is empty), that's why the order in Alt+Tab changes. I don't know if it is was simply by design or some needed behavior, so I am not sure if this can be fixed.

**Comment by VanCoding** [comment]
@lfom aaaahh! I only now realized that this problem does not exist on all other layouts. I tried to live without material shell for a while because of this problem. But I couldn't :D I should've paid a bit more attention to what you've said, sorry!

My solution is now to just ban the "Maximize" Layout completely.

**Comment by opalmay** [comment]
Any way to deal with this? Not using "Maximize" works but it's not a solution

**Comment by josemanuelp** [comment]
I've disabled all but 'Switch Windows' and is working pretty well in Maximized mode. I don't know if this is exactly what you want, but is good for me.

![image](https://user-images.githubusercontent.com/6510893/159498918-419e18eb-c4b5-4a16-8761-440ffd943692.png)
