### ISSUE TITLE
Workspace application selector triples in size if moved incorrectly

### ISSUE THREAD

**Issue by hashworks** [material-shell/material-shell#451]
**Describe the bug**
When one moves the application selector in a certain way the selector height triples. I can repeat the process by moving it up and then letting it go. It happens with Touch and Mouse input.

When moved left/right it returns to its normal size again.

**Screenshots**
![first tripling](https://fb.hash.works/kvZfQ/)
![second tripling](https://fb.hash.works/wEOUKc/)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [X] Wayland
- GNOME Shell version: 3.38
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Open an application
2. Move application selector up
3. See that it increases in size
4. Repeat the process to double multiple times

**Current commit**
Output from `git rev-parse --short HEAD`: `ddc4825`

**Comment by jugendhacker** [comment]
I can reproduce this, also with Arch Linux and GNOME 3.38. As a workaround I reorder the glitching application selector and the glitch is gone.

**Comment by PapyElGringo** [comment]
Should be fixed
