### ISSUE TITLE
Dragging pop up window/ model dialogs, moves parent window

### ISSUE THREAD

**Issue by vineeth-MVR** [material-shell/material-shell#455]
**Describe the bug**
When we mouse drag a model dialog, the parent window reacts to it. But, the dialog window stays in same position.

**Expected behavior**
A dialog window must be draggable to any position.

**Screenshots**
https://vimeo.com/474753210

**To Reproduce**
- Occurs on:
  - [ * ] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Make any application to produce a dialog window
2. Try to drag the dialog window to desired postion
3. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by PapyElGringo** [comment]
It's fixed in the new version what is your current version?

Le lun. 2 nov. 2020 à 18:47, Vineeth Reddy <notifications@github.com> a
écrit :

**Comment by vineeth-MVR** [comment]
Hi, sorry for the late reply
Could you help me find the version?
BTW, i have installed it from the gnome shell extensions

**Comment by vineeth-MVR** [comment]
It fixed!
Just now uninstalled and re installed from git.
It works just as intended.
@PapyElGringo I greatly appreciate your work, starred!
