### ISSUE TITLE
[Feature request] resize windows in tiling

### ISSUE THREAD

**Issue by Wael2727** [material-shell/material-shell#457]
**Is your feature request related to a problem? Please describe.**
no, but probably yes, 
resizing windows in tiling is very important to appeal for aeshetics.
what i mean by this is to use the cursor to resize the windows.

_im probably gonna look very stupid if this is already a feature that i just cant find_

**Describe the solution you'd like**
maybe add the option to resize using keybinds/mouse
let me show a video explaining this.
https://streamable.com/706pgr

**Describe alternatives you've considered**
Pop Shell.

**Comment by GoshaEgorian** [comment]
This is related to #48 
Also a workaround can be found here #362

**Comment by Wael2727** [comment]
alright, ig I have to combine both
thanks for letting me know.
