### ISSUE TITLE
JS ERROR: TypeError: this.workspaceManager.get_workspace_by_index(...) is null

### ISSUE THREAD

**Issue by caseca** [material-shell/material-shell#469]
Ubuntu 20.04

JS ERROR: TypeError: this.workspaceManager.get_workspace_by_index(...) is null
restorePreviousState@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:339:22
enable/</<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:83:39
loadRegistry@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js:33:20
enable/<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:68:25

**Comment by PapyElGringo** [comment]
Are you on Master? Or you installed from gnome website?

**Comment by caseca** [comment]
On Master

**Comment by caseca** [comment]
The Material-shell not start.

**Comment by caseca** [comment]
Sorry for not putting it in the default but I'm at work and I'm running to solve some problems. I promise that the next ones will be in the standard

**Comment by PapyElGringo** [comment]
Is that a fresh install or and it's crashed since you updated?

**Comment by caseca** [comment]
Crashed since I update

**Comment by PapyElGringo** [comment]
can you try pull last commit

**Comment by caseca** [comment]
Started working again. Thank you.
