### ISSUE TITLE
Touching the workspace icons to switch workspaces sometimes freezes Gnome Shell touch & mouse input

### ISSUE THREAD

**Issue by hashworks** [material-shell/material-shell#471]
**Describe the bug**
Touching the workspace icons to switch workspaces sometimes freezes Gnome Shell touch & mouse input, even when moving out of the extension (f.e. activities overview). Mouse and Touch input in the open window still works fine as well as any keyboard shortcuts. Restarting gdm fixes this.

**To Reproduce**
- Occurs on:
  - [ ] X.Org (tested, couldn't reproduce)
  - [X] Wayland
- GNOME Shell version: 3.38
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Create 2 Workspaces
2. Switch between them multiple times using touch
3. Behold the Gnome input freeze by not being able to switch workspaces any more (or anything else)

**Current commit**
Output from `git rev-parse --short HEAD`: `2e1d45a776f6a7f469861cca66a502c8970cad7e`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`: https://fb.hash.works/iKDCOh0/

**Comment by nibirrayy** [comment]
@hashworks  just to inform you that there is already a issue open relating this so can you track your issue there. 
#452

**Comment by hashworks** [comment]
Thanks, closing this one since it's newer
