### ISSUE TITLE
Add the option to show an outline around the focused window

### ISSUE THREAD

**Issue by phillipprado** [material-shell/material-shell#474]
I have previously used tiling window managers that outline the window in focus. The Pop OS tiling extension is a good example of how I believe this could be implemented. It lets the user easily see which window has focus with minimal effort, and it looks good too.

I personally would like to be able to choose the color or at least let it default to the primary UI color already chosen in the Material Shell settings, and I would like to adjust the thickness of the outline.

**Comment by Luctins** [comment]
I think the discussion in #362 may be of your interest, as using material shell in float mode + pop shell's tiling is a interesting alternative.

**Comment by PapyElGringo** [comment]
available in the settings
