### ISSUE TITLE
Add option to resize windows 

### ISSUE THREAD

**Issue by Chrysostomus** [material-shell/material-shell#48]
Currently windows cannot be resized. It would be optimal to achieve the same behavior as most tiling wms, where resizing a window automatically resizes also neighboring tiles.

I'm very impressed by your work. I'm a Manjaro Linux maintainer and I plan to build a Manjaro edition that would enable this extension by default if it is okay to you. I would also add is an option to gnome-layout-switcher, which I'm developing. 
https://gitlab.manjaro.org/Chrysostomus/gnome-layout-switcher

Featurewise this is probably the only "showstopper" issue before I would consider this ready for packaging and distribution. You have done amazing work, and I'm really looking forward to this project maturing and stabilizing.

**Comment by PapyElGringo** [comment]
This is of course a wanted feature.

And I'm glad that you consider my work to be interesting to deploy as primary layout for Manjaro ! I would suggest you to let us a bit more time to stabilize the project and for the project to be tested my more people. It's would also require someone to maintained an AUR repo no?

**Comment by Chrysostomus** [comment]
Sure, I'm in no hurry. I was planning to wait until you publish it in the gnome shell extensions page.

I'm going to add it directly to manjaro repos, but I can maintain the AUR PKGBUILD also.

**Comment by AskAlice** [comment]
+1 on this issue pretty useless when I can't have my terminal at 1/4 width.

Also maybe support for applications that are checked as 'show on all workspaces', seems complicated to implement but it's better than having an always-on-top, show on all workspaces window like terminator have no GUI option to move or kill

**Comment by boardfish** [comment]
Another +1 for this - my use case is that I use `kitty` instead of VSCode's integrated terminal, since that crashes with large inputs (e.g. long lines in `less` or tons of logging).

**Comment by GoshaEgorian** [comment]
Upvote

**Comment by hoebbelsB** [comment]
upvote

**Comment by philibertc** [comment]
> This is of course a wanted feature.
> 
> And I'm glad that you consider my work to be interesting to deploy as primary layout for Manjaro ! I would suggest you to let us a bit more time to stabilize the project and for the project to be tested my more people. **It's would also require someone to maintained an AUR repo no?**

@PapyElGringo the material-shell extension is now in Manjaro's official repo.

**Comment by philibertc** [comment]
I have combined the material-shell with the Pop_Shell extension and it works great !
The procedure is very simple, just install the Pop Shell extension, set the default material-shell mode to "float" and enable Pop Shell tiling (which works better than the one integrated in material-shell for me).

If you can no longer lock your session with Super+L, set the shortcut to Ctrl+Alt+L. The Pop Shell extension monopolizes part of the keyboard shortcuts with the Super key.

**Comment by PapyElGringo** [comment]
Because why not

**Comment by Chrysostomus** [comment]
As a first step, how about adding a keybinding to adjust master/stacking area ratio? That would already satisfy 60% of the rezing needs. I suggest super+ctrl+a and super+ctrl+d as bindings. That's what I used in Manjaro bspwm edition, which also had wasd based direction controls, similar to material-shell. Mouse based resize can come later

**Comment by PapyElGringo** [comment]
Yeah this is a nice idea that we have in the pipe for sometimes now there has been even 2 different pull request to implement this but there is a preliminary step need for this: the ability to have a different state per layout per workspace. I'm currently working on this but in the mean time @NastuzziSamy is working on implementing the foundation of the resizeable layout and depending on how fast we go we will probably jump directly to resize capabilities.

**Comment by PapyElGringo** [comment]
Hey guys the D days has landed ! The feature is available on the https://github.com/material-shell/material-shell/tree/resize branch.
I would need some testers before merging it to master if you guys can try it ! :+1:

**Comment by Chrysostomus** [comment]
Excellent, we are making a new release next weekend, this made it just in time. I'll run some tests now.

**Comment by Chrysostomus** [comment]
Seems to work without issues. It seems that corner resizing is not yet implemented, but this is very much sufficient for now. For some reason the performance seem very good with the update, but that might be placebo.

**Comment by GoshaEgorian** [comment]
@PapyElGringo It works fine!
It seems to be a little laggy while resizing but it's ok and it's not critical.
I have found some windows haven't rezing action in some states. For example, in `half` layout the telegram in a second position and the discord in the third haven't resize action between them (vertical) if telegram is in focus state. But if you change focus window to discord the resize action will appear.

Also I don't know when it comes but now I have keyboard shortcuts issue with `shift+win+D`: it turns to `simple` layout instead of moving window right. And I have `simple` layout turned off in the same time :D

**Comment by PapyElGringo** [comment]
@GoshaEgorian Yeah I have merge a PR providing conflicting hotkeys shortcuts if you pull it's should be good now

**Comment by GoshaEgorian** [comment]
@PapyElGringo I pulled master. On current commit Super+D doesn't work so I created new bug issue to do not litter this one.

**Comment by PapyElGringo** [comment]
The feature should be finalized in Master with the border being visible and the hotkeys shortcuts for resizing with keyboard

**Comment by x8k** [comment]
Awesome! I was waiting for this feature, I'm very happy.
(now is missing just a shortcut to increase/decrease the main windows in one shot ;) )
![2020-12-27_15-57](https://user-images.githubusercontent.com/5973725/103173711-0e0fb180-485d-11eb-8abf-c95dbf6d0f31.png)
