### ISSUE TITLE
Cannot interact with window if moved to secondary monitor with overview

### ISSUE THREAD

**Issue by Luctins** [material-shell/material-shell#480]
**Describe the bug**
When a application is moved from monitor 1 to 2 it visually stays in 1 but interacts through 2.
This can be a problem with applications that have no areas to drag normally (e.g. spotify client) because dragging the material shell "tab" (below) to the other monitor has no effect (it used to work).
![image](https://user-images.githubusercontent.com/4743486/99574167-c708e380-29b5-11eb-8be3-a182557aac19.png)

In the screenshot firefox is used but it is reproducible with other applications.

**Expected behaviour**
The Window should go to secondary monitor or still be interactive.

**Screenshots**
demo below
![scaled5](https://user-images.githubusercontent.com/4743486/99571956-c02ca180-29b2-11eb-81d3-4fc3eedce756.gif)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: PopOS 20.04
- Steps to reproduce, if applicable:
1. Have 2 monitors (1 and 2).
2. Open any GUI application in monitor 1.
2. Drag it to 2 via the overlay menu.
3. Window shows on 1 but is interactive through monitor 2. 
4. Drag it back to 1.
5. Window now interacts as usual.

**Current commit**
Current from extensions.gnome.org

edit1: added one detail about drag area.

**Comment by greek** [comment]
can repro on ubuntu 20.04 on xorg

**Comment by Luctins** [comment]
????


Em ter., 24 de nov. de 2020 às 08:52, PapyElGringo <notifications@github.com>
escreveu:

**Comment by greek** [comment]
> ???? 
the issue is fixed on the `master` branch, but an update on the GNOME extensions site might take a while.
