### ISSUE TITLE
Custom hotkeys

### ISSUE THREAD

**Issue by javierluque96** [material-shell/material-shell#492]
**Is your feature request related to a problem? Please describe.**
I would like to change easily the hotkeys used as I can do with i3, where I can put all the hotkeys I want.

**Describe the solution you'd like**
Implement a file where you can modify them.

**Describe alternatives you've considered**
For a GUI solution modify them through tweaks for example.

**Comment by greek** [comment]
there's a hotkeys menu inside MatShell's settings menu, which you can access through Tweaks.
