### ISSUE TITLE
Super+D doesn't work

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#496]
**Describe the bug**
Super+D shortkey doesn't work.
This bug can be related to [resize issue](https://github.com/material-shell/material-shell/issues/48#issuecomment-732040815).

**Expected behavior**
Focus have to go to next window. 

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Press Super+D

**Current commit**
Output from `git rev-parse --short HEAD`: `7ad7023`

**Comment by PapyElGringo** [comment]
It's seem to be related with ubuntu maybe because it's used to display the desktop

**Comment by Luctins** [comment]
That is indeed a shortcut to show the desktop on some distros, @GoshaEgorian if you can, maybe try searching for `show-desktop` with Dconf editor on the gnome settings entries.
For me there is a entry under `/org/gnome/desktop/wm/keybindings/` called `show-desktop` that is unbound (`<Super>+d` works for me), you can check if yours is bound.

**Comment by GoshaEgorian** [comment]
@Luctins Thanks for solution! I found `show-desktop` was setted to `<Super>d` so I changed it. 

To show current keybinding:
`gsettings get org.gnome.desktop.wm.keybindings show-desktop`
The result in my case was:
`['<Primary><Super>d', '<Primary><Alt>d', '<Super>d']`

So I fixed it by this command (I have removed conflicting keybinding):
`gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Primary><Super>d', '<Primary><Alt>d']"`
And reload xorg: `Alt+F2`, `r` command
