### ISSUE TITLE
Discord Link is expired

### ISSUE THREAD

**Issue by alfredopalhares** [material-shell/material-shell#497]
Hello,

I would like to join the Discord Communit, but the current [invite link](https://discord.gg/vBb7D9a) its expried.
![img](https://i.imgur.com/Kpu2lkP.png)

Regards,
Alfredo Palhares

**Comment by PapyElGringo** [comment]
Wierd it's should still be valid and it's seem valid for me :(

**Comment by Luctins** [comment]
Here seems fine too:
![image](https://user-images.githubusercontent.com/4743486/100607617-f7bc1780-32e9-11eb-87f3-cf4060b19fa5.png)

**Comment by JonasLoos** [comment]
For me the link just worked fine too.

**Comment by PapyElGringo** [comment]
The bottom left link was indeed broken
