### ISSUE TITLE
how to move a application from one monitor to another?

### ISSUE THREAD

**Issue by ufobat** [material-shell/material-shell#498]
**Is your feature request related to a problem? Please describe.**
 I am aware that there is issue #4 but according to my understanding this is only about navigation with keyboard between 2 monitors.

**Describe the solution you'd like**
Material-shell was recommended to me by a friend, and I really like it a lot. I used to have i3 on my laptop for a while now. Unfortunately I don't understand how a dual monitor setup is supposed to work.

Things that I've dislike are:
* the left side bar is only displayed on one of my monitors (the laptop screen, which isnt my main screen)
* I did not find a way to move a application from one monitor the other.

So without understanding it is hard to make a "Feature Request" but, woudln't it make sense that both monitors act independent, so both have all bars and there should be a way of moving a application from one side to the other?

**Describe alternatives you've considered**
As alternative there must be a way to moving a workspace from one screen to the other, so you could move your app by Super+Shift+W just into a workspace (that happens to be on a different monitor)?

**Comment by PapyElGringo** [comment]
Thanks for the feedback !
> the left side bar is only displayed on one of my monitors (the laptop screen, which isnt my main screen)
You can change your primary display in the GNOME monitor settings and the Vertical Panel should follow the primary display.

>I did not find a way to move a application from one monitor the other.
There was an issue that prevented to move a window across monitor using the keyboard shortcut or overview but it's fixed. And the most advanced workflow in Material shell is the One hand on keyboard / One hand on mouse Workflow and the best way to move window around is to press `Super + Click And Drag Windows` around.

>woudln't it make sense that both monitors act independent, so both have all bars
Material Shell could be indeed compatible to this type of workspaces management unfortunately GNOME (Mutter to be specific) Doesn't provide this type of workspaces. It's currently provide only 2 modes: Single workspace on external monitors ( The one we used in MS) And Workspace span to all monitors (Currently unsupported)

**Comment by Luctins** [comment]
Oh thanks!
That (the <Super + drag> shortcut) also solves my problem on how to drag windows that are "non draggable" really nicely.

**Comment by ufobat** [comment]
With `Super + Drag Window` it seems that I can move an application from the secondary screen to the primary screen. But I can't move it back :-(

**Comment by ufobat** [comment]
When moving it from primary to secontary screen I can see "an empty app" on the secondary screen, but the app remains on the primary screen.

![image](https://user-images.githubusercontent.com/12395249/100478998-405ab180-30ed-11eb-9168-ed45b1286fbe.png)

**Comment by PapyElGringo** [comment]
Are you moving the tab or the window itself ?

**Comment by ufobat** [comment]
I've moved the tab, not the window.

I tried to move the window. Unforunately it does also not work for me. The Primary Monitor is 4k and the second is much smaller. When I move the window with `super + drag & drop` into the 2nd screen, it appears first on the 2nd monitor then, if i move it further to the middle of the 2nd screen, it appears on the outside of the primary screen again. As soon as I release the mouse button it is dropped on the primary screen again.

**Comment by PapyElGringo** [comment]
Could you try the last commit from master? How is your monitors arranged? Relative position between them? Does moving the window with the overview mode is working? What is your gnome shell version?

**Comment by ufobat** [comment]
> Could you try the last commit from master?

Yes. It works with the git version. In both direction. Moving Windows as well as Moving Tabs (tabs only if there is already an application on the destination monitor )

> How is your monitors arranged?

Primary 4k is on the left, smaller laptop monitor on the right

> Relative position between them?

I do not understand what you mean.

> Does moving the window with the overview mode is working?

I dont know the overview mode.

> What is your gnome shell version?

3.36.3

**Comment by real-or-random** [comment]
> Could you try the last commit from master?

I can still reproduce this with 8e01802. When I try to move a tab from the secondary screen to the primary screen or the other way around, I get this "empty" app thing as in the screenshot. This happens most of the time but it sometimes works.

> How is your monitors arranged? Relative position between them?

Primary exactly left of secondary, both with the same resolution, 

> Does moving the window with the overview mode is working?

Yes! That works as a workaround.  

> What is your gnome shell version?

3.38.2

**Comment by PapyElGringo** [comment]
There is now a keybinding available in the settings
