### ISSUE TITLE
Some apps opens on the wrong monitor

### ISSUE THREAD

**Issue by sigboe** [material-shell/material-shell#5]
Affected apps include

Spotify,
dconfeditor,
dosbox,
weather,
gnome texteditor,
gnome logs,
vlc,
cheese

**Comment by PapyElGringo** [comment]
No need to list the apps it's just a missing feature that need to be done asap indeed !

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
