### ISSUE TITLE
Float certain windows, and less important, maybe fix MPV

### ISSUE THREAD

**Issue by StratusFearMe21** [material-shell/material-shell#508]
**Is your feature request related to a problem? Please describe.**
When I try to use Picture-in-picture in Firefox, it doesn't let me move the window. instead it moves both the Firefox window, and the PiP window at the same time. Also, in MPV, you can resize the window but only if it's within the aspect ratio of the video.

**Describe the solution you'd like**
I would love to be able to move the PiP window around the screen and maybe even resize it. And for MPV, It would be nice if the tiling engine didn't let the window overflow to the edges of the screen.

**Describe alternatives you've considered**
Open the windows I need in the desktop, then switch to float mode, the problem with this is that opening new windows requires me to switch back and forth between a tile mode and float mode

**Comment by Luctins** [comment]
Can't seem to reproduce it here, what is your setup (OS, addon version, gnome version, etc)?
I'm on gnome 3.38, PopOS 20.10, Firefox 83.6
``` bash
git rev-parse --short HEAD
7ad7023
```

**Comment by StratusFearMe21** [comment]
Oops, I updated my extension and it fixed the PiP problem, but the MPV problem still persists, the volume controls for MPV are on the right of the screen and I can't access them unless I open a third window. I'm on Ubuntu 20.04, MPV 0.32.0, and gnome-shell 3.36.4

**Comment by StratusFearMe21** [comment]
hold on, I'm trying to upload a gif of my problem to github

**Comment by StratusFearMe21** [comment]
![ezgif com-resize](https://user-images.githubusercontent.com/57533634/101210745-fd945e80-3643-11eb-912f-3eacdb5a8135.gif)

**Comment by PapyElGringo** [comment]
Deprecated issue, probably fixed now. Reopen if you still face it.
