### ISSUE TITLE
Partial loss of control on Krita

### ISSUE THREAD

**Issue by vetu11** [material-shell/material-shell#510]
**Describe the bug**
Krita can't pick up certain controls, including middle mouse, used to move the canvas when switching back to it with hotkeys.

**Expected behavior**
When switching back to Krita it should work perfectly.

**Screenshots**
[Demonstration](https://github.com/material-shell/material-shell/files/5646829/2020-12-05.10-58-53.zip)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.38.2
- Distro: Manjaro
- Steps to reproduce, if applicable:
1. Open Krita
2. Switch out of it with [Super] + D
3. Switch into it with [Super] + A
4. Krita can't pick up certain controls, including middle mouse.

This bug does NOT occur if you switch back to Krita with [Alt] + [Tab] or if you switch clicking in the Material Shell to change tabs/workspaces.

The bug stops if once in Krita you click in the Material Shell interface or use other GNOME things, for example, [Super] then [Super].

**Current commit**
Material Shell version 10.

**Log data**
No log is registered when the bug occurs.

**Comment by PapyElGringo** [comment]
Deprecated issue, probably fixed now. Reopen if you still face it.

**Comment by vetu11** [comment]
I can confirm that it still occurs.
