### ISSUE TITLE
Ratio of the ratio layout not working

### ISSUE THREAD

**Issue by marcoppenheimer** [material-shell/material-shell#511]
## Describe the bug

Unable to change ratio of the ratio layout
Any value does not change the resizing of windows while within ratio layout

Is it possible this is an outcome of the Resize changes? How does one resize windows dynamically in either Grid or Ratio layout? 

## Expected Behavior

Window tiling ratio dynamically changes as the setting is modified

## To Reproduce

- Occurs on: 
    - X.Org
- GNOME Shell 3.36.4
- Distro: Ubuntu 20.04.1 LTS
- `git rev-parse --short` : `98b7e67`
- Steps: 
    - Switch to ratio layout
    - Modify 'Ratio of the ratio layout` setting in Material Shell settings

**Comment by PapyElGringo** [comment]
It's probably related to the resize feature. I guess now that we have resize and once the interaction will be improved we could remove the ratio layout. Why do you want to use the ratio now that you can resize ?

**Comment by marcoppenheimer** [comment]
I just realised now that you resize by dragging the side of the windows, which as you said quite rightly, solves my issue.  
Is there a shortcut for this? 
Either way this issue can be removed, apologies.
