### ISSUE TITLE
Cannot drop app on empty app switcher

### ISSUE THREAD

**Issue by sergefdrv** [material-shell/material-shell#512]
**Describe the bug**
If there is no app in the app switcher on a monitor, drag-n-drop of an app from another monitor there does not work.

**Expected behavior**
It should work even if there is no app on the destination monitor.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.4
- Distro: Ubuntu 20.04

**Current commit**
Latest from version extensions.gnome.org

**Comment by PapyElGringo** [comment]
Deprecated issue, probably fixed now. Reopen if you still face it.
