### ISSUE TITLE
Vertical panel icons are gray scale how to make them colorful?

### ISSUE THREAD

**Issue by codewithcheese** [material-shell/material-shell#523]
**Is your feature request related to a problem? Please describe.**
I'm using the "Application" settings for the Vertical panel icons and its brilliant! So clever how it shows up to 3 applications icons nested like that. However, they are all gray scale. Is that by design? Even the active workspace is gray scale. 

**Describe the solution you'd like**
I would like the Vertical panel icons to be colorful

I am a developer so if you can point me in the right direction I should be able to make a PR either fixing the color or offering it as an option.

**Comment by dels07** [comment]
Same problem, is there any way to keep icon color, now it's looks like washed out & some app sometime harder to identify

**Comment by ab5tract** [comment]
This appears to be a duplicate of #521, resolved in PR #587

**Comment by codewithcheese** [comment]
@ab5tract woooo thank you very much! closing this issue
