### ISSUE TITLE
Waiting forever for application to appear

### ISSUE THREAD

**Issue by real-or-random** [material-shell/material-shell#525]
**Describe the bug**
When I launch an application via the placeholder, and it fails to show a windows (e.g., because it crashes), then Material Shell will just wait forever for a window to appear. The animation keeps spinning but nothing will happen. This tab is broken now, I can't click on it anymore (it's disabled) but I can't recover from this state. 

**Expected behavior**
I don't really now what the best way is to handle this. Maybe a timeout or at least stop waiting when the process is exiting? Or as at last resort, I should be able to close the tab manually. I'm not sure if disabling the tab is even the right thing. (I guess it prevents people from firing up multiple instances if the startup is slow.)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.38
- Distro: Arch Linux

**Current commit**
8e0180204f1f982d9f4181017f562afd8b2b7171

**Log data**
(I don't have logs right now. This should be easy to reproduce. If not, I can provide logs for sure.)

**Comment by ForsakenHarmony** [comment]
Similar issue here, especially while developing something, seems to take like 5 seconds for the window to appear (new independent window gets opened by another program). Disabled the extension and it appeared instantly.

**Comment by real-or-random** [comment]
@ForsakenHarmony This does not sound similar to the issue I describe.

**Comment by AlbinoGeek** [comment]
May very well have a related cause, but I feel this in both cases as well:

- If an application is launched by a place holder, it may take up to four seconds to appear.
- If an application crashed while launching from a placeholder, the animation never resets.

**Comment by ForsakenHarmony** [comment]
> 
> 
> @ForsakenHarmony This does not sound similar to the issue I describe.

Yeah sorry, reading it again now it's different, seems I miread it the first time

**Comment by PapyElGringo** [comment]
Deprecated issue, probably fixed now. Reopen if you still face it.
