### ISSUE TITLE
Can't change focus from/to terminal on click

### ISSUE THREAD

**Issue by jacksongoode** [material-shell/material-shell#527]
**Describe the bug**
I'm unable to change focus of a window by clicking on the window in split view if one of the windows is a terminal and another is a browser (Firefox).

**Expected behavior**
Able to change focus to and from a terminal by clicking on the window.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland?
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.10
- Steps to reproduce, if applicable:
1. Open a browser
2. Open a terminal adjacent to it
3. Switch from fullscreen to split window layout

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Comment by Drewsapple** [comment]
What terminal are you using?
Does this happen with any other combination of windows?
Does this behavior also occur in any other layout modes (half, floating, grid, etc.)?

**Comment by jacksongoode** [comment]
I'm using the Gnome terminal installed with Ubuntu. I just tested it out a bit. It looks like the freezing occurs when the terminal is started in the maximized layout and then switched to column. I think it's more of a terminal issue than the browser.

**Comment by stnoonan** [comment]
This started happening for me as well. Disabling material shell allows click to focus and mouse follows focus to work seamlessly again.

**Comment by velovix** [comment]
I've been having this issue as well. I'm on Ubuntu 20.04 and using Gnome Terminal. In my experience, the other application doesn't necessarily need to be a browser.

**Comment by skeletorXVI** [comment]
I'm using Gnome Terminal on Manjaro on a 32:9 monitor.

I am often switching between three and two split layouts. I noticed that the mouse detection area is actually falsely retained by Gnome Terminal. Either when switching layouts or when the window is moved it retains the original mouse detection area size and position. This is troublesome when trying to copy anything from Gnome Terminal but also provides some insight. The actual mouse is offset absolute to the original position and size. This behavior would also explain why we can't change focus by clicking in Gnome Terminal.

In my experience, it does not matter what kind of applications are running besides Gnome Terminal, so far I've experienced this issue with multiple JetBrains IDEs, Chromium, Firefox, Electron-based apps, Qt-based apps, though browsers seem to be most reliable to trigger this bug.

**Comment by titpetric** [comment]
@PapyElGringo this seems to have been added in >v12, unclear where, but currently the bugfix isn't available for gnome-shell 3.x, I suppose. I need to be running 4.0+ to run v17 (latest release) to take advantage?

**Comment by PapyElGringo** [comment]
Yep indeed the main branch is only compatible for gnome 40+

**Comment by titpetric** [comment]
I guess I'm in luck, it seems v12 does work with gnome-shell 3.38.4, but not 3.36* (updated PopOS to 21.04)
