### ISSUE TITLE
can't change tiling modes

### ISSUE THREAD

**Issue by nibirrayy** [material-shell/material-shell#532]
**Describe the bug**
I just pulled all the latest changes changes from the git and after the pull i cant change tiling modes

**Expected behavior**
Expected to change tiling modes

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Manjaro

**Current commit**
commit: f3e36bebca81943c3f2efdc9a9cf373d7ae89a01

Here is a log of journalctl error
[error.log](https://github.com/material-shell/material-shell/files/5743188/error.log)

I am not uploading all the errors as i am getting same log messages as on the above log file again and again

I also tried changing the tiling mode and got this error
[error2.log](https://github.com/material-shell/material-shell/files/5743211/error2.log)

**Comment by nibirrayy** [comment]
**UPDATE**
I am also not able to move windows between workspaces using the shift+super+W and shift+super+S

I am getting this error
`Dec 26 20:10:33 nibir-vivobookasuslaptoptp420iatm420ia gnome-shell[1344]: Ignoring excess values in shadow definition`

**Comment by PapyElGringo** [comment]
Check the new shortcuts in the settings

**Comment by nibirrayy** [comment]
@PapyElGringo I was using the shell way before and just pulled the commits so the shortcuts were same as it was earlier and i checked the shortcut in settings and they were the same. I even tried reassigning them but it sill didn't work. 

I have now replaced the git version of the shell with the manjaro community package version and now it is working fine

**Comment by PapyElGringo** [comment]
I said that because tin the latest Git version I switched some of the keyboard to the arrow direction key to ease the dual hand workflow. So moving a window around with the keyboard is now Super + UP/DOWN but it's should be visible in the extension settings. If there is another issue we need to dig it up

**Comment by Smaugthur** [comment]
Same thing happened to me, I recently updated the git version (today) and I'm unable to switch between tiling modes even with the GUI (it doesn't make any changes when i select on the list of tiling layouts).

- I played around with the configuration and I only make it work if I **set "Maximize"  mode as the only default mode**, and then **set the others via GUI**, even so It just worked 1 time and then it blocked again.

- 
Another configuration that works to me is set "Maximize" mode as the only default and add "Float" mode via GUI, like so I'm able to switch every times I want, but if you add another mode  it blocks.

**Comment by nibirrayy** [comment]
So this is not a my setup specific bug and can be reproduced. I am currently running the manjaro package of the shell and it is working fine. I am not sure which commit it is but i think it was the release package after some code from someone was merged so it might be due to changes done in last few commit @PapyElGringo

**Comment by PapyElGringo** [comment]
Could you gather some logs when trying to switch layout ?

**Comment by PapyElGringo** [comment]
Sorry got them

**Comment by PapyElGringo** [comment]
You both use gaps?

**Comment by Smaugthur** [comment]
yep, I use gaps, but I reinstalled the extensions and all works fine again.

**Comment by nibirrayy** [comment]
ya @PapyElGringo  i use gaps. and @Smaugthur   I will try it later today if it is working fine
