### ISSUE TITLE
Material shell not launching due to JS ERROR

### ISSUE THREAD

**Issue by GienekWspanialy** [material-shell/material-shell#537]
**Describe the bug**
The extension is not launching after last update of Manjaro switched from X.Org to Wayland. Tried with both community version and the git version from AUR. Also tried with other extensions turned off. Other extensions work as expected.

Can't check on X.Org since GDM just shows me the log-in screen again.

[EDIT]
For some reason switching back to older kernel (5.9.16-1) allowed me to use X.Org. Adding new log below.

[EDIT 2]
I've managed to use X.Org on new kernel (5.10.2-2) also, but the error is the same.

**Expected behavior**
The extension launches.

**To Reproduce**
- Occurs on:
  - [X] X.Org [EDIT]
  - [x] Wayland
- GNOME Shell version: 3.38.2
- Distro: Manjaro Nibia 20.2
- Steps to reproduce, if applicable:
1. Log in.
2. Material shell logo shows up.
3. Material shell not launching. [EDIT 3] The regular GNOME desktop is present.

or

1. Turn off all extensions.
2. Turn on Material shell.
3. Material shell not launching. [EDIT 3] The regular GNOME desktop is present.

I also tried removing first line in the file mentioned in the log, but without success (same error in log).

**Log data**
Output from `journalctl /usr/bin/gnome-shell` on Wayland:
```
sty 02 17:39:05 piotr-pc gnome-shell[15094]: JS ERROR: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data @ /usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js:31

```

[EDIT] Output from `journalctl /usr/bin/gnome-shell` on X.Org:
```
sty 02 18:46:38 piotr-pc gnome-shell[1699]: JS ERROR: too much recursion
                                            DisableIncompatibleExtensionsModule/ExtensionManager.prototype._callExtensionEnable@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/module/disableIncompatibleExtensionsModule.js:23:40
                                            DisableIncompatibleExtensionsModule/ExtensionManager.prototype._callExtensionEnable@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/module/disableIncompatibleExtensionsModule.js:24:30

```
The last line (24:30) is repeated multiple times. After turning off other extensions I get the same error as in Wayland.

**Comment by pedrosousagrilo** [comment]
Think my issue is the same as yours but yours as more details, closing mine https://github.com/material-shell/material-shell/issues/534 .

**Comment by GienekWspanialy** [comment]
@pedrosousagrilo Sorry for the confusion, but I think the issues are different – in my case the regular GNOME desktop works instead of Material shell, in yours the screen is black. I edited the OP to clarify my issue.

**Comment by PapyElGringo** [comment]
@GienekWspanialy your issue is related to a corrupted State. You can reinitialize the state by removing the `material-shell@papyelgringo.state.json` in the `~/.cache` folder and by opening `looking glass` with `alt+f2 then type lg` then copy past `global.set_persistent_state('material-shell-state',new GLib.Variant('s', '{}'))`

**Comment by GienekWspanialy** [comment]
@PapyElGringo Thank you, worked like a charm :+1: Should I leave the issue opened until automatic fix for cases like mine?
