### ISSUE TITLE
Material Shell freezes the gnome in the case of dual monitor

### ISSUE THREAD

**Issue by dziurka** [material-shell/material-shell#543]
**Describe the bug**

After the last system updates (solus is a rolling release distribution) the material shell freezes my entire gnome environment. I am not even able to restart the shell (alt + f2, r), only the mouse cursor works. I even restarted all material-shell settings with dconf, but that didn't help.
The problem appears only with the connected second monitor - no matter if it is connected before logging in or after.

The problem is certainly with material-shell, as I even uninstalled other add-ons, and the gnome with material-shell disabled works fine.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ]  Wayland
- GNOME Shell version: 3.38.2
- Distro: Solus Gnome
- Version of material-shell: extensions.gnome and master

**Log data**
I didn't find anything in the logfile `journalctl /usr/bin/gnome-shell`:

**Comment by caseca** [comment]
I also have this problem
Wayland - GNOME Shell 3.38.2 - Distro Ubuntu 20.04 - Version of material-shell: git master

**Comment by PapyElGringo** [comment]
I'll need some logs or crashdump

**Comment by caseca** [comment]
I will attach here what I found in my
[material_log_dual_monitor.txt](https://github.com/material-shell/material-shell/files/5778051/material_log_dual_monitor.txt)

**Comment by dazWiLLiE** [comment]
Same problem here. 2 monitors, gnome classic (Xorg). Desktop loads, but as soon as i click on some app in the list, everything freezes except the mouse.. which shows me a spinning ball.
[crash.txt](https://github.com/material-shell/material-shell/files/5921107/crash.txt)

**Comment by HaukurPall** [comment]
I've had this issue in the past when I was trying to set the number of workspaces in material-shell. Material shell does not play nicely with some GNOME settings. You can try to set `gsettings set org.gnome.mutter dynamic-workspaces true` and see if it works.

**Comment by caseca** [comment]
> I've had this issue in the past when I was trying to set the number of workspaces in material-shell. Material shell does not play nicely with some GNOME settings. You can try to set `gsettings set org.gnome.mutter dynamic-workspaces true` and see if it works.

Yes it worked, thanks.

**Comment by PapyElGringo** [comment]
That it's interesting!

**Comment by PapyElGringo** [comment]
The fixed workspace length should work properly with external monitors now

**Comment by caseca** [comment]
Is working now, thanks.

**Comment by xendk** [comment]
Sorry to hijack this issue, but there seems to be a few multi-monitor users here, maybe I could coax some to hop into #610 to weigh in whether they use focus follows mouse and keyboard shortcuts?

**Comment by mbablok** [comment]
I have just had such an issue: after installing the extension the UI freezes, logouts and restarts as well. 

My setup is:
GNOME Shell 3.38.4
X11
Manjaro Gnome
Two 4K monitors with scaling 200% (that might be the problem)

 I managed to get it work by:
* turning one monitor of before restart
* logging in, the scaling was back to 100% default
* changing the scaling to 200%
* turning the second monitor on

There is some type error in the logs that might be the culprit
```
cze 18 10:58:08 manjaro gnome-shell[15372]: JS ERROR: Exception in callback for signal: tileable-focus-changed: Error: Wrong type number; float expected. But it's out of range: -Infinity
                                            setTranslation/<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/widget/translationAnimator.js:68:47
                                            setTranslation@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/widget/translationAnimator.js:51:57
                                            startTransition@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/maximize.js:143:38
                                            onFocusChanged@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/maximize.js:77:22
                                            registerToSignals/<.id<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/tilingLayouts/baseTiling.js:84:34
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                            focusTileable@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:339:14
                                            addMsWindow@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWorkspace.js:185:18
                                            setWindowToMsWorkspace@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:676:24
                                            addWindowToAppropriateMsWorkspace@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWorkspaceManager.js:605:14
                                            checkWindowsForAssignations/<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:287:47
                                            checkWindowsForAssignations@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:170:50
                                            setMetaWindowAsWaitingForAssignation@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:153:14
                                            onNewMetaWindow@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:92:21
                                            handleExistingMetaWindow/<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:56:18
                                            handleExistingMetaWindow@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msWindowManager.js:39:36
                                            enable/</<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:91:32
                                            loadRegistry@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js:56:21
                                            enable/<@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:73:25

```

Anyway, thank you for the extension, I have been meaning to play with tiling windows for some time!

**Comment by tflori** [comment]
I upgraded yesterday to Ubuntu 21.04 and installed material shell from the extension page. I've setup 5 workspaces (will try if dynamic works) and have the same issue when connecting a second Monitor: it freezes.
