### ISSUE TITLE
Bugs Bugs Bugs

### ISSUE THREAD

**Issue by comod** [material-shell/material-shell#561]
I figured out a lot of Issues after using this for a week and now i cant even use it any more, because Its totally broken!
I am very disappointed!!

Crititcal:
- Second Screen go back to gnome default (no material shell), after using Floating Layout on primary screen and reboot
  - more precise: Material-Shell is totally broken (windows in disposition to mousepointer (hard to describe, sorry: i mean i cant click on a bookmark for example, i must point my mouse top: -50px, left: -10px round about to hit what i want to hit, even after restart material shell))

High:
- Dialogs pops up under other window
- After Gnome (ALT+F2, r) or PHPStorm Restarts reorder positions of phpstorm (moves windows around everywhere)
- Drag n Drop to antoher Screen doesnt work every time

Low:
- Fokus ("White"-Window) not set (Its darken intead) (after leaving a "last window" after using two or more)
- TaskBarMenu-Popout Menu Position wrong (top: +10px too much)
- Sometimes crash with restart (Reason unknown)

**Comment by comod** [comment]
My other user is still working. How can i reset a session?

**Comment by comod** [comment]
Ok Figured out how to reset:
`rm ~/.local/share/gnome-shell/material-shell-state-cp`

**Comment by comod** [comment]
Even after Rest State and Restart i had a new issues with phpstorm (i dont know why PHPStorm is such a troublemaker). I couldnt work with that window at all. No resize of internal  toolwindows or something else. And the best: if i click something  in the top menubar it appears on the other screen somewhere. What the Heck is going on here??? Again: my other "Office" user works well all day long without any issues. Before this issue hapenned i was logged in into a awesomewm session. Maybe thats the reason. Some side effects or something....

what can i do to reset to start over with a fresh state?

Please help. Its really frustrating now

**Comment by PapyElGringo** [comment]
Hey @comod Sorry for the troubles to reset the state you have to open Looking glass by typing `Alt+ F2` then type `lg` then copy past `global.set_persistent_state('material-shell-state',new GLib.Variant('s', '{}'))`

**Comment by PapyElGringo** [comment]
@comod join me on Discord tomorrow if you are still stuck so we can troubleshoot this
