### ISSUE TITLE
Allow to see wallpaper when you are selecting a program to launch

### ISSUE THREAD

**Issue by dgmvecuador** [material-shell/material-shell#564]
**Is your feature request related to a problem? Please describe.**
No related to a problem.

**Describe the solution you'd like**
When you click in "+" button for search or select for an application to launch, the wallpaper could be shown in the background, I think this could be an option.

**Describe alternatives you've considered**
Wallpaper are not show anywhere, I not sure if there are another place or situation to be implemented.

**Comment by AlbinoGeek** [comment]
The wallpaper does show when you click `+` on the top/bottom or left/right bars...

You have to turn off `Blur Wallpaper` which breaks it entirely, and shows black instead.

**Comment by dgmvecuador** [comment]
Thank you, the options is not very intuitive, maybe it should be more clear
