### ISSUE TITLE
Delete Hotkeys

### ISSUE THREAD

**Issue by AlbinoGeek** [material-shell/material-shell#565]
**Is your feature request related to a problem? Please describe.**
I cannot delete or disable hotkeys.

**Describe the solution you'd like**
ESC or some other invalid hotkey should set the hotkey disabled.

**Describe alternatives you've considered**
I have tried to assign multiple actions to the same hotkey to force un-assign, however, this too failed.

Material Shell instead issued me a useless configuration where every hotkey was assigned the same key.

**Comment by AlbinoGeek** [comment]
**Why?**
Super+A and Super+D used to move windows between workspaces.
But you broke that in an update. (changed this hotkey to "focus window".)

You then assigned Super+Left and Super+Right to this function,
Which then means there is no way to reposition windows within a workspace anymore.

(Opening another issue about this ^)

**Comment by HaukurPall** [comment]
I would like to be able to disable/delete hotkeys

**Comment by kcpr** [comment]
@HaukurPall , I'm pretty sure You can do that: in settings just double-click the hotkey entry like You'd like to set it and hit <kbd>Backspace</kbd>. Also - You can edit or disable hotkeys in "dconf editor" (first You may have to manually assign it in the extension settings so an entry show up in "dconf editor").

**Comment by EpsilonKu** [comment]
@kcpr Is it possible make it normally on extension setting?

**Comment by kcpr** [comment]
@EpsilonKu , I'm sorry for the late answer - I haven't seen Your comment before. If I understand You correctly: yes, at least it works for me. Just as I described in the previous comment (hitting <kbd>Backspace/</kbd> solves the issue).

**Comment by Compro-Prasad** [comment]
@kcpr Can this issue be closed?

**Comment by AlbinoGeek** [comment]
Closing at request of @Compro-Prasad
