### ISSUE TITLE
Hotkeys wrong in README

### ISSUE THREAD

**Issue by AlbinoGeek** [material-shell/material-shell#566]
Since the hotkeys were updated without warning users [ see #565 ] ...

I went and checked the documentation:
https://github.com/material-shell/material-shell#hotkeys

And couldn't help but notice that it's completely wrong now.

---

Many of the default hotkeys were changed in one of the last few versions without so much as a whisper of notice.

**Comment by smythed** [comment]
I have submitted an update to keyboard shortcuts in README.
