### ISSUE TITLE
New workspace suggestion: Favorites

### ISSUE THREAD

**Issue by nununoisy** [material-shell/material-shell#57]
GNOME has a favorites category. In the vanilla shell the favorited apps show up on the dock. Since there is no dock, and apps can still be favorited, would it be possible to add a category that pulls from favorited apps?

**Comment by PapyElGringo** [comment]
I think this is doable and maybe a good idea. There is a lot of discussions on this categories lately and we should take time to prepare a good solution for them. This should be part of the discussion

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **IS** deprecated.
