### ISSUE TITLE
Click window to focus behaving unexpectedly

### ISSUE THREAD

**Issue by Omegastick** [material-shell/material-shell#570]
**Describe the bug**
With any layout other than maximize, they boundaries for clicking on windows to focus them seems to be wrong.

Opening 3 terminals in the "half" layout gives the layout in the screenshots section. Clicking in the top-left quadrant of the screen selects terminal B, the top-right and bottom-right terminal A, and the bottom-left does nothing (note it's impossible to select terminal C).

However, closing and recreating the windows gives me a different result. This time wherever I click terminal A is selected. Closing and recreating them again gives a different result.

**Expected behavior**
Clicking on a window should select it.

**Screenshots**
![terminals](https://user-images.githubusercontent.com/17452111/105736721-02cba680-5f2d-11eb-9f2e-d6e2e6c7b85e.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Open 3 terminals the "half" layout.
2. Click on each of the terminals and see which window is selected.

**Current commit**
Latest version from extensions.gnome.org.

**Log data**
No log output while reproducing the bug.

**Comment by comod** [comment]
You can reproduce this easylie just with 2 terminals and the tiling layout doesnt matter. This is a very annoying bug :-D . I installed therfore a another terminal (which is better anyhow as the default one). It seems this only happens with the default (gnome?) terminal. maybe it wasnt "designed" to be a multi-instance programm (i know this sounds ridiculous) (but try to open the terminal via super (programm launcher) - if you try to open more than one terminal, you cant do that, it opens the open one (per workspace) - so maybe the default gnome behaivour is taken over control here. but this is only a guess

**Comment by comod** [comment]
BTW everything works fine if you use Keyboard-Shortcuts. Only the Mouse-Events doesn't work well in many Situations

**Comment by comod** [comment]
This also happens with Rxvt-Terminal. I can get Focus to these "buggy windows" then only if i click on the first window (eg Chrome) in the Workspace. If i use Kitty everything is good. I dont know what Rxvt and default Ubuntu Terminal has together with this Bug, but hopefully helpful in any way.
