### ISSUE TITLE
gnome crashing if first workspace windows closed

### ISSUE THREAD

**Issue by sainad2222** [material-shell/material-shell#578]
**Describe the bug**
Gnome crashing if all first workspace windows are closed while other workspaces are open

**Expected behavior**
first workspace should be replaced by bottom workspaces

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. open few windows in first workspace
2. open some in second too
3. now close all windows in first workspace

**Current commit**
latest

**Log data**
nothing

**Comment by PapyElGringo** [comment]
probably related to #535
