### ISSUE TITLE
Way to close an app entirely

### ISSUE THREAD

**Issue by fabdarice** [material-shell/material-shell#593]
**Is your feature request related to a problem? Please describe.**
Today, with material shell, when I press SUPER+Q, it visually close the application.
However, it seems like the process still runs in the background (ps aux shows the app still).
At least, the following app stays up-and-running:
- Chrome/Brave browser
- Slack
- Telegram
- Signal
- SPotify

**Describe the solution you'd like**
A simple way to close and kill processes and applications

**Describe alternatives you've considered**
N/A

**Comment by Luctins** [comment]
Is there any common thread between these applications? (e.g. all being electron based)
For me `<Super+Q>` kills applications just fine, including spotify. 
It goes from having a few processes to a single suspended one (no real "live" processes, `ps -A | grep spot` returns nothing)

**Comment by PapyElGringo** [comment]
Deprecated issue, probably fixed now. Reopen if you still face it.
