### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by grubeli** [material-shell/material-shell#595]
**Is your feature request related to a problem? Please describe.**
Launching new application via keyboard, for example Super + Return/Enter to launch a terminal, etc.
or Super + T to open new tab ready to type new app name.

**Describe the solution you'd like**
Ability to customize bindings would be amazing, similar to how we can do it in Qtile.
Or at least add keybinding for opening new tab.

**Comment by grubeli** [comment]
Just noticed that there is "bindings.gschema.xml" with Super + x to open a new tab, that's good.
Is there a way to customize bindings on a running build?

**Comment by PapyElGringo** [comment]
From the extensions settings?

**Comment by grubeli** [comment]
I just realized that we are still Gnome and can use gnome keybindings to launch an app,
https://gist.github.com/fwilhe/2f1f1878113883535156e230cba62bed
