### ISSUE TITLE
Homebrew package support

### ISSUE THREAD

**Issue by kwrooijen** [material-shell/material-shell#598]
**Is your feature request related to a problem? Please describe.**
Not all distro package managers are supported.

**Describe the solution you'd like**
If material-shell is available on [Homebrew](https://brew.sh/) then any distribution can make use of it.

**Describe alternatives you've considered**
...

**Comment by PapyElGringo** [comment]
Homebrew is for MacOS no?

**Comment by kwrooijen** [comment]
Homebrew is both MacOS and Linux. I use it to install tools that I either can't find in apt or are outdated.

**Comment by PapyElGringo** [comment]
We support only Gnome Extension official install process and Git install for convenience
