### ISSUE TITLE
Column layout from README.md does not exist

### ISSUE THREAD

**Issue by mkevac** [material-shell/material-shell#627]
The column layout mentioned in README.md does not exist.

![image](https://user-images.githubusercontent.com/123544/112509942-0307e700-8da2-11eb-8d76-f5fc33a581ff.png)

I expected to see "Column" layout in the list of layouts.

```
 marko  manjaro  ~  %  pamac list | grep material
gnome-shell-extension-material-shell     12-3                        community  562.3 kB
```

I think that README.md should be fixed.

**Comment by sgraf812** [comment]
I think what you are looking for is the Simple horizontal layout, but it seems you already figured that out. Maybe open a PR that fixes the README?
