### ISSUE TITLE
AppCard maximum width

### ISSUE THREAD

**Issue by derixithy** [material-shell/material-shell#63]
The Categorie cards on the desktop can get to wide on porttraid screens and overlap.
See screenshot for an example
![Screenshot from 2019-07-13 20-02-46](https://user-images.githubusercontent.com/1281878/61175079-d306b900-a5a9-11e9-80ce-6dfa7122c6db.png)

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **IS CONFIRMED** be fixed.
