### ISSUE TITLE
Material-Shell Extension Settings hangs

### ISSUE THREAD

**Issue by johnbarney** [material-shell/material-shell#633]
Before I start, there's a lot of negativity in some of these bug reports. Thank you very much for taking the time to create this extension. I was looking for a nice middle ground between Gnome and i3 and this is exactly what I'm looking for.

**Describe the bug**
When I open Extensions -> Material Shell Settings the window hangs for 15-20 seconds. Some options that I attempt to configure (Color for example) will cause the freeze again.

**Additional Detail**
I've disabled all System76 extensions except PopShop and System76 Power and disabled the majority of the built-in keymappings in Pop_OS! to make sure Material Shell is being conflicted with as little as possible.

Normally I'm decent at troubleshooting but these stacktraces are a bit beyond me.

**Expected behavior**
I expect 0-1 second delay before the UI is ready to use.

**Screenshots**

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.38
- Distro: Pop_OS! 20.10
- Steps to reproduce, if applicable:
1. Unsure what I did to cause. Did not happen on clean install.
2. Open Extensions
3. Open Material Shell Settings

**Current commit**
Installed from gnome-extensions site.

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:

pastebin.com/m3qjgkuR

**Comment by PapyElGringo** [comment]
Thanks for your feedback. It's seem that every time Material shell try to tile windows it's try to tile a lot of window that is already destroyed.

Does it worked previously?

**Comment by johnbarney** [comment]
Yes it was working well when I first installed, but performance has been decreasing steadily. My best guess is every window I open and quit is still attempting to be tiled even after reboot. Is there a way I can clear this?

**Comment by PapyElGringo** [comment]
Try reset the state https://github.com/material-shell/material-shell#reset-material-shell

**Comment by johnbarney** [comment]
Running just the looking glass reset command gave me r(0) = undefined so I'm not entirely sure if that worked. I went ahead and reset with dconf and the UI does feel faster but the settings menu still hangs.

**Comment by johnbarney** [comment]
So after some troubleshooting, including installing Ubuntu 20.10 vanilla and just installing extensions and material-shell (no updates) and I found the same exact behavior. However I also discovered that the extensions settings window is only frozen if the extension is turned on. Turn off the extension and it works just fine. Maybe this window class should be excluded by default?

**Comment by PapyElGringo** [comment]
Thanks for digging up. How do you open the extension settings ? From the extension app or Gnome Tweaks?

**Comment by johnbarney** [comment]
Extensions App

**Comment by PapyElGringo** [comment]
Since the extension settings will be rewrited to Gtk4 with Gnome 40 we will wait to check the behavior there before digging more. In the mean time you can try with Gnome tweaks if it's the same behavior.

**Comment by johnbarney** [comment]
Understood. As a workaround I've just added the window class to the exclude list and that seems to work just fine. Thanks for the help and best of luck with the Gnome40 upgrade!

**Comment by PapyElGringo** [comment]
Thanks !
