### ISSUE TITLE
Mouse pointer is slightly shifted downwards (on the same window or neighbour)

### ISSUE THREAD

**Issue by prafiny** [material-shell/material-shell#636]
**Describe the bug**
When using Half layout, pointing on small windows is not accurate (you have to aim slightly up to click on a given element)

**Expected behavior**
Click/hover should be aligned with graphical environment

**Screenshots**
N/A

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36.8
- Distro: Ubuntu 20.04.2 LTS
- Steps to reproduce, if applicable:
1. Switch to Half layout
2. Open 4 windows
3. Try to click on elements of the small windows

**Current commit**
version 12 from extension.gnome.org

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
None

**Comment by PapyElGringo** [comment]
Could you try with the git version on the Main branch?

**Comment by prafiny** [comment]
I just installed it via git (master branch it is) and the bug doesn't seem to show up. I'll test a few hours and keep you informed !

**Comment by prafiny** [comment]
Seem to be ok on the main branch, I'm closing :)
