### ISSUE TITLE
Flickering windows and screens on gnome40 branch

### ISSUE THREAD

**Issue by prafiny** [material-shell/material-shell#648]
**Describe the bug**
At some point, windows start to bug (might be related to cache: automatically switching from one tab to the other on firefox, displaying past of a gnome-terminal window, …)

**Screenshots**
If unclear, I will try to produce a screencast

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 40.0.0
- Distro: Archlinux
- Steps to reproduce, if applicable:
1. Open several windows (for instance firefox with several tabs)
2. Browse/use "half" layout to use another app on side

**Current commit**
2d9ec55

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
No related output

**Comment by isaacsando** [comment]
I'm seeing the same thing. Same setup as @prafiny.

**Comment by zachbutton** [comment]
I'm seeing this on both X.Org and Wayland.

**Comment by PapyElGringo** [comment]
Any way to reproduce?

**Comment by prafiny** [comment]
I've pulled your recent changes, my "To Reproduce" is still relevant on my setup (opening several firefox tabs, opening two terminals, make some commands, switching ff tabs and there it flickers)

**Comment by PapyElGringo** [comment]
Could you make a screencast?

**Comment by prafiny** [comment]
https://drive.google.com/file/d/1DV-GuTWHHB2ai1JvCprbKiSGmUKoX7P8/view

**Comment by PapyElGringo** [comment]
Could you try last commit?

**Comment by prafiny** [comment]
Cannot reproduce for now ! I'll let a few days to be sure and we can close if @isaacsando and @zachbutton confirm it is fixed :)

**Comment by isaacsando** [comment]
@prafiny @PapyElGringo I'm having trouble compiling this so I can confirm it's fixed. I'm running Arch 5.11.16 on Xorg and doing the following:
- git clone --branch gnome40 https://github.com/material-shell/material-shell.git
- cd material-shell
- make install

I get the following error:
```
./scripts/install.py
Installing dependencies...
Command '['npm', 'install', '--silent']' returned non-zero exit status 1.
Failed to install dependencies
make: *** [Makefile:51: install] Error 1
```

I've also tried installing using a PKGBUILD as follows (includes the latest commit 7636f12 from gnome40 branch):
```bash
# Maintainer: Henri van de Munt <(firstname) @ gmail.com>
pkgname=gnome-shell-extension-material-shell-git
pkgver=12.r12.7636f12
pkgrel=1
pkgdesc="GNOME Shell Extension Material Shell"
arch=('any')
url="https://github.com/PapyElGringo/material-shell"
license=('GPL')
depends=('gnome-shell')
makedepends=('git' 'npm' 'python2')
optdepends=('plata-theme: gtk and shell theme'
            'tela-icon-theme-git: icon theme'
            'ttf-roboto: font')
groups=('gnome-shell-extensions')
source=('git+https://github.com/PapyElGringo/material-shell.git#branch=gnome40')
md5sums=('SKIP')

pkgver() {
    cd material-shell
    printf "%s" "$(git describe --long --tags | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

build() {
    cd material-shell
    npm install --cache "${srcdir}/npm-cache"
    make compile
}

package() {
    cd material-shell
    install -d $pkgdir/usr/share/gnome-shell/extensions/material-shell@papyelgringo/
    cp -r dist/* $pkgdir/usr/share/gnome-shell/extensions/material-shell@papyelgringo/
}
```
I run makepkg and get this error (I can attach the full log if you'd like):
```
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/sass_types/boolean.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/sass_types/color.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/custom_importer_bridge.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/create_string.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/sass_types/error.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/sass_context_wrapper.o] Error 1
npm ERR! make: *** [binding.target.mk:129: Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/isaac/Documents/aur/gnome-shell-extension-material-shell-git/src/material-shell/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.11.16-arch1-1
npm ERR! gyp ERR! command "/usr/bin/node" "/home/isaac/Documents/aur/gnome-shell-extension-material-shell-git/src/material-shell/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/isaac/Documents/aur/gnome-shell-extension-material-shell-git/src/material-shell/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.0.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/isaac/Documents/aur/gnome-shell-extension-material-shell-git/src/npm-cache/_logs/2021-04-28T16_47_15_253Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
```

Any thoughts on what I'm doing wrong?

**Comment by PapyElGringo** [comment]
Please open another issue for that @isaacsando but you should use 'make install' it's seem that you miss 'npm' try to install it

**Comment by ddemidov** [comment]
I have the same issue as @isaacsando, on arch linux as well. The gnome40 branch did compile just before this commit so I don't think it is system-related.

**Comment by PapyElGringo** [comment]
Well in this case can you may try the last commit with a bump of the node-sass version?

**Comment by ddemidov** [comment]
I was wrong about being able to compile the previous commit, the compilation now breaks for it as well. This seems to be unrelated to this repo, because I am not able to `npm install node-sass` in a clean folder as well.

**Comment by ddemidov** [comment]
Probably related: https://github.com/sass/node-sass/issues/3077

**Comment by ddemidov** [comment]
Installing [`nodejs-lts-fermium`](https://wiki.archlinux.org/index.php/Node.js_) solves the problem with compilation for me, and it makes the material shell useable again on gnome 40. Thanks!

**Comment by isaacsando** [comment]
@ddemidov Thank you for finding this! I was able to install nodejs-lts-fermium as I too had v16.0.0 of node and I'm now able to compile. material-shell is usable again, and oh how I've missed it :) Thanks for the fix @PapyElGringo !
