### ISSUE TITLE
Material Shell is incompatible with Gnome 40.1

### ISSUE THREAD

**Issue by dextersgenius** [material-shell/material-shell#659]
**Describe the bug**
Unable to enable Material Shell on Gnome 40.1 - extension is incompatible

**Expected behavior**
Extension should be compatible.

**Screenshots**
![image](https://user-images.githubusercontent.com/1624052/117733699-1c77cc00-b246-11eb-868a-b34dcd9e2d58.png)

**To Reproduce**
- Occurs on:
  - [x] Wayland
- GNOME Shell version: 40.1
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. yay -S gnome-shell-extension-material-shell-git
2. gnome-session-quit
3. < log back in >
4. gnome-extensions enable material-shell@papyelgringo

**Current commit**
640f48e

**Log data**
< no logs generated >

**Comment by Nepherim** [comment]
Note there is work going on for Gnome 40 compatibility. Ref: https://github.com/material-shell/material-shell/tree/gnome40

**Comment by augugusto** [comment]
the gnome 40 branch has now meen gerged into main. please remember to close the issue if solved

**Comment by abooij** [comment]
Did #632 fix this, @dextersgenius?

**Comment by PapyElGringo** [comment]
The 40 compatibility has been merged into `main`
