### ISSUE TITLE
Add support for overlayed windows

### ISSUE THREAD

**Issue by cdmistman** [material-shell/material-shell#66]
Currently, overlayed windows are not properly overlayed over other windows.

This is seen when using guake: 
- "maximize" layout: opens in new window
- "grid" layouts: opens in new sub-grid

The same happens when using GNOME's screenshot tool.

**Comment by nununoisy** [comment]
Would this also apply to the Firefox update prompt?

**Comment by PapyElGringo** [comment]
Can you check the last commit and give me feedbacks?

**Comment by donnellycolton** [comment]
Guake still gets opened as its own window instead of overlay

![Screenshot from 2019-07-17 20-30-24](https://user-images.githubusercontent.com/23486351/61420740-f004fa00-a8d1-11e9-841a-adaddebe9124.png)

**Comment by nununoisy** [comment]
The Firefox update prompt now displays correctly in the latest commit

**Comment by donnellycolton** [comment]
Prompts seem to be better -- in JetBrains IDEs, the "Tip of the Day" shows up in the same workspace (though not center-screen, the top left corner of the prompt is aligned with the center of the display, excluding material-shell's bars).

I'm not familliar with GNOME extensions but I might dig around later and see if there's a PR I can make to fix this issue.

I'm also getting an issue where the status area of the left bar disappears after waking from hibernate. I'm not sure if this is a material-shell problem or if it lies with GNOME's handling of hibernate. Also not familiar with GNOME extension lifecycles so I couldn't debug it quickly

**Comment by donnellycolton** [comment]
Interesting... in baseTiling you seem to be placing the dialog window in the center of the workarea, but I still get the alignment issue. I can't find anywhere else that might be cause the dialog to be off-center.

**Comment by PapyElGringo** [comment]
Can you share a screenshots ? And for guake We won't be able to handle it soon.

**Comment by ZeroAurora** [comment]
I don't know if it's related, but many kinds of overlays can't work correctly
for example, in Braker Browser (flatpak edition)
![2019-07-30 10-59-46 的屏幕截图](https://user-images.githubusercontent.com/25359455/62097460-71d52a00-b2b9-11e9-9c9a-e8844b680147.png)

**Comment by PapyElGringo** [comment]
Since https://github.com/material-shell/material-shell/commit/15183774f2b393a32bdbbc69fc244f6e62d87bd9 You can now add some window class excluded from tiling in the settings which should allow you to make work your overlayed windows

**Comment by vinayak-mehta** [comment]
@PapyElGringo Are there any docs on how to find the window classes for applications we want to exclude from tiling?

Thank you for building this! It's really awesome!

**Comment by vinayak-mehta** [comment]
Nvm found it! https://superuser.com/a/142451/402144

On X11, enter the `xprop WM_CLASS` command on the terminal, and then click on any window to find its class.

Thank you again for this awesome project!
