### ISSUE TITLE
Search panel text input affected by "panels size" setting

### ISSUE THREAD

**Issue by kellya** [material-shell/material-shell#669]
**Describe the bug**
Altering the panels size in material shell settings changes the search box display size in the search panel

**Expected behavior**
Changes to panel size should not impact the text box

**Screenshots**
Search panel with panels size set to 24 (the search is tiny)
![Screenshot from 2021-05-25 10-12-50](https://user-images.githubusercontent.com/168120/119515980-5667c880-bd44-11eb-8fbd-b28556a19bf3.png)

Search panel with panels size set to 48 (Input looks normal)
![Screenshot from 2021-05-25 10-12-38](https://user-images.githubusercontent.com/168120/119515999-5bc51300-bd44-11eb-80c6-62eccc58bd95.png)

**To Reproduce**
- Occurs on:
  - [X] X.Org
  - [ ] Wayland
- GNOME Shell version: 40.1
- Distro: Fedora 34
- Steps to reproduce, if applicable:
1.  Open material shell settings
2.  Change the "Panels size" setting to something small (I used 24)
3.  Hit the super key/Click the magnifying glass icon in the upper left to bring up search panel
4.  Observe teeny tiny search box input with "Text to search" spewing out of the top and bottom

**Current commit**
Output from `git rev-parse --short HEAD`: `d970eb6`

**Log data**
There are no logs associated with this as it is a display/formatting issue

**Comment by zoitrok** [comment]
Seems like I defaulted to 48 (probably from my previous gnome settings) where I experienced the same issue. In lack of good Xorg scaling I've tweaked my fonts to 1.25x size. I experience the same, but ramping up the panels size to 60 seems to be a workaround for me.
