### ISSUE TITLE
Unable to set Primary UI Color

### ISSUE THREAD

**Issue by SethGrisham** [material-shell/material-shell#671]
**Describe the bug**
When changing the Primary UI Color in Gnome extensions, the box will change but it does not persist when extensions is reloaded. The primary UI color does not change outside of the extensions program.

**Expected behavior**
Changing the primary UI color in gnome extensions should change it everywhere else and also be persistent.

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 40.1
- Distro: OpenSUSE Tumbleweed
- Steps to reproduce, if applicable:
1. Open Gnome Extensions for Material Shell
2. Change Primary UI color
3. Exit and reopen Gnome extensions for Material shell
4. Neither the setting or the UI color have changed.

**Current commit**
f44335d

**Comment by TheCultLeader666** [comment]
still a problem

**Comment by bree29** [comment]
Still an issue here as well

```
System:    Host: msi Kernel: 5.10.59-1-MANJARO x86_64 bits: 64 Desktop: GNOME 40.3 
           Distro: Manjaro Linux 
Machine:   Type: Laptop System: Micro-Star product: GF65 Thin 9SEXR v: REV:1.0 
           serial: <superuser required> 
           Mobo: Micro-Star model: MS-16W1 v: REV:1.0 serial: <superuser required> 
           UEFI: American Megatrends v: E16W1IMS.108 date: 12/04/2019 
Battery:   ID-1: BAT1 charge: 48.8 Wh (100.0%) condition: 48.8/51.3 Wh (95.1%) 
CPU:       Info: Quad Core model: Intel Core i5-9300H bits: 64 type: MT MCP cache: L2: 8 MiB 
           Speed: 900 MHz min/max: 800/4100 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 
           5: 901 6: 901 7: 901 8: 900 
Graphics:  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel 
           Device-2: NVIDIA TU106M [GeForce RTX 2060 Mobile] driver: nvidia v: 470.63.01 
           Display: x11 server: X.org 1.20.13 driver: loaded: modesetting,nvidia 
           resolution: <missing: xdpyinfo> 
           OpenGL: renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 470.63.01 
```
