### ISSUE TITLE
No property margin_left on GtkStack

### ISSUE THREAD

**Issue by Gubard** [material-shell/material-shell#674]
Error: No property margin_left on GtkStack

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:45:40
  _init@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/prefs.js:121:26
  buildPrefsWidget@/usr/share/gnome-shell/extensions/material-shell@papyelgringo/prefs.js:27:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
- Occurs on:
  - Wayland
- GNOME Shell version: 40.1.0
- Distro: Fedora 34 (Workstation Edition)
- Steps to reproduce, if applicable:
1. Open Extensions
2. Setting  Material Shell
3. Technical Details

**Comment by PapyElGringo** [comment]
How did you installed MS?

**Comment by flofeld** [comment]
Duplicate of #667

**Comment by Gubard** [comment]
sudo dnf install gnome-shell-extension-material-shell


пн, 7 июн. 2021 г. в 12:48, PapyElGringo ***@***.***>:

**Comment by Gubard** [comment]
I removed the old version and installed it from the git. That helped.
