### ISSUE TITLE
Inactive window gets dimmed

### ISSUE THREAD

**Issue by nizamsp** [material-shell/material-shell#723]
**Describe the bug**
Inactive window gets dimmed on an ultrawide monitor. Couldn't see the content of the inactive window easily

**Expected behavior**
A clear and concise description of what you expected to happen, and how the actual outcome differs.
There should be a way to disable the out of focus window dimming. It's quite annoying. Everything else works super good.

**Screenshots**
![Screenshot from 2021-10-11 18-13-00](https://user-images.githubusercontent.com/1537832/136791831-7f1778c6-005c-4d86-817e-ae810e78ff9e.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Step 1
2. Step 2
3. ???
4. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `640f48e`

**Log data**
[output.txt](https://github.com/material-shell/material-shell/files/7322441/output.txt)

Output from `journalctl /usr/bin/gnome-shell`:
```
example log data in output.txt
```

**Comment by hakimzulkufli** [comment]
Sounds like you have "Focus effect" option set to "default". Change to "none" instead.
