### ISSUE TITLE
Unable to set some key-bindings

### ISSUE THREAD

**Issue by josephmahede** [material-shell/material-shell#748]
**Describe the bug**
When I try to set a keybinding to "Ctrl + Super + Left". It always only registers "Ctrl L + Super" and leaves the third key stroke out.

**Expected behavior**
Expectation: Actually registering the keys I typed.

**Screenshots**
![Screenshot from 2021-12-21 16-57-13](https://user-images.githubusercontent.com/37513596/147016851-62847ed8-662a-4e3a-bfaa-f974d5ac03ad.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 41.2
- Distro: Fedora 35
- Steps to reproduce, if applicable:
1. Set the hotkeys from Extensions -> Meterial Shell settings

**Current commit**
Installed from gnome extensions website

**Log data**
N/A

**Comment by PapyElGringo** [comment]
Should be fixed on master
