### ISSUE TITLE
Material shell reproducibly freezes

### ISSUE THREAD

**Issue by arsdragonfly** [material-shell/material-shell#755]
**Describe the bug**
Material shell reproducibly freezes after the following steps

**To Reproduce**
1. on a new workspace, open gnome-terminal and launch glxgears from it
2. close gnome-terminal, which will kill glxgears
3. the whole desktop freezes

**Comment by PapyElGringo** [comment]
I can't reproduce it are you on the last commit?

**Comment by arsdragonfly** [comment]
Yes. It's not reproducible on "maximize" layout, but reproducible on "half" layout.

**Comment by PapyElGringo** [comment]
Could you confirm it's fixed?

**Comment by arsdragonfly** [comment]
Yes it's been fixed. Please close the issue.
