### ISSUE TITLE
Can't change keybindings on French keyboard

### ISSUE THREAD

**Issue by Okanda** [material-shell/material-shell#756]
**Describe the bug**
The killer combinason AWSD to navigate is bad on an azerty keyboard and I can't change keybindings. 
If I go to extension options-->hotkeys and want to change, for example, Super+Q to focus to left windows it closes the windows (the keybinding Super+Q is applied).  The same occurs with Super+W, . . . 

**Expected behavior**
When Super+Q is used in hotkeys options, the keybinding have to be change to Super+Q. 

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.41
- Distro: OpenSuse TW
- Steps to reproduce, if applicable:
1. Launch extension options
2. Hotkeys tab
3. clic to change a keybindings
4. Keybindings is not modified but "appalied"

Hope my english is not to bad. French guy inside :)

Than you

**Comment by PapyElGringo** [comment]
I just pushed a fix!
PS: Material Shell est made in France :+1:

**Comment by Okanda** [comment]
Yes, trop bien. Ça aurait été plus facile à expliquer en français ^^

Par contre je ne crois pas que ça ai marché. J'ai toujours eu le même problème après mise à jour de l'extension (via le site gnome-extension). Est-ce que ça peut venir d'un de mes réglages de Gnome? 
J'ai contourné simplement le problème en donnant des raccourcis à une touche (genre QZSD) avant de refaire les raccourcis en rajoutant la touche Super. 

En tous cas merci pour l'extension. Je n'arrive plus à m'en passer!

**Comment by PapyElGringo** [comment]
Normalement ça devrait être bon, quand tu change de hotkey tu as bien une `dialog` qui s'ouvre pour saisir les hotkeys? Hésite pas a rejoindre le discord pour creuser si ça marche toujours pas

**Comment by Okanda** [comment]
Oui ça m'a demandé si j'autorisais l'extension à "contrôler" (je ne me rappelle plus du terme exact) les raccourcis clavier et une dialog apparaît. 
Mais si par exemple je veux Super+W pour changer de bureau et que ce raccourci est déjà pris par "changer d'applis" je ne peux pas rentrer le nouveau raccourci. Ça change d'application.
