### ISSUE TITLE
Toggleable fullscreen mode for an app

### ISSUE THREAD

**Issue by stilvoid** [material-shell/material-shell#757]
**Is your feature request related to a problem? Please describe.**
When working with multiple applications open, I would like to be able to temporarily maximise one window while I perform a task in it, without destroying the layout so that when I un-maximise the window, everything goes back to how it was before.

**Describe the solution you'd like**
A keyboard shortcut that maximises the currently focused window.
When I press the shortcut again while the window is maximised, the layout is restored to what is was before maximise.

**Describe alternatives you've considered**
Changing the layout to maximise and then changing it back does not guarantee your layout will return exactly as it was before.
I could have hotkeys for various layout modes and switch that way but that's a different mental model and much less convenient than toggling a temporary fullscreen mode.

**Comment by PapyElGringo** [comment]
What about `Super+F`?

**Comment by stilvoid** [comment]
Yep, `Super+F` would definitely be my keybinding of choice. I've recently come to Material Shell from [i3](https://i3wm.org/) and the behaviour I described above is exactly what `Super+F` does in i3 :)

**Comment by PapyElGringo** [comment]
Oups it's already possible to set it in the Gnome settings `toggle fullscreen mode` and I thought it was default

**Comment by stilvoid** [comment]
I tried setting this but it just doesn't seem to work.

Example:
* I have two firefox windows open in a Ratio layout.
* I press `Super+F` which is assigned, via Gnome settings, to `toggle fullscreen mode`
* The Firefox window flickers for a moment but nothing else happens.

Note: If I press `F11` in Firefox, the correct thing happens but obviously that doesn't apply to all apps.

**Comment by stilvoid** [comment]
Edit: I take it all back! Apparently I had failed to set the binding correctly. This does work as expected :D
