### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by Oman395** [material-shell/material-shell#763]
**Is your feature request related to a problem? Please describe.**
With the release of gnome shell 42 around the corner, I would love to see support in material shell.

This would most likely involve parity changes to match the tweaked UI style of the update.

**Describe the solution you'd like**
Full support for gnome shell 42, probably with UI changes for parity.

**Describe alternatives you've considered**
I don't really know any alternatives. It could just be supported already, or we could just stay on an old version of gnome.

**Comment by PapyElGringo** [comment]
Doest Material Shell start without issue with only the metadata change?

**Comment by mhkarimi1383** [comment]
I'm waiting for that too using ArchLinux

**Comment by Rishabh672003** [comment]
yeah i love this extension please port it to gnome 42

**Comment by PapyElGringo** [comment]
The `gnome42` branch is ready to be tested don't hesitate to join https://discord.com/channels/584783412959641716/958324397234589716 for feedback too

**Comment by njakes** [comment]
How do you change branches?

**Comment by mhkarimi1383** [comment]
it was okay for me :)

**Comment by mhkarimi1383** [comment]
> How do you change branches?

```bash
git clone git@github.com:material-shell/material-shell.git -b gnome42
cd material-shell
make
git pull --recurse-submodules
git pull --recurse
make
rm package-lock.json # one of packages from package-lock  have problem with linux 
rm -rf node_modules # one of packages from package-lock  have problem with linux 
npm cache verify # one of packages from package-lock  have problem with linux 
sudo npm i -g npm
make install
```

**Comment by mhkarimi1383** [comment]
I get random crashes and some apps (like PyCharm and GoLand) randomly disappear

**Comment by PapyElGringo** [comment]
@mhkarimi1383 Can you reproduce the crashes?

**Comment by mhkarimi1383** [comment]
> @solinium Do you face reproductible crash?
> 

No crash for material shell or anything Just invisibility of appit happen alot

**Comment by PapyElGringo** [comment]
Gnome 42 compatibility is release ! If you found anymore issues please open separate issue
