### ISSUE TITLE
changing the keyboard layout changes the shell layout instead

### ISSUE THREAD

**Issue by AmSaleh21** [material-shell/material-shell#774]
**Describe the bug**
When I try to switch language with 'super+space' the shell changes the layout instead -Maximize to Split to Half ... -
the 'alt+shift' combo also doesn't work

**Expected behavior**
to switch the different keyboard language layout

**To Reproduce**
- Occurs on:
  - [x] Wayland
- GNOME Shell version: 41.4
- Distro: Manjaro 21.2.5
- Steps to reproduce, if applicable:
1. super+space
2. Bug

**Comment by Meister1593** [comment]
i think it's duplicate of #346

**Comment by IceDBorn** [comment]
Just go into the extension's hotkey settings and set the cycle layout shortcut from Disabled to something else.

**Comment by AmSaleh21** [comment]
> Just go into the extension's hotkey settings and set the cycle layout shortcut from Disabled to something else.

not available through the material shell's key binding.

**Comment by AmSaleh21** [comment]
> i think it's duplicate of #346

confirmed, closing this one, for feature searchers there is a workaround. change gnome layout switch with switchback, and ```ctrl-space``` will work fine switching keyboard layouts, but you won't be able to switch material shell layout with keyboard binding unless it is shown in the settings in the feature.
