### ISSUE TITLE
Windows not resizable

### ISSUE THREAD

**Issue by dn9z** [material-shell/material-shell#777]
Windows are not resizable. Sometimes there is a 1 pixel border where I am able to resize windows. I have tried material shell in ubuntu, fedora, arch on vmware as well as virtualbox to no avail, same issue everywhere.

**Comment by Luctins** [comment]
Same here, this is a regression when updating to gnome 40+

**Comment by dn9z** [comment]
Lots of problems just got fixed, including the resizing issue. Nice!
