### ISSUE TITLE
Allow disabling the automatic moving of windows into their "proper" workspace category

### ISSUE THREAD

**Issue by bwnance** [material-shell/material-shell#79]
For my workflow, it's really helpful to be able to pop open windows in any workspace without them moving to their "correct" one. I'd really like an option to disable this functionality.

**Comment by Kibouo** [comment]
This would also be needed for #60. Custom categories could contain apps from other categories.

A "you already added this app to another category"-exception would be too restricting I find.

**Comment by jadbox** [comment]
To add here, it would be nice to disable all categories (or make all workspaces 'custom categories') so that apps can be freely moved around.

**Comment by dyllandry** [comment]
It is a bit tedious while reading documentation to keep swapping between "internet" apps and "development" apps.

**Comment by PapyElGringo** [comment]
You can move a browser instance in the development category if you want at any time. It's not because the browser open as default in a category that it's can be switched afterward.

**Comment by bwnance** [comment]
Regardless, it's easiest to not have to go and find that browser window in
the first place and just have it open in the current workspace.

**Comment by ioparaskev** [comment]
Even if you choose to move it manually to another workspace (obviously it would be best to avoid having to move every app to your workspace preference and have the shell honor the workspace you are in when opening an app), if for some reason you open a pop up window in that app (for example a settings window), that window goes to it's "predestined" workspace.

For example:

1. I am on the "Games" workspace (I don't play games, so I want to make use of this workspace for other apps)
2. I open thunderbird. Thunderbird pops to the "Social" workspace
3. I move thunderbird to the "Games" workspace
4. I want to send an email, so I press the "Write" button in Thunderbird (or any other button that will open another window).
5. The compose email window is now on the "Social" workspace. And if I already have other tiled apps there, it will mess the tiling as well. What's funny is that pressing the "Write" button also transfers you to that workspace. So in that case you see the new window. If for example I press Tools -> Message Filters, a new window opens in the "Social" workspace but I'm not even transferred there. So I have to remember at which workspace this app belongs and go check if a window has opened there...

In any case, if the shell didn't enforce opening the apps to the workspace category of its liking, it would solve two problems with one stone:
1. Avoid having to manually move apps to other workspaces
2. Avoid popping windows to different workspaces than the one I'm currently at

**Comment by PapyElGringo** [comment]
Theses issues only happen because you use the "Game" workspace for something different. All theses issues will be fixed when the customized categories engine will land. The categorized workspaces will try to magnet their apps and the uncategorized ones will open the apps in the current ones.

But I understand that the current behavior is annoying. The product is not yet completed and therefore some usecases are still broken.

**Comment by ioparaskev** [comment]
Is there a way to change the app category manually? A config file or something? From what I see thunderbird gets moved to the "proper" workspace even when new mail arrives

**Comment by matthijsvk** [comment]
Where is this implemented so I can disable it?
It would be very nice to be able to disable the custom categories, and automatic moving to the category workspaces as above.
ie instead of 'games', 'social' etc just 1, 2, 3, 4.

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
