### ISSUE TITLE
Improve system tray layout when using large panel sizes

### ISSUE THREAD

**Issue by AlbinoGeek** [material-shell/material-shell#838]
**Is your feature request related to a problem? Please describe.**

The system tray doesn't look right on my system, because I use large icons for the categories and windows (90% blind) -- leading to a system tray that looks like it could host 3 icons in the same space it only hosts one.

![image](https://user-images.githubusercontent.com/1910461/174454601-9136ec7e-1c01-42f0-8fe6-75b91e5c3d8c.png)

**Describe the solution you'd like**

You know how the system tray in Windows "upgrades" to wrapping flexbox when there are many icons? I think this would be a wonderful addition to material-shell, as I have a lot of applications with tray icons.

I feel like literally any other layout would look better, here are some mspaint-equiv examples to get the point across:

![image](https://user-images.githubusercontent.com/1910461/174454933-770325a7-2da3-4650-86de-ff14fc0b104f.png)

**Note**: I didn't have to resize any of the icons, just move them about, which shows how much wasted space there is when you have larger category icons and these tiny tiny tray icons.

**Describe alternatives you've considered**

Resizing the tray icon items would be nice, but that's not an option either.

**Comment by PapyElGringo** [comment]
@AlbinoGeek Can you confirm that your issue is now fixed?

**Comment by AlbinoGeek** [comment]
@PapyElGringo This works well now!

Unfortunately the system keeps complaining that Material Shell has an update, whenever I use the version from the repository -- but it's working well.

The only icon that is not correctly spaced is the keyboard switcher.

![image](https://user-images.githubusercontent.com/1910461/175877890-87295355-1230-41e0-b328-e5cafc4a5062.png)
