### ISSUE TITLE
Material Shell does not keep more than 2 workspaces in persistent state

### ISSUE THREAD

**Issue by IceDBorn** [material-shell/material-shell#864]
**Describe the bug**
I'm pinning my apps on different workspaces (10), material shell only keeps the first two after a reboot. Dynamic workspaces are enabled in the gnome settings.

**Expected behavior**
Material shell should keep all pinned apps in all workspaces.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 42.3.1
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Pin apps, creating more than two workspaces
2. Log out/Reboot
3. All of the workspaces, except the first two, are gone.

**Comment by IceDBorn** [comment]
Having workspaces set to a static number instead of dynamic, fixes the issue.

**Comment by kcpr** [comment]
Thank You. I have the same issue.

> Having workspaces set to a static number instead of dynamic, fixes the issue.

It's not a real solution though I think, a workaround rather. Noticed the same though.

I tried to go back to some previous commit and the issue stays. I believe it probably has something to do with some Gnome Shell update. Looks like a "placeholders" are no longer enough for Gnome Shell to not automatically remove a workspace.

And it's not required to log out to reproduce the bug I think, it's just enough to:
1. Pin some applications in, for example, second and third workspace.
2. Close all applications in the third workspace (a placeholder will appear).
3. Close all applications in the second workspace - third workspace should be removed (and there should be no "+" on the workspaces list).

**Comment by IceDBorn** [comment]
@kcpr You are right, it's not a fix, just a workaround, it's an issue with gnome shell itself not the extension and you can reproduce this without logging out/rebooting.

**Comment by PapyElGringo** [comment]
can you guys list the enabled extensions? we had the same issue with auto move window extensions

**Comment by IceDBorn** [comment]
@PapyElGringo I enabled auto move windows and this occured.

**Comment by IceDBorn** [comment]
I'll try disabling the extension when I get back home and I'll report back.

**Comment by IceDBorn** [comment]
@PapyElGringo Auto move windows caused this.

**Comment by kcpr** [comment]
Yes, I confirm - after disabling that extension it works correctly.
I assume that the full list of extensions I have installed is no longer necessary.
Thank You a lot! And for the whole extension by the way!
