### ISSUE TITLE
Appindicator and other icons have shrank

### ISSUE THREAD

**Issue by rwjack** [material-shell/material-shell#866]
**Describe the bug**
Ever since a few months ago, all the appindicators have shrank. Tested on my desktop, with different scaling options.

I haven't updated my laptop in a while, and I used this version:
https://github.com/ragnarokxg/material-shell-ragnarokxg/tree/feature/app-launcher-optional
After updating to latest today, the icons shrank on my laptop as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/59068073/184629434-59c72a9a-3135-479c-8be6-69592aa6228a.png)

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell 42.1
- Distro: Ubuntu 22.04

**Current commit**
Latest from gnome shell extensions

**Comment by HalfVoxel** [comment]
We resized icons around that time. So this is to be expected. The `en` text looks a bit large in comparison, though.
