### ISSUE TITLE
Completely hide / disable horizontal panel

### ISSUE THREAD

**Issue by paulodiovani** [material-shell/material-shell#868]
**Is your feature request related to a problem? Please describe.**
The horizontal panel takes too much space, especially compared to default gnome top bar.

**Describe the solution you'd like**
Add the ability to disable or hide the horizontal panel (this is not zen-mode, as I still want the vertical panel).

**Describe alternatives you've considered**
- Reduce the horizontal panel size independently from vertical panel.
- Disable the taskbar.
- Keep the original gnome topbar with its full functionality (tray icons, watch and calendar, active window name...) alongside the vertical bar

**Comment by rwjack** [comment]
I'm looking forward to this feature so much! Unfortunately Papy mentioned that he won't be working on this since it doesn't fit the material shell workflow. Trust me, I don't understand either.

But I was thinking of creating a "community fork" and changing some core features, though I'm not really a TS expert.

**Comment by paulodiovani** [comment]
In the end, I decided to use Pop-Shell instead. Material-shell gave me a couple of weird issues on Wayland (like hiding the mouse cursor, somehow forbidding to click anywhere until I switch workspace to change the layout).

The extension is great and the change from the workspace preview to app icons is awesome, but right now I'll stick with a tiling extension that doesn't change Gnome too much.

I'll close the issue, if someone else wants it please open it back. ;)

**Comment by rwjack** [comment]
@paulodiovani Thanks for opening my eyes with pop-shell. It's has less of a tiling WM vibe with less features obviously, but that makes it more customizable, helping get rid of the horizontal panel finally...
