### ISSUE TITLE
Gnome-shell crash with material-shell enabled on Ubuntu 22.10

### ISSUE THREAD

**Issue by dturkin** [material-shell/material-shell#905]
Gnome-shell crash after enabling material-shell

Output from syslog:
Oct 23 10:28:14 gnome-shell[4202]: GNOME Shell crashed with signal 11
Oct 23 10:28:14 gnome-shell[4202]: == Stack trace for context 0x56362cd31640 ==
Oct 23 10:28:14 kernel: [   35.458622] gnome-shell[4202]: segfault at 8 ip 00007f88b6b811d6 sp 00007ffd500ffa58 error 4 in libmozjs-102.so.102.3.0[7f88b650e000+aea000]
Oct 23 10:28:14 kernel: [   35.458631] Code: 81 e2 ff ff ff 0f 48 85 c0 74 08 48 8b 40 08 48 83 c0 21 48 01 d0 48 89 45 00 48 83 c4 08 5b 5d c3 0f 1f 00 48 8b 17 48 89 f8 <48> 8b 4a 08 89 ce 83 e6 0f 83 fe 01 74 5c 80 7f 24 00 75 46 48 c1

Tried to re-install but it didn't help

- Occurs on:
  - [ ] X.Org
  - [X] Wayland
- GNOME Shell version: 43
- Distro: Ubuntu 22.10
- Steps to reproduce, if applicable:
1. Step 1
2. Step 2
3. ???
4. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `4376a97`

**Log data**
Output from syslog:
Oct 23 10:28:14 gnome-shell[4202]: GNOME Shell crashed with signal 11
Oct 23 10:28:14 gnome-shell[4202]: == Stack trace for context 0x56362cd31640 ==
Oct 23 10:28:14 kernel: [   35.458622] gnome-shell[4202]: segfault at 8 ip 00007f88b6b811d6 sp 00007ffd500ffa58 error 4 in libmozjs-102.so.102.3.0[7f88b650e000+aea000]
Oct 23 10:28:14 kernel: [   35.458631] Code: 81 e2 ff ff ff 0f 48 85 c0 74 08 48 8b 40 08 48 83 c0 21 48 01 d0 48 89 45 00 48 83 c4 08 5b 5d c3 0f 1f 00 48 8b 17 48 89 f8 <48> 8b 4a 08 89 ce 83 e6 0f 83 fe 01 74 5c 80 7f 24 00 75 46 48 c1

**Comment by onefish2** [comment]
I have been seeing this exact behavior since 221.0 was in beta. I verified the same experience on a clean install of Ubuntu Gnome 22.10.

**Comment by mgrb** [comment]
Same problem!!!!
Using X.Org and Wayland.

**Comment by PapyElGringo** [comment]
Any logs?

**Comment by dturkin** [comment]
`ноя 08 09:27:33 dturkin-ljxl gnome-shell[2118]: Running GNOME Shell (using mutter 43.0) as a Wayland display server
ноя 08 09:27:33 dturkin-ljxl gnome-shell[2118]: Device '/dev/dri/card0' prefers shadow buffer
ноя 08 09:27:33 dturkin-ljxl gnome-shell[2118]: Added device '/dev/dri/card0' (i915) using atomic mode setting.
ноя 08 09:27:33 dturkin-ljxl gnome-shell[2118]: Created gbm renderer for '/dev/dri/card0'
ноя 08 09:27:33 dturkin-ljxl gnome-shell[2118]: Boot VGA GPU /dev/dri/card0 selected as primary
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Using public X11 display :1024, (using :1025 for managed services)
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Using Wayland display name 'wayland-0'
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Will monitor session c1
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Extension ubuntu-appindicators@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-appin>
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Extension ubuntu-dock@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.co>
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Extension ding@rastersoft.com already installed in /usr/share/gnome-shell/extensions/ding@rastersoft.com. /us>
ноя 08 09:27:34 dturkin-ljxl org.gnome.Shell.desktop[2118]: Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm3/.config/mutter/sessions/109ddf2d82c1a0826716678888539995600000019680000.ms”: No such file or directory
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS ERROR: TypeError: this._managerProxy is undefined
                                                   _onGeoclueVanished@resource:///org/gnome/shell/ui/status/location.js:163:9
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
ноя 08 09:27:34 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
                                                   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: ATK Bridge is disabled but a11y has already been enabled.
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: Registering session with GDM
ноя 08 09:27:35 dturkin-ljxl gnome-shell[2118]: Could not open device /dev/input/event22: GDBus.Error:System.Error.ENODEV: No such device
ноя 08 09:27:37 dturkin-ljxl gnome-shell[2118]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
                                                   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
ноя 08 09:27:40 dturkin-ljxl gnome-shell[3867]: Running GNOME Shell (using mutter 43.0) as a Wayland display server
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Device '/dev/dri/card0' prefers shadow buffer
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Added device '/dev/dri/card0' (i915) using atomic mode setting.
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Enabling experimental feature 'scale-monitor-framebuffer'
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Created gbm renderer for '/dev/dri/card0'
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Boot VGA GPU /dev/dri/card0 selected as primary
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Using public X11 display :0, (using :1 for managed services)
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Using Wayland display name 'wayland-0'
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Will monitor session 2
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: Telepathy is not available, chat integration will be disabled.
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:41 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:42 dturkin-ljxl gnome-shell[3867]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
ноя 08 09:27:43 dturkin-ljxl gnome-shell[3867]: GNOME Shell started at Tue Nov 08 2022 09:27:41 GMT+0300 (Moscow Standard Time)
ноя 08 09:27:43 dturkin-ljxl gnome-shell[3867]: Registering session with GDM
ноя 08 09:27:43 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:43 dturkin-ljxl ubuntu-appindicators@ubuntu.com[3867]: unable to update icon for blueman
ноя 08 09:27:43 dturkin-ljxl ubuntu-appindicators@ubuntu.com[3867]: Impossible to send about-to-show to menu: Gio.DBusError: GDBus.Error:org.freedesktop.DBus>
ноя 08 09:27:43 dturkin-ljxl ubuntu-appindicators@ubuntu.com[3867]: unable to update icon for blueman
ноя 08 09:27:43 dturkin-ljxl gnome-shell[3867]: ATK Bridge is disabled but a11y has already been enabled.
ноя 08 09:27:44 dturkin-ljxl gnome-shell[3867]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:27:44 dturkin-ljxl ubuntu-appindicators@ubuntu.com[3867]: unable to update icon for remmina-icon
ноя 08 09:27:47 dturkin-ljxl gnome-shell[3867]: JS ERROR: Exception in callback for signal: hidden: Error: Page -2 does not exist at IconGrid
                                                   getItemsAtPage@resource:///org/gnome/shell/ui/iconGrid.js:1383:19
                                                   _translatePreviousPageIcons@resource:///org/gnome/shell/ui/appDisplay.js:323:34
                                                   _syncPageIndicators@resource:///org/gnome/shell/ui/appDisplay.js:396:14
                                                   goToPage@resource:///org/gnome/shell/ui/appDisplay.js:445:14
                                                   goToPage@resource:///org/gnome/shell/ui/appDisplay.js:1236:29
                                                   goToPage@resource:///org/gnome/shell/ui/appDisplay.js:1582:15
                                                   _init/<@resource:///org/gnome/shell/ui/appDisplay.js:1327:52
                                                   _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                                   _hideDone@resource:///org/gnome/shell/ui/overview.js:589:18
                                                   _animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:566:55
                                                   onStopped@resource:///org/gnome/shell/ui/overviewControls.js:753:21
                                                   _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:150:22
                                                   _easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:316:60
ноя 08 09:27:50 dturkin-ljxl gnome-shell[3867]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesk>
ноя 08 09:27:50 dturkin-ljxl gnome-shell[3867]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesk>
ноя 08 09:27:50 dturkin-ljxl gnome-shell[3867]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.DBusError: GDBus.Error:org.freedesk>
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: WARNING: addSignalMethods is replacing existing [object Object] connect method
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: WARNING: addSignalMethods is replacing existing [object Object] emit method
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was d>
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: --------------
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: INIT EXTENSION
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: --------------
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: ----------------
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: ENABLE EXTENSION
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: ----------------
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: Disabled gnome extension ubuntu-dock@ubuntu.com because it is incompatible with Material Shell
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: Disabled gnome extension ding@rastersoft.com because it is incompatible with Material Shell
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: GNOME Shell crashed with signal 11
ноя 08 09:27:56 dturkin-ljxl gnome-shell[3867]: == Stack trace for context 0x5576964c5640 ==
Nov  8 09:27:56 dturkin-ljxl kernel: [   38.250700] gnome-shell[3867]: segfault at 8 ip 00007f1f56b811d6 sp 00007fffd53b3598 error 4 in libmozjs-102.so.102.3.
0[7f1f5650e000+aea000]
Nov  8 09:27:56 dturkin-ljxl kernel: [   38.250711] Code: 81 e2 ff ff ff 0f 48 85 c0 74 08 48 8b 40 08 48 83 c0 21 48 01 d0 48 89 45 00 48 83 c4 08 5b 5d c3 0
f 1f 00 48 8b 17 48 89 f8 <48> 8b 4a 08 89 ce 83 e6 0f 83 fe 01 74 5c 80 7f 24 00 75 46 48 c1
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Running GNOME Shell (using mutter 43.0) as a Wayland display server
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Device '/dev/dri/card0' prefers shadow buffer
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Added device '/dev/dri/card0' (i915) using atomic mode setting.
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Created gbm renderer for '/dev/dri/card0'
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Boot VGA GPU /dev/dri/card0 selected as primary
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Using public X11 display :1024, (using :1025 for managed services)
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Using Wayland display name 'wayland-0'
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: Will monitor session c2
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:06 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Extension ubuntu-appindicators@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-appi>
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Extension ubuntu-dock@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.c>
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Extension ding@rastersoft.com already installed in /usr/share/gnome-shell/extensions/ding@rastersoft.com. /u>
ноя 08 09:28:07 dturkin-ljxl org.gnome.Shell.desktop[10427]: Window manager warning: Failed to parse saved session file: Failed to open file “/var/lib/gdm3/.config/mutter/sessions/106b1d8c39961b9381166788888620105300000103830000.ms”: No such file or directory
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Failed to query file info on '/var/lib/gdm3/.local/share/icc/.goutputstream-DNLBV1': Error when getting information for file “/var/lib/gdm3/.local/share/icc/.goutputstream-DNLBV1”:
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Failed to query file info on '/var/lib/gdm3/.local/share/icc/.goutputstream-KKLBV1': Error when getting information for file “/var/lib/gdm3/.local/share/icc/.goutputstream-KKLBV1”:
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: Failed to query file info on '/var/lib/gdm3/.local/share/icc/.goutputstream-QILBV1': Error when getting information for file “/var/lib/gdm3/.local/share/icc/.goutputstream-QILBV1”:
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 287]: Too many arguments to method Gio.AsyncInitable.init_async: expected 3, got 4
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: ATK Bridge is disabled but a11y has already been enabled.
ноя 08 09:28:07 dturkin-ljxl gnome-shell[10427]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
                                                    asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
ноя 08 09:28:08 dturkin-ljxl gnome-shell[10427]: Registering session with GDM
ноя 08 09:28:09 dturkin-ljxl gnome-shell[10427]: JS ERROR: Gio.IOErrorEnum: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
                                                    asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23
`

**Comment by PapyElGringo** [comment]
Can you guys try to disable `ubuntu-dock@ubuntu.com` and `ding@rastersoft.com` (Desktop Icon NG) manually before enabling material shell? It's seem that the crash happen when we are trying to disable them ourselves

**Comment by dturkin** [comment]
Already tried. Result is the same

**Comment by PapyElGringo** [comment]
this should be fixed in last commit

**Comment by dturkin** [comment]
Work like a charm now! Thanks!!!
