### ISSUE TITLE
workspace closing windows leaves empty spot in row

### ISSUE THREAD

**Issue by zh54tg234f** [material-shell/material-shell#916]
**Describe the bug**
workspace closing windows leaves empty spot in row

**Expected behavior**
i think it was previously that empty work-spaces were removed and sometimes it still happens but only when its not between two other work-spaces. i don't have session persistence enabled. 

maybe its intent as such than it would be no bug but a feature request to make a setting for disabling this preserving empty work-spaces.

**Screenshots**
the great drawn red circle 

![workspace-empty-spots](https://user-images.githubusercontent.com/117942238/201521580-0a59a0b8-10bf-41c4-b535-55e00cbdc69a.png)

also this happens :

![not-amused](https://user-images.githubusercontent.com/117942238/201521962-51a2169b-9607-4bff-8be5-561831c8cc35.png)

**To Reproduce**
- Occurs on:
  - [x] Wayland
- GNOME Shell 43.1 
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Step 1 create multiple work-spaces with applications running
2. Step 2 close them in the workspace between two other ones
3. See the gap 

thank you so much for this awesome project

**Comment by PapyElGringo** [comment]
You probably activated an incompatible extensions like auto move app or something

**Comment by zh54tg234f** [comment]
uff im very sorry, must have happened by accident
