### ISSUE TITLE
ratio & grid layout results in unclickable windows [ incorrect click translation to wrong position or through application to what ever is behind]

### ISSUE THREAD

**Issue by zh54tg234f** [material-shell/material-shell#917]
**Describe the bug**
the window is correctly displayed but i cant click and get the effect as if i would click on the background without a window being present.
(mainly happened with VLC media player a lot but others as well,
also sometimes the relation of where i click and where it actually sends the click position to the application is wrong resulting in clicking  next to where i actually clicked resulting in bad user experience.)
 
the issue does not seem to be related to which position or size the application has. (beside half screen, some times i move it a few times and it works again and some times have to make it "huge" enough like half screen or maximize than its working again)

**Expected behavior**
being able to click and the click arrives at the position and the window  i clicked, not behind nor somewhere else in the actual window

**Screenshots**

![smaller2](https://user-images.githubusercontent.com/117942238/202922095-c442769a-97e6-4a78-a27a-d69753807ad2.png)

this change background pop up shows the click was send to what is behind the application

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 43
- Distro: Arch
- Steps to reproduce, if applicable:
1. Step 1 use ratio  / grid
2. Step 2 open multiple windows - 4 windows minimum (increases probability, but bug rarely occurs with just one window being not full screen)
3. check if you can click in the application (best is right click as seen on the screenshot)
4. Bug: see your click was send to the background and not the application which sucks

**Current commit**
latest stable 

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
tell me if you rly need it
```

**Comment by zh54tg234f** [comment]
happens on grid as well (5 windows opened) - 1/3 of screen seems not enough as well 
(using 4k display)

![grid-problem3](https://user-images.githubusercontent.com/117942238/202975959-3e7428d4-f334-48ef-9ae4-e9a8937da8c7.png)

grid also has the wrong translation of click position sometimes... (offset from a few hundredth pixels)


i click somewhere left and the click gets translated way to far on the right

**Comment by zh54tg234f** [comment]
okay i got it now with no other windows opened


![fullsc](https://user-images.githubusercontent.com/117942238/203039927-561b76b8-1366-40af-9fdf-e069869806fd.png)

maybe its something gab related , will edit in case it is

**Comment by PapyElGringo** [comment]
This has probably been fixed by https://github.com/material-shell/material-shell/pull/936

**Comment by zh54tg234f** [comment]
will reopen in case it is not
