### ISSUE TITLE
Insane RAM and CPU usage

### ISSUE THREAD

**Issue by sandikata** [material-shell/material-shell#933]
**Describe the bug**
Insane RAM and CPU usage after 12 hours in screen off.
7.71 gb          +       15.79 mb        =       7.72 gb         gnome-shell

**Expected behavior**
To work properly

**Screenshots**

**To Reproduce**
- Occurs on:
  - [x ] X.Org
  - [ ] Wayland
- GNOME Shell version: 43
- Distro: Gentoo
- Steps to reproduce, if applicable:
1. Step 1
2. Step 2
3. ???
4. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by zh54tg234f** [comment]
Bro you use gentoo and have the decency to fill such a detailed bug report. 
Close Request. Gentoo and Xorg bro... it's so funny 

@sandikata it is most likely a miss configuration on your side of gentoo
never had this on any VM with Xorg and Material Shell (arch)

We dont know what other extension you have that might create that conflict. 
Please check them.

**Comment by sandikata** [comment]
With such behavior from your side, I don't have any desire to continue. Just not gonna use this extension.
I dislike mostly persons who pretend to be always right and to claim other's like morons or whatever because they're dared to use gentoo.

![319039125_5836609749786853_8985000832107640650_n](https://user-images.githubusercontent.com/884699/210937961-756ded9b-b54a-4b4e-a62d-41d95495a596.jpg)

**Comment by zh54tg234f** [comment]
Where did i pretend to be always right? 
So based on your image your statement is that you are garbage / a disappointment? 
Since you provided 0 details about your issue and told us you use Gentoo.
I would never claim Gentoo users are morons , i think asking for help without giving some kind of details will leave your issue unsolved and i communicated that.

**Comment by sandikata** [comment]
With such behavior, I am not about to waste my time to get disrespect because i am using Gentoo with X11.

**Comment by PapyElGringo** [comment]
Hey @sandikata Thanks for you [review](https://extensions.gnome.org/extension/3357/material-shell/?c=139472) on Gnome Extension but @zh54tg234f and Me are two different person.

I have no Idea of what is Gentoo is but it's indeed hard to troubleshoot any issue with this lack of information that could help me to reproduce this issue.

**Comment by sandikata** [comment]
> Hey @sandikata Thanks for you [review](https://extensions.gnome.org/extension/3357/material-shell/?c=139472) on Gnome Extension but @zh54tg234f and Me are two different person.
> 
> I have no Idea of what is Gentoo is but it's indeed hard to troubleshoot any issue with this lack of information that could help me to reproduce this issue.

Hello,
As i've mentioned, i don't have a desire to continue with such disrespect just because i am using Gentoo+X11 combo.
It is build like any binary system out in the world, it uses Gnome 43 on X11 as mentioned already? What else you need ?

**Comment by PapyElGringo** [comment]
You should understand that not everyone is experiencing this ¨Insane RAM and CPU usage¨ so there should be something specific to your system that is related to this issue. 
Without your cooperation there is no way I can figure it out myself.

Don't talk of disrespect when you affiliate me to your argument with @zh54tg234f without any reason because it's a huge of disrespect of my work and the 4 years spent in making open source software

**Comment by sandikata** [comment]
> You should understand that not everyone is experiencing this ¨Insane RAM and CPU usage¨ so there should be something specific to your system that is related to this issue. Without your cooperation there is no way I can figure it out myself.
> 
> Don't talk of disrespect when you affiliate me to your argument with @zh54tg234f without any reason because it's a huge of disrespect of my work and the 4 years spent in making open source software

Hello,
Noted.

Sorry for that.
As I said in my review, it is a great extension. I didn't realize @zh54tg234f is not an extension author.
But it was offensive from his side.

Please let me know what exactly to provide?
I am free now to collect required details.

**Comment by PapyElGringo** [comment]
First be sure to reproduce the issue while disabled all other extensions except Material Shell and be sure to not use AppImage Launcher as it seem to be incompatible with it too

**Comment by sandikata** [comment]
Well, I don't have AppImage Launcher anymore (deleted 2 days ago).
But i have another idea, to try it on a different account with just material shell enabled.
But there will be some delay, as i am too busy those days.

TBH, since AppImage launcher is gone, gnome shell behaves different. With 20 enabled extensions after a day it uses 480 MB of RAM which is more than good (compared to before AppImage launcher removal, it was about 1.3 - 1.5 GB with slowness and freezing). But this has to be investigated in deep.

**Comment by PapyElGringo** [comment]
The issue was related to using `AppImage Launcher`
