### ISSUE TITLE
material-shell-extension

### ISSUE THREAD

**Issue by Gridman44** [material-shell/material-shell#935]
Persistence

The best way to configure the desktop layout is to not have to do it.

Material Shell keeps track of every decision relative to the desktop layout: where are windows, in which workspaces, and in which order.

This allows configuration of the layouts on the go while using it.

When opening a new session Material Shell will restore every window previously present with a "window placeholder which allows you to reopen any of the previous windows easily at the same spot you like to have them.

Is there a magical secret to get windows to stay where i put them? I have multiple monitors.   Ive tried this extension 3  times and get it all set up and my windows are never where i left them and this isn't just after a reboot.  For example if I double click on appimage and appimagelauncher has a pop up window, the pop up window will open up on another display taking multiple windows with it and then refusing to close. Then the reboot and now in a completely different location. Also window focus just has a mind of it's own. Unresponsive to mod+ keys and will have to grab mouse and click on tab in top window to switch if i have more than one window open on that workspace/monitor. Wayland  Gnome 6.1.1-zen1-1-zen  Arch . Don't normally ask but don't really feel like spending time on it. thanks

**Comment by PapyElGringo** [comment]
The only magical secret is to not use `appimagelauncher` as it seem incompatible with Material Shell. We only can retreive data and launch app using `.desktop` files to identify themselves. It's look like the `appimagelauncher` prevent Gnome Shell to retreive app information which lead to the impossibility for us to apply the persistence mechanism

**Comment by rizajur** [comment]
@PapyElGringo  - still relevant i dont get it. Please clean up the out dated issues etc. It would be a huge help or find some one to do it who joined a months / years ago.
