### ISSUE TITLE
New Window Launcher Via Super S Type-To-Launch Application

### ISSUE THREAD

**Issue by bcatalfo** [material-shell/material-shell#947]
**Describe the bug**
Let's say I press super d to a new window. The "type to search" box is highlighted and I can type to search for applications. Visually it gets a blue border. But when I do the same with Super + S the same does not happen. The box is grayed out and I need to click on it to begin search for applications.

**Expected behavior**
A clear and concise description of what you expected to happen, and how the actual outcome differs.

**Screenshots**
![image](https://user-images.githubusercontent.com/28869518/218330603-b7a9aa66-ac9c-4c67-b2ef-edf0573ea2b0.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [ x ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Step 1
2. Step 2
3. ???
4. Bug

**Current commit**
Output from `git rev-parse --short HEAD`: `c7803af`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
example log data
```

**Comment by rizajur** [comment]
>But when I do the same with Super + S the same does not happen. The box is grayed out and I need to click on it to begin search for applications.

I never had this bug, i dont know what you mean with 

>do the same with Super + S

do you mean the super key search why would you press super + s for search ? 
Super + S is cycle one workspace down

**Comment by bcatalfo** [comment]
Sorry for describing the problem poorly. For me I use super + s to go down and super + d to go right. When I go to the right to a new workspace it works as expected but when I go down to a new workspace it doesn't.

**Comment by rizajur** [comment]
3.38.5 is debian bullseye (stable) Gnome Version 

are you talking now about one bug out of 2 or is it just the one bug?

> super + d to go right. When I go to the right to a new workspace it works as expected but when I go down to a new workspace it doesn't.

you mean the auto focus of the search ?

**Comment by bcatalfo** [comment]
Yes!

**Comment by rizajur** [comment]
Okay, i have seen this bug before. I have tried to reproduce it on Debian with 3.38.5 Gnome. (Installed latest version from Extension Store)

>I will update the version and the distro in detail 

so you are now on gnome 43?

**Comment by bcatalfo** [comment]
I will check my version and update it and get back to you by tomorrow. I have a lot of things to do today (ie superbowl). Thank you for taking the time to help.

**Comment by rizajur** [comment]
Please do that, thanks for creating the issue. I don't know why i didn't do it at the time... Life

**Comment by PapyElGringo** [comment]
I do reproduce this on `Main` branch.

@rizajur the gnome 3.38 is pretty old and Material Shell dropped support for this old version since gnome 40 which is a longtime ago. Note that you don't benefits from recent changes

**Comment by bcatalfo** [comment]
Here is my setup- I wanted to upgrade to Gnome 43 but the support from arch doesn't seem very good
![Screenshot from 2023-02-13 18-23-29](https://user-images.githubusercontent.com/28869518/218598509-3cd64e45-1957-44da-b23c-ac11513b8831.png)

**Comment by rizajur** [comment]
lets say arch linux gnome and material shell is tricky depending on the updates
