### ISSUE TITLE
Cannot move windows with the topbar buttons anymore

### ISSUE THREAD

**Issue by tiramiseb** [material-shell/material-shell#958]
**Describe the bug**

In previous versions, I could move windows by dragging the topbar buttons (reorder in current workspace, or move windows to another monitor). There was a bug where I could not move windows to monitors where no windows were open, but I did not take the time to report it.

I have upgraded to the latest git commit in master (`c3d1241..db20eb5`), and now I cannot drag topbar buttons anymore. I have not upgraded anything else at the same time. Same Ubuntu, same GNOME Shell, etc.

**Expected behavior**

Ability to move windows :-)

**Screenshots**

Not applicable.

**To Reproduce**

- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 40.5
- Distro: Ubuntu 21.10 (yes, obsolete, I know, I need to take time to upgrade)

**Current commit**

Output from `git rev-parse --short HEAD`: `db20eb5`

**Log data**

Output from `journalctl /usr/bin/gnome-shell`:

```
avril 19 11:04:52 seblaptop gnome-shell[3053]: JS ERROR: Error: Virtual function not implemented: Class ClutterClickAction doesn't implement long_press
                                               vfunc_long_press@/home/sebastien/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js:557:17

```

**Comment by tiramiseb** [comment]
It looks like it works with GNOME 44 in Ubuntu 23.04.

I still don't have upgraded the computer with multiple monitors, but on my laptop I can drag buttons to reorder windows in the current workspace.

**Comment by PapyElGringo** [comment]
Oh so I guess I made a breaking changes

**Comment by PapyElGringo** [comment]
Can you try last commit?
