### ISSUE TITLE
Feature to hide native titlebar for maximized/tiled windows

### ISSUE THREAD

**Issue by crillon** [material-shell/material-shell#964]
**Is your feature request related to a problem? Please describe.**
The title bar is useless when the window is maximized or tiled.
I found out that in #68 people say this feature is present, but it's not

![image](https://github.com/material-shell/material-shell/assets/43761130/a360d701-adc0-4902-86dd-b2b946192607)
![image](https://github.com/material-shell/material-shell/assets/43761130/27171b87-1582-4da3-87e5-2e04f9b042dd)

I don't know, is this a bug or has this feature been removed?

**Describe the solution you'd like**

- Add an option to the settings menu to remove titlebar when window is
	- Maximized
	- Tiled
	- Both
	- Always

**Describe alternatives you've considered**
There is an extension [GTK Title Bar](https://github.com/velitasali/gtktitlebar) that does just that, but unfortunately it doesn't work when the window is tiled by Material Shell, and it doesn't support gnome 44.

**Comment by crillon** [comment]
I read the code and found that the feature is there, but it doesn't work.
So..
- Occurs on: 
	- [x]  X.Org
	- [ ]  Wayland
- GNOME Shell version: 44.1
- Distro: Manjaro 23.0 (6.1.31-2-MANJARO)

Looks like the problem is here:
https://github.com/material-shell/material-shell/blob/89f460b3717a541082f5b87b514f7cc23e3ea170/src/utils/windows.ts#L23-L47

1) The feature doesn't work even in gnome 43. I think the problem is in line 28, with `!metaWindow.decorated` (I don't know TypeScript and JS. So I can't find what is "decorated", how and where it changes);
2) In gnome 44, line 40 does not work, to hide the titlebar now you need to use 0 instead of 2, I did not find good info about this, so I just refer to other extensions: [No Titlebar When Maximized](https://github.com/alecdotninja/no-titlebar-when-maximized) and https://github.com/velitasali/gtktitlebar/issues/36#issuecomment-1455278899

I changed the code to this..
```typescript
export const setTitleBarVisibility = function (
    metaWindow: MetaWindowWithMsProperties,
    visible: boolean
) {
    const windowXID = getWindowXID(metaWindow);
    if (!windowXID || metaWindow.is_client_decorated()) // 1
        return;
    try {
        Util.trySpawn([
            'xprop',
            '-id',
            windowXID,
            '-f',
            '_MOTIF_WM_HINTS',
            '32c',
            '-set',
            '_MOTIF_WM_HINTS',
            `2, 0, ${visible ? '1' : '0'} 0, 0`, // 2
        ]);
    } catch (e) {
        Me.logFocus('xprop', e);
    }

    metaWindow.titleBarVisible = visible;
};
```
..and it looks like everything is working, but I haven't tested it very well, so there may be some unknown issues with this code.

**Comment by henrybarreto** [comment]
Me too

**Comment by henrybarreto** [comment]
> I read the code and found that the feature is there, but it doesn't work. So..
> 
>     * Occurs on:
>       
>       * [x]   X.Org
>       * [ ]   Wayland
> 
>     * GNOME Shell version: 44.1
> 
>     * Distro: Manjaro 23.0 (6.1.31-2-MANJARO)
> 
> 
> Looks like the problem is here:
> 
> https://github.com/material-shell/material-shell/blob/89f460b3717a541082f5b87b514f7cc23e3ea170/src/utils/windows.ts#L23-L47
> 
>     1. The feature doesn't work even in gnome 43. I think the problem is in line 28, with `!metaWindow.decorated` (I don't know TypeScript and JS. So I can't find what is "decorated", how and where it changes);
> 
>     2. In gnome 44, line 40 does not work, to hide the titlebar now you need to use 0 instead of 2, I did not find good info about this, so I just refer to other extensions: [No Titlebar When Maximized](https://github.com/alecdotninja/no-titlebar-when-maximized) and [Gnome Shell 44 support velitasali/gtktitlebar#36 (comment)](https://github.com/velitasali/gtktitlebar/issues/36#issuecomment-1455278899)
> 
> 
> I changed the code to this..
> 
> ```ts
> export const setTitleBarVisibility = function (
>     metaWindow: MetaWindowWithMsProperties,
>     visible: boolean
> ) {
>     const windowXID = getWindowXID(metaWindow);
>     if (!windowXID || metaWindow.is_client_decorated()) // 1
>         return;
>     try {
>         Util.trySpawn([
>             'xprop',
>             '-id',
>             windowXID,
>             '-f',
>             '_MOTIF_WM_HINTS',
>             '32c',
>             '-set',
>             '_MOTIF_WM_HINTS',
>             `2, 0, ${visible ? '1' : '0'} 0, 0`, // 2
>         ]);
>     } catch (e) {
>         Me.logFocus('xprop', e);
>     }
> 
>     metaWindow.titleBarVisible = visible;
> };
> ```
> 
> ..and it looks like everything is working, but I haven't tested it very well, so there may be some unknown issues with this code.

I'm using your fix here; it seems to solve the problem.

**Comment by jivanpal** [comment]
Issue not present on GNOME 42.x.

**Comment by PapyElGringo** [comment]
Hey guys ! Thanks for waiting ! I made a PR to fix this https://github.com/material-shell/material-shell/pull/977
