### ISSUE TITLE
Material-Shell appears to interrupt edge-scrolling

### ISSUE THREAD

**Issue by anathemamask** [material-shell/material-shell#98]
Memory: 15.7 GiB
Processor: AMD Ryzen 7 2700x eight core processor x 16
Graphics: GeForce RTX 2070/PCIe/SSE2
OS Type: 64-bit.
OS: Ubuntu 19.04.
Linux: 5.0.0-23-generic
Gnome Version: 3.32.1
Session : Xorg
Proprietary Nvidia driver 430
Material-Shell version: 3.32

Material-shell seemed to work fine for general use, but when running certain games such as Rimworld (native, x86_64) and League of Legends (lutris-based WINE-staging DXVK), using the mouse to scroll the camera by dragging it to the edge of the screen does not work.This occurs whether the game is in windowed, fullscreen, or borderless windowed mode. 

 Disabling material-shell immediately resolved this issue.

Settings changed from default:
Layouts - 
Ratio (enabled, all others disabled)
Ratio value - golden ratio (0.62)

Tiling settings -
Gap size - 0
Animation duration - smooth (0.25)

**Comment by PapyElGringo** [comment]
With Material Shell v2 out this issue **SHOULD** be fixed.
